module.exports = [
  // ═══════════════════════════════════════════════════════════════
  // TIER 5: الخوارزميات (30 challenges = 10 lessons × 3 exercises)
  // ═══════════════════════════════════════════════════════════════

  // ── الدرس 1: فرز تصاعدي ──
  { title:'فرز تصاعدي: المثال', description:'(درس) الفرز التصاعدي (الفقاعي Bubble Sort) يرتب عناصر المصفوفة من الأصغر إلى الأكبر عن طريق مقارنة كل عنصر بمن بعده واستبدالهما إذا كان الأول أكبر. هذه الخوارزمية بسيطة لكنها فعالة للمصفوفات الصغيرة، وتعمل بتكرار المقارنات والاستبدالات حتى تصبح جميع العناصر في الترتيب الصحيح.\n\nالكود:\nصحيح[] مصفوفة = [5، 3، 8، 1، 9]\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة) - 1؛ ع = ع + 1) {\n    لكل (صحيح ب = ع + 1؛ ب < طول(مصفوفة)؛ ب = ب + 1) {\n        إذا (مصفوفة[ع] > مصفوفة[ب]) {\n            صحيح مؤقت = مصفوفة[ع]\n            مصفوفة[ع] = مصفوفة[ب]\n            مصفوفة[ب] = مؤقت\n        }\n    }\n}\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}\nالoutput المتوقع: 1\n3\n5\n8\n9', starterCode:'صحيح[] مصفوفة = [5، 3، 8، 1، 9]\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة) - 1؛ ع = ع + 1) {\n    لكل (صحيح ب = ع + 1؛ ب < طول(مصفوفة)؛ ب = ب + 1) {\n        إذا (مصفوفة[ع] > مصفوفة[ب]) {\n            صحيح مؤقت = مصفوفة[ع]\n            مصفوفة[ع] = مصفوفة[ب]\n            مصفوفة[ب] = مؤقت\n        }\n    }\n}\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}', expectedOutput:'1\n3\n5\n8\n9', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:1, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'فرز تصاعدي: تمارين 1', description:'افرز مصفوفة [7، 2، 9، 4، 1] تصاعدياً واطبع كل عنصر في سطر.', starterCode:'', expectedOutput:'1\n2\n4\n7\n9', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:2, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'فرز تصاعدي: تمارين 2', description:'افرز مصفوفة [15، 3، 8، 12، 1] تصاعدياً واطبع كل عنصر في سطر.', starterCode:'', expectedOutput:'1\n3\n8\n12\n15', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:3, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 2: فرز تنازلي ──
  { title:'فرز تنازلي: المثال', description:'(درس) الفرز التنازلي يرتب عناصر المصفوفة من الأكبر إلى الأصغر عن طريق عكس شرط المقارنة في خوارزمية الفرز الفقاعي. بدلاً من التأكد من أن العنصر الأصغر يذهب للأمام، نتأكد من أن العنصر الأكبر يذهب للأمام. هذه الخوارزمية مفيدة عند الحاجة لترتيب النتائج ترتيباً هابطاً مثل ترتيب الدرجات أو الأسعار.\n\nالكود:\nصحيح[] مصفوفة = [5، 3، 8، 1، 9]\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة) - 1؛ ع = ع + 1) {\n    لكل (صحيح ب = ع + 1؛ ب < طول(مصفوفة)؛ ب = ب + 1) {\n        إذا (مصفوفة[ع] < مصفوفة[ب]) {\n            صحيح مؤقت = مصفوفة[ع]\n            مصفوفة[ع] = مصفوفة[ب]\n            مصفوفة[ب] = مؤقت\n        }\n    }\n}\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}\nالoutput المتوقع: 9\n8\n5\n3\n1', starterCode:'صحيح[] مصفوفة = [5، 3، 8، 1، 9]\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة) - 1؛ ع = ع + 1) {\n    لكل (صحيح ب = ع + 1؛ ب < طول(مصفوفة)؛ ب = ب + 1) {\n        إذا (مصفوفة[ع] < مصفوفة[ب]) {\n            صحيح مؤقت = مصفوفة[ع]\n            مصفوفة[ع] = مصفوفة[ب]\n            مصفوفة[ب] = مؤقت\n        }\n    }\n}\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}', expectedOutput:'9\n8\n5\n3\n1', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:4, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'فرز تنازلي: تمارين 1', description:'افرز مصفوفة [7، 2، 9، 4، 1] تنازلياً واطبع كل عنصر في سطر.', starterCode:'', expectedOutput:'9\n7\n4\n2\n1', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:5, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'فرز تنازلي: تمارين 2', description:'افرز مصفوفة [20، 5، 10، 15] تنازلياً واطبع كل عنصر في سطر.', starterCode:'', expectedOutput:'20\n15\n10\n5', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:6, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 3: قلب المصفوفة ──
  { title:'قلب المصفوفة: المثال', description:'(درس) قلب المصفوفة يعني عكس ترتيب عناصرها بحيث يصبح العنصر الأخير هو الأول والعكس ذلك. الطريقة البسيطة هي إنشاء مصفوفة جديدة وملؤها بالعناصر من النهاية إلى البداية. هذه العملية مفيدة في العديد من التطبيقات مثل عكس كلمات أو جمل أو معالجة البيانات بالاتجاه المعاكس.\n\nالكود:\nصحيح[] الأصل = [1، 2، 3، 4، 5]\nصحيح[] المعكوسة = []\nلكل (صحيح ع = طول(الأصل) - 1؛ ع >= 0؛ ع = ع - 1) {\n    المعكوسة[طول(المعكوسة)] = الأصل[ع]\n}\nلكل (صحيح ع = 0؛ ع < طول(المعكوسة)؛ ع = ع + 1) {\n    طباعة(المعكوسة[ع])\n}\nالoutput المتوقع: 5\n4\n3\n2\n1', starterCode:'صحيح[] الأصل = [1، 2، 3، 4، 5]\nصحيح[] المعكوسة = []\nلكل (صحيح ع = طول(الأصل) - 1؛ ع >= 0؛ ع = ع - 1) {\n    المعكوسة[طول(المعكوسة)] = الأصل[ع]\n}\nلكل (صحيح ع = 0؛ ع < طول(المعكوسة)؛ ع = ع + 1) {\n    طباعة(المعكوسة[ع])\n}', expectedOutput:'5\n4\n3\n2\n1', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:7, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'قلب المصفوفة: تمارين 1', description:'قلب مصفوفة [10، 20، 30، 40] واطبع النتيجة.', starterCode:'', expectedOutput:'40\n30\n20\n10', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:8, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'قلب المصفوفة: تمارين 2', description:'قلب مصفوفة ["أ"، "ب"، "ج"، "د"، "هـ"] واطبع النتيجة.', starterCode:'', expectedOutput:'هـ\nد\nج\nب\nأ', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:9, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 4: إزالة التكرارات ──
  { title:'إزالة التكرارات: المثال', description:'(درس) إزالة التكرارات تعني حذف العناصر المتشابهة من المصفوفة بحيث يبقى كل عنصر فريداً مرة واحدة فقط. الطريقة تتم بفحص كل عنصر في المصفوفة الأصلية والتحقق مما إذا كان موجوداً بالفعل في مصفوفة النتيجة، وإذا لم يكن موجوداً نضيفه. هذه العملية مفيدة لتنظيف البيانات والتخلص من المعلومات المكررة.\n\nالكود:\nصحيح[] الأصل = [1، 2، 2، 3، 3، 3]\nصحيح[] النتيجة = []\nلكل (صحيح ع = 0؛ ع < طول(الأصل)؛ ع = ع + 1) {\n    صحيح موجود = خطأ\n    لكل (صحيح ب = 0؛ ب < طول(النتيجة)؛ ب = ب + 1) {\n        إذا (الأصل[ع] == النتيجة[ب]) {\n            موجود = صواب\n        }\n    }\n    إذا (!موجود) {\n        النتيجة[طول(النتيجة)] = الأصل[ع]\n    }\n}\nلكل (صحيح ع = 0؛ ع < طول(النتيجة)؛ ع = ع + 1) {\n    طباعة(النتيجة[ع])\n}\nالoutput المتوقع: 1\n2\n3', starterCode:'صحيح[] الأصل = [1، 2، 2، 3، 3، 3]\nصحيح[] النتيجة = []\nلكل (صحيح ع = 0؛ ع < طول(الأصل)؛ ع = ع + 1) {\n    صحيح موجود = خطأ\n    لكل (صحيح ب = 0؛ ب < طول(النتيجة)؛ ب = ب + 1) {\n        إذا (الأصل[ع] == النتيجة[ب]) {\n            موجود = صواب\n        }\n    }\n    إذا (!موجود) {\n        النتيجة[طول(النتيجة)] = الأصل[ع]\n    }\n}\nلكل (صحيح ع = 0؛ ع < طول(النتيجة)؛ ع = ع + 1) {\n    طباعة(النتيجة[ع])\n}', expectedOutput:'1\n2\n3', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:10, xpReward:70, points:75, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'إزالة التكرارات: تمارين 1', description:'أزل التكرارات من مصفوفة [5، 5، 3، 3، 1، 1] واطبع النتيجة.', starterCode:'', expectedOutput:'5\n3\n1', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:11, xpReward:70, points:75, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'إزالة التكرارات: تمارين 2', description:'أزل التكرارات من مصفوفة [10، 20، 10، 30، 20] واطبع النتيجة.', starterCode:'', expectedOutput:'10\n20\n30', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:12, xpReward:70, points:75, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 5: حسابات على المصفوفة ──
  { title:'حسابات على المصفوفة: المثال', description:'(درس) يمكننا إجراء عمليات حسابية مختلفة على عناصر المصفوفة مثل حساب المجموع والمتوسط والأكبر. العملية تتطلب المرور على جميع العناصر بحلقة تكرارية وجمع القيم، ثم قسمة المجموع على عدد العناصر للحصول على المتوسط. هذه الحسابات أساسية في تحليل البيانات والإحصاء.\n\nالكود:\nصحيح[] الأعداد = [10، 20، 30، 40، 50]\nصحيح المجموع = 0\nلكل (صحيح ع = 0؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    المجموع = المجموع + الأعداد[ع]\n}\nصحيح المتوسط = المجموع / طول(الأعداد)\nطباعة(المتوسط)\nالoutput المتوقع: 30', starterCode:'صحيح[] الأعداد = [10، 20، 30، 40، 50]\nصحيح المجموع = 0\nلكل (صحيح ع = 0؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    المجموع = المجموع + الأعداد[ع]\n}\nصحيح المتوسط = المجموع / طول(الأعداد)\nطباعة(المتوسط)', expectedOutput:'30', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:13, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'حسابات على المصفوفة: تمارين 1', description:'احسب متوسط مصفوفة [5، 10، 15، 20] واطبعه.', starterCode:'', expectedOutput:'12', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:14, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'حسابات على المصفوفة: تمارين 2', description:'احسب أكبر قيمة في مصفوفة [3، 7، 1، 9، 4] واطبعها.', starterCode:'', expectedOutput:'9', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:15, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 6: البحث الخطي ──
  { title:'البحث الخطي: المثال', description:'(درس) البحث الخطي هو أبسط خوارزميات البحث عن عنصر معين في مصفوفة. يتم فحص كل عنصر في المصفوفة واحداً تلو الآخر مقارناً إياه بالقيمة المطلوبة، وإذا وجدناه نسجل فهرسه. هذه الخوارزمية بسيطة لكنها قد تكون بطيئة للمصفوفات الكبيرة، وهي مفيدة عندما لا تكون المصفوفة مرتبة.\n\nالكود:\nصحيح[] الأعداد = [10، 25، 30، 45، 50]\nصحيح الهدف = 30\nصحيح فهرس = -1\nلكل (صحيح ع = 0؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    إذا (الأعداد[ع] == الهدف) {\n        فهرس = ع\n    }\n}\nطباعة(فهرس)\nالoutput المتوقع: 2', starterCode:'صحيح[] الأعداد = [10، 25، 30، 45، 50]\nصحيح الهدف = 30\nصحيح فهرس = -1\nلكل (صحيح ع = 0؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    إذا (الأعداد[ع] == الهدف) {\n        فهرس = ع\n    }\n}\nطباعة(فهرس)', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:16, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'البحث الخطي: تمارين 1', description:'ابحث عن الرقم 15 في مصفوفة [5، 10، 15، 20، 25] واطبع فهرسه.', starterCode:'', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:17, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'البحث الخطي: تمارين 2', description:'ابحث عن الرقم 100 في مصفوفة [10، 20، 30] واطبع فهرسه (إذا لم يوجده اطبع -1).', starterCode:'', expectedOutput:'-1', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:18, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 7: عكس مصفوفة بدون مصفوفة جديدة ──
  { title:'قلب بدون مصفوفة جديدة: المثال', description:'(درس) قلب المصفوفة في مكانها (In-place) يعني عكس ترتيب العناصر دون إنشاء مصفوفة جديدة، مما يوفر الذاكرة. يتم ذلك عن طريق تبادل العناصر من الطرفين نحو المركز، بحيث نبدل العنصر الأول مع الأخير والثاني مع ما قبل الأخير وهكذا. هذه الطريقة أكثر كفاءة من الطريقة السابقة لأنها لا تحتاج لمساحة إضافية.\n\nالكود:\nصحيح[] مصفوفة = [1، 2، 3، 4، 5]\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة) / 2؛ ع = ع + 1) {\n    صحيح مؤقت = مصفوفة[ع]\n    مصفوفة[ع] = مصفوفة[طول(مصفوفة) - 1 - ع]\n    مصفوفة[طول(مصفوفة) - 1 - ع] = مؤقت\n}\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}\nالoutput المتوقع: 5\n4\n3\n2\n1', starterCode:'صحيح[] مصفوفة = [1، 2، 3، 4، 5]\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة) / 2؛ ع = ع + 1) {\n    صحيح مؤقت = مصفوفة[ع]\n    مصفوفة[ع] = مصفوفة[طول(مصفوفة) - 1 - ع]\n    مصفوفة[طول(مصفوفة) - 1 - ع] = مؤقت\n}\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}', expectedOutput:'5\n4\n3\n2\n1', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:19, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'قلب بدون مصفوفة جديدة: تمارين 1', description:'قلب مصفوفة [10، 20، 30] في مكانها واطبع النتيجة.', starterCode:'', expectedOutput:'30\n20\n10', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:20, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'قلب بدون مصفوفة جديدة: تمارين 2', description:'قلب مصفوفة [1، 2، 3، 4] في مكانها واطبع النتيجة.', starterCode:'', expectedOutput:'4\n3\n2\n1', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:21, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 8: فرز الدمج ──
  { title:'دمج مصفوفتين: المثال', description:'(درس) دمج المصفوفتين يعني التجمع بين عنصرين من مصفوفتين مختلفتين في مصفوفة واحدة جديدة. يتم ذلك عن طريق نسخ عناصر المصفوفة الأولى أولاً ثم نسخ عناصر المصفوفة الثانية بعدها. هذه العملية مفيدة عند الحاجة لدمج قوائم بيانات أو مجموعات من المعلومات في قائمة واحدة موحدة.\n\nالكود:\nصحيح[] م1 = [1، 3، 5]\nصحيح[] م2 = [2، 4، 6]\nصحيح[] الدمج = []\nلكل (صحيح ع = 0؛ ع < طول(م1)؛ ع = ع + 1) {\n    الدمج[طول(الدمج)] = م1[ع]\n}\nلكل (صحيح ع = 0؛ ع < طول(م2)؛ ع = ع + 1) {\n    الدمج[طول(الدمج)] = م2[ع]\n}\nلكل (صحيح ع = 0؛ ع < طول(الدمج)؛ ع = ع + 1) {\n    طباعة(الدمج[ع])\n}\nالoutput المتوقع: 1\n3\n5\n2\n4\n6', starterCode:'صحيح[] م1 = [1، 3، 5]\nصحيح[] م2 = [2، 4، 6]\nصحيح[] الدمج = []\nلكل (صحيح ع = 0؛ ع < طول(م1)؛ ع = ع + 1) {\n    الدمج[طول(الدمج)] = م1[ع]\n}\nلكل (صحيح ع = 0؛ ع < طول(م2)؛ ع = ع + 1) {\n    الدمج[طول(الدمج)] = م2[ع]\n}\nلكل (صحيح ع = 0؛ ع < طول(الدمج)؛ ع = ع + 1) {\n    طباعة(الدمج[ع])\n}', expectedOutput:'1\n3\n5\n2\n4\n6', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:22, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'دمج مصفوفتين: تمارين 1', description:'ادمج مصفوفتي [10، 20] و [30، 40] واطبع النتيجة.', starterCode:'', expectedOutput:'10\n20\n30\n40', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:23, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'دمج مصفوفتين: تمارين 2', description:'ادمج مصفوفتي ["أ"، "ب"] و ["ج"، "د"] واطبع النتيجة.', starterCode:'', expectedOutput:'أ\nب\nج\nد', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:24, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 9: تحويل أنظمة العد ──
  { title:'تحويل أنظمة العد: المثال', description:'(درس) تحويل الأعداد من النظام العشري إلى الثنائي يعني تمثيل العدد بنظام عد يعتمد على رقمين فقط (0 و 1). يتم ذلك عن طريق قسمة العدد على 2 باستمرار وجمع الباقي، ثم عكس ترتيب الأرقام للحصول على النتيجة. هذا التحويل أساسي في الحاسبات الإلكترونية لأنها تعمل بالنظام الثنائي.\n\nالكود:\nصحيح عدد = 10\nنص ثنائي = ""\nطالما (عدد > 0) {\n    صحيح باقي = عدد % 2\n    ثنائي = باقي + ثنائي\n    عدد = عدد / 2\n}\nطباعة(ثنائي)\nالoutput المتوقع: 1010', starterCode:'صحيح عدد = 10\nنص ثنائي = ""\nطالما (عدد > 0) {\n    صحيح باقي = عدد % 2\n    ثنائي = باقي + ثنائي\n    عدد = عدد / 2\n}\nطباعة(ثنائي)', expectedOutput:'1010', requirements:'[{"type":"must_use_keyword","keyword":"طالما"},{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:25, xpReward:70, points:75, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'تحويل أنظمة العد: تمارين 1', description:'حوّل العدد 8 إلى نظام عد ثنائي واطبعه.', starterCode:'', expectedOutput:'1000', requirements:'[{"type":"must_use_keyword","keyword":"طالما"},{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:26, xpReward:70, points:75, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'تحويل أنظمة العد: تمارين 2', description:'حوّل العدد 15 إلى نظام عد ثنائي واطبعه.', starterCode:'', expectedOutput:'1111', requirements:'[{"type":"must_use_keyword","keyword":"طالما"},{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:27, xpReward:70, points:75, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 10: ترتيب الأزواج ──
  { title:'ترتيب الأزواج: المثال', description:'(درس) ترتيب الأزواج يหมาย ترتيب عناصر مصفوفة منظمة كأزواج من القيم. يتم تطبيق خوارزمية الفرز الفقاعي لترتيب هذه الأزواج حسب القيمة الأولى أو الثانية حسب الحاجة. هذه التقنية مفيدة في معالجة البيانات الثنائية مثل إحداثيات النقاط أو أزواج القيم والمفاتيح.\n\nالكود:\nصحيح[] مصفوفة = [30، 10، 50، 20، 40]\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة) - 1؛ ع = ع + 1) {\n    لكل (صحيح ب = ع + 1؛ ب < طول(مصفوفة)؛ ب = ب + 1) {\n        إذا (مصفوفة[ع] > مصفوفة[ب]) {\n            صحيح مؤقت = مصفوفة[ع]\n            مصفوفة[ع] = مصفوفة[ب]\n            مصفوفة[ب] = مؤقت\n        }\n    }\n}\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}\nالoutput المتوقع: 10\n20\n30\n40\n50', starterCode:'صحيح[] مصفوفة = [30، 10، 50، 20، 40]\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة) - 1؛ ع = ع + 1) {\n    لكل (صحيح ب = ع + 1؛ ب < طول(مصفوفة)؛ ب = ب + 1) {\n        إذا (مصفوفة[ع] > مصفوفة[ب]) {\n            صحيح مؤقت = مصفوفة[ع]\n            مصفوفة[ع] = مصفوفة[ب]\n            مصفوفة[ب] = مؤقت\n        }\n    }\n}\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}', expectedOutput:'10\n20\n30\n40\n50', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:28, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'ترتيب الأزواج: تمارين 1', description:'افرز مصفوفة [45، 12، 78، 34، 90] تصاعدياً واطبع النتيجة.', starterCode:'', expectedOutput:'12\n34\n45\n78\n90', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:29, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'ترتيب الأزواج: تمارين 2', description:'افرز مصفوفة [100، 50، 25، 75] تنازلياً واطبع النتيجة.', starterCode:'', expectedOutput:'100\n75\n50\n25', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:30, xpReward:70, points:70, difficulty:'EXPERT', dynamicOutput:'' },
];
