module.exports = [
  // ═══════════════════════════════════════════════════════════════
  // TIER 1: أساسيات البرمجة (30 challenges = 10 lessons × 3 exercises)
  // ═══════════════════════════════════════════════════════════════

  // ── الدرس 1: طباعة أول برنامج ──
  { title:'طباعة: المثال', description:'(درس) أوّل أمر تتعلّمه في أي لغة برمجة هو طباعة شيء على الشاشة!\nفي ض، استخدم دالة طباعة() مع نص محاط بعلامات اقتباس مزدوجة لعرض أي رسالة تريدها.\nهذا الأمر يطبع النص كما هو داخل الشاشة (المخرجات).\nالكود:\nطباعة("مرحباً بالعالم")\nتطبع: مرحباً بالعالم', starterCode:'طباعة("مرحباً بالعالم")', expectedOutput:'مرحباً بالعالم', requirements:'[{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:1, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'طباعة: تمارين 1', description:'اكتب برنامجاً يطبع تحية "أهلاً يا عالم".', starterCode:'', expectedOutput:'أهلاً يا عالم', requirements:'[{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:2, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'طباعة: تمارين 2', description:'اكتب برنامجاً يطبع كلمة "برمجة".', starterCode:'', expectedOutput:'برمجة', requirements:'[{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:3, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },

  // ── الدرس 2: طباعة أرقام ──
  { title:'طباعة أرقام: المثال', description:'(درس) يمكنك طباعة الأرقام مباشرة بدون علامات اقتباس!\nإذا أردت طباعة رقم (وليس نصاً)، اكتب الرقم مباشرة داخل طباعة() بدون علامات اقتباس.\nالفرق بين النص والرقم: النص محاط بعلامات اقتباس، أما الرقم فيُكتب كما هو.\nالكود:\nطباعة(42)\nتطبع: 42', starterCode:'طباعة(42)', expectedOutput:'42', requirements:'[{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:4, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'طباعة أرقام: تمارين 1', description:'اكتب برنامجاً يطبع الرقم 100.', starterCode:'', expectedOutput:'100', requirements:'[{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:5, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'طباعة أرقام: تمارين 2', description:'اكتب برنامجاً يطبع الرقم 0.', starterCode:'', expectedOutput:'0', requirements:'[{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:6, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },

  // ── الدرس 3: تعريف المتغيرات الصحيحة ──
  { title:'متغير صحيح: المثال', description:'(درس) المتغير كوة في الذاكرة لتخزين قيمة! نوع صحيح يخزن أرقاماً صحيحة فقط.\nاستخدم كلمة صحيح متبوعة باسم المتغير وعلامة = ثم القيمة.\nالصحيح هو لل أرقام كاملة بدون كسور (مثل: 10، 25، -3).\nالكود:\nصحيح عمر = 20\nطباعة(عمر)\ntprint: 20', starterCode:'صحيح عمر = 20\nطباعة(عمر)', expectedOutput:'20', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:7, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'متغير صحيح: تمارين 1', description:'عرّف متغيراً صحيحاً اسمه العمر وسجّله بقيمة 25، ثم اطبع قيمته.', starterCode:'', expectedOutput:'25', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:8, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'متغير صحيح: تمارين 2', description:'عرّف متغيراً صحيحاً اسمه العدد وسجّله بقيمة 50، ثم اطبع قيمته.', starterCode:'', expectedOutput:'50', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:9, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },

  // ── الدرس 4: المتغيرات العشرية ──
  { title:'متغير عشري: المثال', description:'(درس) نوع عشري يخزن أرقاماً بها كسور عشرية (مثل: 3.5، 0.75، 1.80).\nاستخدم كلمة عشري متبوعة باسم المتغير وعلامة = ثم القيمة العشرية.\nالعشري مفيد للقياسات الدقيقة مثل الأوزان والطويلات والنسب.\nالكود:\nعشري المتوسط = 3.5\nطباعة(المتوسط)\ntprint: 3.5', starterCode:'عشري المتوسط = 3.5\nطباعة(المتوسط)', expectedOutput:'3.5', requirements:'[{"type":"must_use_keyword","keyword":"عشري"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:10, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'متغير عشري: تمارين 1', description:'عرّف متغيراً عشرياً اسمه النسبة وسجّله بقيمة 0.75، ثم اطبع قيمته.', starterCode:'', expectedOutput:'0.75', requirements:'[{"type":"must_use_keyword","keyword":"عشري"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:11, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'متغير عشري: تمارين 2', description:'عرّف متغيراً عشرياً اسمه الطول وسجّله بقيمة 1.80، ثم اطبع قيمته.', starterCode:'', expectedOutput:'1.8', requirements:'[{"type":"must_use_keyword","keyword":"عشري"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:12, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },

  // ── الدرس 5: المتغيرات النصية ──
  { title:'متغير نصي: المثال', description:'(درس) النوع النصي (نص) يخزن النصوص والكلمات المحاطة بعلامات اقتباس مزدوجة.\nاستخدم كلمة نص متبوعة باسم المتغير وعلامة = ثم النص المحاط بعلامات اقتباس.\nالكود:\nنص اسم = "أحمد"\nطباعة(الاسم)\ntprint: أحمد', starterCode:'نص اسم = "أحمد"\nطباعة(الاسم)', expectedOutput:'أحمد', requirements:'[{"type":"must_use_keyword","keyword":"نص"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:13, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'متغير نصي: تمارين 1', description:'عرّف متغيراً نصياً اسمه المدينة وسجّله بقيمة "الرياض"، ثم اطبع قيمته.', starterCode:'', expectedOutput:'الرياض', requirements:'[{"type":"must_use_keyword","keyword":"نص"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:14, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'متغير نصي: تمارين 2', description:'عرّف متغيراً نصياً اسمه البلد وسجّله بقيمة "السعودية"، ثم اطبع قيمته.', starterCode:'', expectedOutput:'السعودية', requirements:'[{"type":"must_use_keyword","keyword":"نص"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:15, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },

  // ── الدرس 6: المتغيرات المنطقية ──
  { title:'متغير منطقي: المثال', description:'(درس) النوع المنطقي يخزين فقط قيمتين: صواب (صحيح) أو خطأ (خاطئ).\nهذا النوع مفيد للتعبير عن حالة مثل: هل تم الواجب؟ هل المستخدم مسجل الدخول؟\nفي ض، نستخدم كلمة صواب لتعني true وخطأ لتعني false.\nالكود:\nمنطقي مكتمل = صواب\nطباعة(مكتمل)\ntprint: true', starterCode:'منطقي مكتمل = صواب\nطباعة(مكتمل)', expectedOutput:'true', requirements:'[{"type":"must_use_keyword","keyword":"منطقي"},{"type":"must_use_keyword","keyword":"صواب"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:16, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'متغير منطقي: تمارين 1', description:'عرّف متغيراً منطقياً اسمه ناجح وسجّله بقيمة خطأ، ثم اطبع قيمته.', starterCode:'', expectedOutput:'false', requirements:'[{"type":"must_use_keyword","keyword":"منطقي"},{"type":"must_use_keyword","keyword":"خطأ"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:17, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'متغير منطقي: تمارين 2', description:'عرّف متغيراً منطقياً اسمه موجود وسجّله بقيمة صواب، ثم اطبع قيمته.', starterCode:'', expectedOutput:'true', requirements:'[{"type":"must_use_keyword","keyword":"منطقي"},{"type":"must_use_keyword","keyword":"صواب"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:18, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },

  // ── الدرس 7: العمليات الحسابية ──
  { title:'عمليات حسابية: المثال', description:'(درس) لغة ض تدعم جميع العمليات الحسابية الأساسية!\nالجمع (+) والطرح (-) والضرب (*) والقسمة (/) - كلها متاحة.\nيمكنك حفظ النتيجة في متغير ثم طباعتها.\nالكود:\nصحيح نتيجة = 15 + 25\nطباعة(النتيجة)\ntprint: 40', starterCode:'صحيح نتيجة = 15 + 25\nطباعة(النتيجة)', expectedOutput:'40', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:19, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'عمليات حسابية: تمارين 1', description:'احسب الفرق بين 100 و 37 واطبع النتيجة.', starterCode:'', expectedOutput:'63', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:20, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'عمليات حسابية: تمارين 2', description:'احسب حاصل ضرب 7 في 8 واطبع النتيجة.', starterCode:'', expectedOutput:'56', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:21, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },

  // ── الدرس 8: قسمة والباقي ──
  { title:'قسمة والباقي: المثال', description:'(درس) operator / يعطيك حاصل القسمة، و operator % يعطيك الباقي!\nمثال: 144 ÷ 12 = 12 بدون باقي. و 17 ÷ 5 = 3 مع باقي 2.\nالباقي مفيد لمعرفة إذا كان العدد ينقسم بالكامل أم لا.\nالكود:\nصحيح نتيجة = 144 / 12\nطباعة(النتيجة)\ntprint: 12', starterCode:'صحيح نتيجة = 144 / 12\nطباعة(النتيجة)', expectedOutput:'12', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:22, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'قسمة والباقي: تمارين 1', description:'احسب باقي قسمة 17 على 5 واطبع النتيجة.', starterCode:'', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:23, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'قسمة والباقي: تمارين 2', description:'احسب حاصل قسمة 200 على 8 واطبع النتيجة.', starterCode:'', expectedOutput:'25', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:24, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },

  // ── الدرس 9: الثوابت ──
  { title:'ثابت: المثال', description:'(درس) الثابت مثل المتغير لكن لا يمكن تغيير قيمته لاحقاً!\nاستخدم كلمة ثابت بدلاً من نوع البيانات لتعريف قيمة ثابتة لا تتغير.\nالثوابت مفيدة للقيم المعروفة مسبقاً مثل نسبة الضرية أو سرعة الضوء.\nالكود:\nثابت النسبة = 0.5\nطباعة(النسبة)\ntprint: 0.5', starterCode:'ثابت النسبة = 0.5\nطباعة(النسبة)', expectedOutput:'0.5', requirements:'[{"type":"must_use_keyword","keyword":"ثابت"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:25, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'ثابت: تمارين 1', description:'عرّف ثابتاً اسمه الطول وسجّله بقيمة 10، ثم اطبع قيمته.', starterCode:'', expectedOutput:'10', requirements:'[{"type":"must_use_keyword","keyword":"ثابت"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:26, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'ثابت: تمارين 2', description:'عرّف ثابتاً اسمه العرض وسجّله بقيمة 5، ثم اطبع قيمته.', starterCode:'', expectedOutput:'5', requirements:'[{"type":"must_use_keyword","keyword":"ثابت"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:27, xpReward:10, points:15, difficulty:'BEGINNER', dynamicOutput:'' },

  // ── الدرس 10: القيمة عدم ──
  { title:'قيمة عدم: المثال', description:'(درس) القيمة عدم تعني أن المتغير فارغ ولا يحتوي على أي قيمة!\nفي البرمجة، أحياناً لا توجد قيمة مناسبة لتخزينها - هنا يأتي دور عدم.\nيمكنك تخزين عدم في أي نوع بيانات (صحيح، عشري، نص).\nالكود:\nطباعة(عدم)\ntprint: null', starterCode:'طباعة(عدم)', expectedOutput:'null', requirements:'[{"type":"must_use_keyword","keyword":"طباعة"},{"type":"must_use_keyword","keyword":"عدم"}]', tier:1, order:28, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'قيمة عدم: تمارين 1', description:'عرّف متغيراً نصياً اسمه الاسم بقيمة عدم ثم اطبع قيمته.', starterCode:'', expectedOutput:'null', requirements:'[{"type":"must_use_keyword","keyword":"نص"},{"type":"must_use_keyword","keyword":"عدم"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:29, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
  { title:'قيمة عدم: تمارين 2', description:'عرّف متغيراً صحيحاً اسمه العدد بقيمة عدم ثم اطبع قيمته.', starterCode:'', expectedOutput:'null', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"عدم"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:30, xpReward:10, points:10, difficulty:'BEGINNER', dynamicOutput:'' },
];
