module.exports = [
  // ═══════════════════════════════════════════════════════════════
  // TIER 6: المصفوفات (30 challenges = 10 lessons × 3 exercises)
  // ═══════════════════════════════════════════════════════════════

  // ── الدرس 1: إنشاء مصفوفة ──
  { title:'إنشاء مصفوفة: المثال', description:'(درس) المصفوفة هي مجموعة منظمة من العناصر تحمل نفس النوع وتخزن في متغير واحد. لإنشاء مصفوفة، نستخدم الأقواس المربعة [ ] ونفصل بين العناصر بفاصلة. هذا يجعل من السهل إدارة مجموعات من البيانات في مكان واحد.\nالكود:\nصحيح[] مصفوفة = [10، 20، 30]\nطباعة(مصفوفة)\nالنتيجة المتوقعة: 10,20,30', starterCode:'صحيح[] مصفوفة = [10، 20، 30]\nطباعة(مصفوفة)', expectedOutput:'10,20,30', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:1, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'إنشاء مصفوفة: تمارين 1', description:'أنشئ مصفوفة [5، 15، 25، 35، 45] واطبعها.', starterCode:'', expectedOutput:'5,15,25,35,45', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:2, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'إنشاء مصفوفة: تمارين 2', description:'أنشئ مصفوفة نصوص ["تفاح"، "موز"، "عنب"] واطبعها.', starterCode:'', expectedOutput:'تفاح,موز,عنب', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:3, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 2: الوصول للعناصر ──
  { title:'الوصول للعناصر: المثال', description:'(درس) كل عنصر في المصفوفة له فهرس رقمي يبدأ من الصفر. نستخدم الأقواس المربعة مع رقم الفهرس للوصول لأي عنصر في المصفوفة. مثلاً، الفهرس 0 يمثل العنصر الأول، والفهرس 1 يمثل العنصر الثاني، وهكذا.\nالكود:\nصحيح[] مصفوفة = [10، 20، 30]\nطباعة(مصفوفة[0])\nالنتيجة المتوقعة: 10', starterCode:'صحيح[] مصفوفة = [10، 20، 30]\nطباعة(مصفوفة[0])', expectedOutput:'10', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:4, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'الوصول للعناصر: تمارين 1', description:'أنشئ مصفوفة [5، 10، 15] واطبع العنصر الثاني (الفهرس 1).', starterCode:'', expectedOutput:'10', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:5, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'الوصول للعناصر: تمارين 2', description:'أنشئ مصفوفة [100، 200، 300] واطبع العنصر الأخير (الفهرس 2).', starterCode:'', expectedOutput:'300', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:6, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 3: طول المصفوفة ──
  { title:'طول المصفوفة: المثال', description:'(درس) دالة طول() تُرجع عدد العناصر الموجودة في المصفوفة. هذه الدالة مفيدة جداً عند استخدام الحلقات للمرور على جميع العناصر، لأنها تحدد نقطة نهاية الحلقة. مثلاً، إذا كانت المصفوفة تحتوي 3 عناصر، فإن طول() تُرجع الرقم 3.\nالكود:\nصحيح[] مصفوفة = [10، 20، 30]\nطباعة(طول(مصفوفة))\nالنتيجة المتوقعة: 3', starterCode:'صحيح[] مصفوفة = [10، 20، 30]\nطباعة(طول(مصفوفة))', expectedOutput:'3', requirements:'[{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:7, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'طول المصفوفة: تمارين 1', description:'أنشئ مصفوفة [1، 2، 3، 4، 5] واطبع طولها.', starterCode:'', expectedOutput:'5', requirements:'[{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:8, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'طول المصفوفة: تمارين 2', description:'أنشئ مصفوفة ["أ"، "ب"] واطبع طولها.', starterCode:'', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:9, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 4: تعديل العناصر ──
  { title:'تعديل العناصر: المثال', description:'(درس) يمكننا تغيير قيمة أي عنصر في المصفوفة عن طريق تحديد فهرسه واستخدام عامل الإسناد (=). هذه العملية تسمى التعديل، وهي مفيدة لتحديث البيانات بدون إنشاء مصفوفة جديدة. مثلاً، لمتابعة نتائج طالب أو تعديل أسعار منتج.\nالكود:\nصحيح[] مصفوفة = [10، 20، 30]\nمصفوفة[1] = 25\nطباعة(مصفوفة[1])\nالنتيجة المتوقعة: 25', starterCode:'صحيح[] مصفوفة = [10، 20، 30]\nمصفوفة[1] = 25\nطباعة(مصفوفة[1])', expectedOutput:'25', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:10, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'تعديل العناصر: تمارين 1', description:'أنشئ مصفوفة [10، 20، 30] ثم غيّر العنصر الأول إلى 15 واطبعه.', starterCode:'', expectedOutput:'15', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:11, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'تعديل العناصر: تمارين 2', description:'أنشئ مصفوفة ["أ"، "ب"، "ج"] ثم غيّر العنصر الأخير إلى "ز" واطبعه.', starterCode:'', expectedOutput:'ز', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:12, xpReward:15, points:15, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 5: إضافة عنصر ──
  { title:'إضافة عنصر: المثال', description:'(درس) لإضافة عنصر جديد في نهاية المصفوفة، نستخدم فهرساً يساوي طول المصفوفة الحالي. لأن الفهارس تبدأ من الصفر، فإن طول() يمثل أول فهرس متاح بعد العنصر الأخير. هذه الطريقة تسمح بتوسيع المصفوفة ديناميكياً لإضافة بيانات جديدة.\nالكود:\nصحيح[] مصفوفة = [1، 2، 3]\nمصفوفة[طول(مصفوفة)] = 4\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}\nالنتيجة المتوقعة:\n1\n2\n3\n4', starterCode:'صحيح[] مصفوفة = [1، 2، 3]\nمصفوفة[طول(مصفوفة)] = 4\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}', expectedOutput:'1\n2\n3\n4', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:13, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'إضافة عنصر: تمارين 1', description:'أنشئ مصفوفة [10، 20] وأضف العنصر 30 في النهاية ثم اطبع المصفوفة.', starterCode:'', expectedOutput:'10\n20\n30', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:14, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'إضافة عنصر: تمارين 2', description:'أنشئ مصفوفة فارغة وأضف 3 عناصر (5، 10، 15) ثم اطبع المصفوفة.', starterCode:'', expectedOutput:'5\n10\n15', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:15, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 6: حذف عنصر ──
  { title:'حذف عنصر: المثال', description:'(درس) لحذف عنصر من المصفوفة، نحتاج لتحريك جميع العناصر التي تليه خطوة إلى اليسار لملء الفراغ. نبدأ من العنصر المراد حذفه وننسخ كل عنصر في الموقع الذي يسبقه. بهذه الطريقة، يُمحو العنصر المستهدف ويصبح المصفوفة أصغر بعنصر واحد.\nالكود:\nصحيح[] مصفوفة = [1، 2، 3، 4، 5]\nمصفوفة[2] = مصفوفة[3]\nمصفوفة[3] = مصفوفة[4]\nلكل (صحيح ع = 0؛ ع < 4؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}\nالنتيجة المتوقعة:\n1\n2\n4\n5', starterCode:'صحيح[] مصفوفة = [1، 2، 3، 4، 5]\nمصفوفة[2] = مصفوفة[3]\nمصفوفة[3] = مصفوفة[4]\nلكل (صحيح ع = 0؛ ع < 4؛ ع = ع + 1) {\n    طباعة(مصفوفة[ع])\n}', expectedOutput:'1\n2\n4\n5', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:16, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'حذف عنصر: تمارين 1', description:'أنشئ مصفوفة [10، 20، 30، 40] واحذف العنصر الأوسط ثم اطبع النتيجة.', starterCode:'', expectedOutput:'10\n20\n40', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:17, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'حذف عنصر: تمارين 2', description:'أنشئ مصفوفة ["أ"، "ب"، "ج"] واحذف العنصر الأخير ثم اطبع النتيجة.', starterCode:'', expectedOutput:'أ\nب', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:18, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 7: البحث في المصفوفة ──
  { title:'البحث في المصفوفة: المثال', description:'(درس) البحث في المصفوفة يعني المرور على جميع عناصرها والتحقق مما إذا كان عنصر معين موجوداً. نستخدم حلقة for للمرور على كل عنصر، ونقارنه مع القيمة المطلوبة باستخدام شرط if. إذا وجدناه، نحفظ فهرسه؛ وإلا نُرجع -1 للدلالة على عدم الوجود.\nالكود:\nصحيح[] مصفوفة = [5، 10، 15، 20]\nصحيح الهدف = 15\nصحيح فهرس = -1\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    إذا (مصفوفة[ع] == الهدف) {\n        فهرس = ع\n    }\n}\nطباعة(فهرس)\nالنتيجة المتوقعة: 2', starterCode:'صحيح[] مصفوفة = [5، 10، 15، 20]\nصحيح الهدف = 15\nصحيح فهرس = -1\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    إذا (مصفوفة[ع] == الهدف) {\n        فهرس = ع\n    }\n}\nطباعة(فهرس)', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:19, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'البحث في المصفوفة: تمارين 1', description:'ابحث عن الرقم 7 في مصفوفة [1، 3، 5، 7، 9] واطبع فهرسه.', starterCode:'', expectedOutput:'3', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:20, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'البحث في المصفوفة: تمارين 2', description:'ابحث عن النص "موز" في مصفوفة ["تفاح"، "موز"، "عنب"] واطبع فهرسه.', starterCode:'', expectedOutput:'1', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:21, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 8: مصفوفة ثنائية ──
  { title:'مصفوفة ثنائية: المثال', description:'(درس) المصفوفة الثنائية هي مصفوفة تحتوي مصفوفات أخرى كعناصر، مما يُنشئ جدولاً ذا صفوف وأعمدة. للوصول لعنصر معين، نستخدم فهرسين: الفهرس الأول لتحديد الصف، والثاني لتحديد العمود. هذه المصفوفات مفيدة لتمثيل البيانات المنظمة مثل جداول الدرجات أو خرائط الموقع.\nالكود:\nصحيح[] صف1 = [1، 2]\nصحيح[] صف2 = [3، 4]\nصحيح[] مصفوفة = [صف1، صف2]\nطباعة(مصفوفة[0][0])\nالنتيجة المتوقعة: 1', starterCode:'صحيح[] صف1 = [1، 2]\nصحيح[] صف2 = [3، 4]\nصحيح[] مصفوفة = [صف1، صف2]\nطباعة(مصفوفة[0][0])', expectedOutput:'1', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:22, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'مصفوفة ثنائية: تمارين 1', description:'أنشئ مصفوفة ثنائية [[10، 20]، [30، 40]] واطبع العنصر في الصف الثاني العمود الثاني.', starterCode:'', expectedOutput:'40', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:23, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'مصفوفة ثنائية: تمارين 2', description:'أنشئ مصفوفة ثنائية [["أ"، "ب"]، ["ج"، "د"]] واطبع العنصر في الصف الأول العمود الثاني.', starterCode:'', expectedOutput:'ب', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:24, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 9: عد العناصر ──
  { title:'عد العناصر: المثال', description:'(درس) عد العناصر يعني حساب عدد مرات تكرار عنصر معين داخل المصفوفة. نُنشئ متغير عداد يبدأ من الصفر، ثم نمر على جميع العناصر بحلقة for ونقارن كل عنصر مع القيمة المطلوبة. كل مرة نجد تطابقاً، نزيد العداد بمقدار واحد.\nالكود:\nصحيح[] مصفوفة = [1، 2، 2، 3، 2]\nصحيح العدد = 0\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    إذا (مصفوفة[ع] == 2) {\n        العدد = العدد + 1\n    }\n}\nطباعة(العدد)\nالنتيجة المتوقعة: 3', starterCode:'صحيح[] مصفوفة = [1، 2، 2، 3، 2]\nصحيح العدد = 0\nلكل (صحيح ع = 0؛ ع < طول(مصفوفة)؛ ع = ع + 1) {\n    إذا (مصفوفة[ع] == 2) {\n        العدد = العدد + 1\n    }\n}\nطباعة(العدد)', expectedOutput:'3', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:25, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'عد العناصر: تمارين 1', description:'عد تكرار الرقم 5 في مصفوفة [5، 1، 5، 3، 5] واطبع العدد.', starterCode:'', expectedOutput:'3', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:26, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'عد العناصر: تمارين 2', description:'عد تكرار النص "أحمد" في مصفوفة ["أحمد"، "علي"، "أحمد"، "محمد"] واطبع العدد.', starterCode:'', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:27, xpReward:15, points:20, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 10: دمج مصفوفتين ──
  { title:'دمج مصفوفتين: المثال', description:'(درس) دمج مصفوفتين يعني الجمع بين عناصريهما في مصفوفة واحدة جديدة. نُنشئ مصفوفة فارغة، ثم نمر على عناصر المصفوفة الأولى ونضيفها واحداً تلو الآخر، ثم نفعل الشيء نفسه مع المصفوفة الثانية. هذه التقنية مفيدة عند دمج قوائم بيانات أو إضافة عناصر من مصادر مختلفة.\nالكود:\nصحيح[] م1 = [1، 2، 3]\nصحيح[] م2 = [4، 5، 6]\nصحيح[] الدمج = []\nلكل (صحيح ع = 0؛ ع < طول(م1)؛ ع = ع + 1) {\n    الدمج[طول(الدمج)] = م1[ع]\n}\nلكل (صحيح ع = 0؛ ع < طول(م2)؛ ع = ع + 1) {\n    الدمج[طول(الدمج)] = م2[ع]\n}\nلكل (صحيح ع = 0؛ ع < طول(الدمج)؛ ع = ع + 1) {\n    طباعة(الدمج[ع])\n}\nالنتيجة المتوقعة:\n1\n2\n3\n4\n5\n6', starterCode:'صحيح[] م1 = [1، 2، 3]\nصحيح[] م2 = [4، 5، 6]\nصحيح[] الدمج = []\nلكل (صحيح ع = 0؛ ع < طول(م1)؛ ع = ع + 1) {\n    الدمج[طول(الدمج)] = م1[ع]\n}\nلكل (صحيح ع = 0؛ ع < طول(م2)؛ ع = ع + 1) {\n    الدمج[طول(الدمج)] = م2[ع]\n}\nلكل (صحيح ع = 0؛ ع < طول(الدمج)؛ ع = ع + 1) {\n    طباعة(الدمج[ع])\n}', expectedOutput:'1\n2\n3\n4\n5\n6', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:28, xpReward:15, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'دمج مصفوفتين: تمارين 1', description:'ادمج مصفوفتي [10، 20] و [30، 40] واطبع النتيجة.', starterCode:'', expectedOutput:'10\n20\n30\n40', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:29, xpReward:15, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'دمج مصفوفتين: تمارين 2', description:'ادمج مصفوفتي ["أ"، "ب"] و ["ج"، "د"] واطبع النتيجة.', starterCode:'', expectedOutput:'أ\nب\nج\nد', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:30, xpReward:15, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
];
