module.exports = [
  // ═══════════════════════════════════════════════════════════════
  // TIER 7: البرمجة الكائنية المتقدمة (30 challenges = 10 lessons × 3 exercises)
  // ═══════════════════════════════════════════════════════════════

  // ── الدرس 1: الوراثة ──
  { title:'الوراثة: المثال', description:'(درس) الوراثة هي آلية تسمح بإنشاء صنف جديد من صنف موجود، حيث يرث الصنف الجديد جميع خصائص ووظائف الصنف الأصل ويمكنه تعديلها أو إضافة ميزات جديدة. الوراثة تُقلل من تكرار الكود وتجعل البرمجة أكثر تنظيماً وقابلية للصيانة.\nالكود:\nصنف حيوان {\n    دالة جديد(الاسم) {\n        هذا.الاسم = الاسم\n    }\n    دالة صوت() {\n        ارجع "صوت مجهول"\n    }\n}\nصنف قط يرث حيوان {\n    دالة جديد() {\n        هذا.الاسم = "قط"\n    }\n    دالة صوت() {\n        ارجع "мяو"\n    }\n}\nصحيح ق = جديد()\nطباعة(ق.صوت())\nالنتيجة المتوقعة: мяو', starterCode:'صنف حيوان {\n    دالة جديد(الاسم) {\n        هذا.الاسم = الاسم\n    }\n    دالة صوت() {\n        ارجع "صوت مجهول"\n    }\n}\nصنف قط يرث حيوان {\n    دالة جديد() {\n        هذا.الاسم = "قط"\n    }\n    دالة صوت() {\n        ارجع "мяو"\n    }\n}\nصحيح ق = جديد()\nطباعة(ق.صوت())', expectedOutput:'мяو', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:1, xpReward:80, points:80, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'الوراثة: تمارين 1', description:'اكتب صنف حيوان بصوت "صوت مجهول"، وصنف كلب يرث حيوان بصوت "هم هم". أنشئ كلباً واطبع صوته.', starterCode:'', expectedOutput:'هم هم', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:2, xpReward:80, points:80, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'الوراثة: تمارين 2', description:'اكتب صنف شكل بصوت "شكل"، وصنف دائرة يرث شكل بصوت "دائرة". أنشئ دائرة واطبع صوتها.', starterCode:'', expectedOutput:'دائرة', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:3, xpReward:80, points:80, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 2: الأصل ──
  { title:'الأصل: المثال', description:'(درس) كلمة الأصل تُستخدم للإشارة إلى الصنف الأب (الصنف الأصل) في عملية الوراثة. عندما تريد الصنف الابن استدعاء دالة أو خاصية من الصنف الأب، تستخدم الأصل لتمكين ذلك. هذا يسمح بإعادة استخدام الكود الموجود في الصنف الأب وإضافة سلوك جديد في الصنف الابن.\nالكود:\nصنف حيوان {\n    دالة جديد(الاسم) {\n        هذا.الاسم = الاسم\n    }\n    دالة اسم() {\n        ارجع هذا.الاسم\n    }\n}\nصنف كلب يرث حيوان {\n    دالة جديد() {\n        هذا.الاسم = "كلب"\n    }\n    دالة وصف() {\n        ارجع "الاسم: " + هذا.اسم()\n    }\n}\nصحيح ك = جديد()\nطباعة(ك.وصف())\nالنتيجة المتوقعة: الاسم: كلب', starterCode:'صنف حيوان {\n    دالة جديد(الاسم) {\n        هذا.الاسم = الاسم\n    }\n    دالة اسم() {\n        ارجع هذا.الاسم\n    }\n}\nصنف كلب يرث حيوان {\n    دالة جديد() {\n        هذا.الاسم = "كلب"\n    }\n    دالة وصف() {\n        ارجع "الاسم: " + هذا.اسم()\n    }\n}\nصحيح ك = جديد()\nطباعة(ك.وصف())', expectedOutput:'الاسم: كلب', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:4, xpReward:80, points:80, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'الأصل: تمارين 1', description:'اكتب صنف آلة ب دالة حرك() ترجع "آلة تتحرك"، وصنف سيارة يرث آلة ب دالة حرك() ترجع "سيارة تتحرك". أنشئ سيارة واطبع حركتها.', starterCode:'', expectedOutput:'سيارة تتحرك', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:5, xpReward:80, points:80, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'الأصل: تمارين 2', description:'اكتب صنف شكل ب دالة وصف() ترجع "شكل"، وصنف مربع يرث شكل ب دالة وصف() ترجع "مربع". أنشئ مربعاً واطبع وصفه.', starterCode:'', expectedOutput:'مربع', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:6, xpReward:80, points:80, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 3: الخاص والعام والمحمي ──
  { title:'الوصول: المثال', description:'(درس) آليات الوصول في البرمجة الكائنية تتحكم في من يمكنه قراءة أو تعديل خصائص الصنف. الخاص يسمح بالوصول فقط من داخل الصنف نفسه، بينما العام يسمح بالوصول من أي مكان. استخدام آليات الوصول الصحيحة يُعزز الأمان ويمنع الوصول غير المصرح به للبيانات الحساسة.\nالكود:\nصنف حساب {\n    خاص صحيح الرصيد\n    دالة جديد(الرصيد) {\n        هذا.الرصيد = الرصيد\n    }\n    عام دالة اعرض() {\n        طباعة(هذا.الرصيد)\n    }\n}\nصحيح ح = جديد(1000)\nح.اعرض()\nالنتيجة المتوقعة: 1000', starterCode:'صنف حساب {\n    خاص صحيح الرصيد\n    دالة جديد(الرصيد) {\n        هذا.الرصيد = الرصيد\n    }\n    عام دالة اعرض() {\n        طباعة(هذا.الرصيد)\n    }\n}\nصحيح ح = جديد(1000)\nح.اعرض()', expectedOutput:'1000', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"خاص"},{"type":"must_use_keyword","keyword":"عام"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:7, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'الوصول: تمارين 1', description:'اكتب صنف طالب بخاص الدرجة، وعام درجة() ترجع الدرجة. أنشئ طالباً بدرجة 95 واطبع درجته.', starterCode:'', expectedOutput:'95', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"خاص"},{"type":"must_use_keyword","keyword":"عام"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:8, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'الوصول: تمارين 2', description:'اكتب صنف محفظة بخاصة المبلغ، وعام أضف() واطبع الرصيد. أنشئ محفظة بـ 100 وأضف 50 ثم اطبع الرصيد.', starterCode:'', expectedOutput:'150', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"خاص"},{"type":"must_use_keyword","keyword":"عام"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:9, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 4: المحمي ──
  { title:'المحمي: المثال', description:'(درس) المحمي هو مستوى وصول يسمح بالوصول إلى خصائص الصنف من داخل الصنف نفسه ومن الأصناف الابنة فقط، بينما يمنع الوصول من خارج هرم الوراثة. هذا يختلف عن الخاص الذي يسمح بالوصول من داخل الصنف فقط، والعام الذي يسمح بالوصول من أي مكان. المحمي يوفر توازناً بين الحماية والمرونة في التوسع.\nالكود:\nصنف حيوان {\n    محمي نص الاسم\n    دالة جديد(الاسم) {\n        هذا.الاسم = الاسم\n    }\n    عام دالة اعرض() {\n        طباعة(هذا.الاسم)\n    }\n}\nصنف كلب يرث حيوان {\n    دالة جديد() {\n        هذا.الاسم = "كلب"\n    }\n}\nصحيح ك = جديد()\nك.اعرض()\nالنتيجة المتوقعة: كلب', starterCode:'صنف حيوان {\n    محمي نص الاسم\n    دالة جديد(الاسم) {\n        هذا.الاسم = الاسم\n    }\n    عام دالة اعرض() {\n        طباعة(هذا.الاسم)\n    }\n}\nصنف كلب يرث حيوان {\n    دالة جديد() {\n        هذا.الاسم = "كلب"\n    }\n}\nصحيح ك = جديد()\nك.اعرض()', expectedOutput:'كلب', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"محمي"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"عام"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:10, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'المحمي: تمارين 1', description:'اكتب صنف قاعدة بيانات بمحمي كلمة_المرور، وعام تحقق() تطبع "صالح". أنشئ قاعدة وتحقق منها.', starterCode:'', expectedOutput:'صالح', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"محمي"},{"type":"must_use_keyword","keyword":"عام"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:11, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'المحمي: تمارين 2', description:'اكتب صنف مستخدم بخاصة المعرف، وعام معلومات() تطبع المعرف. أنشئ مستخدماً بمعرف "admin" واطبع معلوماته.', starterCode:'', expectedOutput:'admin', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"خاص"},{"type":"must_use_keyword","keyword":"عام"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:12, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 5: الصنف المجرّد ──
  { title:'الصنف المجرّد: المثال', description:'(درس) الصنف المجرّد هو صنف لا يمكن إنشاء نسخ منه مباشرة، بل يُستخدم كقالب للصنف الابن. يحتوي على دوال مجرّدة لا تنفذ، ويجب على الصنف الابن تنفيذها جميعاً. الصنف المجرّد مفيد لتعريف عقد مشتركة بين أصناف متعددة وتطبيق مفهوم التعددية الشكلية في البرمجة الكائنية.\nالكود:\nمجرّد صنف شكل {\n    عام دالة مساحة()\n    عام دالة وصف() {\n        ارجع "شكل"\n    }\n}\nصنف مربع يرث شكل {\n    دالة جديد(الطول) {\n        هذا.الطول = الطول\n    }\n    عام دالة مساحة() {\n        ارجع هذا.الطول * هذا.الطول\n    }\n}\nصحيح م = جديد(5)\nطباعة(م.مساحة())\nالنتيجة المتوقعة: 25', starterCode:'مجرّد صنف شكل {\n    عام دالة مساحة()\n    عام دالة وصف() {\n        ارجع "شكل"\n    }\n}\nصنف مربع يرث شكل {\n    دالة جديد(الطول) {\n        هذا.الطول = الطول\n    }\n    عام دالة مساحة() {\n        ارجع هذا.الطول * هذا.الطول\n    }\n}\nصحيح م = جديد(5)\nطباعة(م.مساحة())', expectedOutput:'25', requirements:'[{"type":"must_use_keyword","keyword":"مجرّد"},{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"عام"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:13, xpReward:80, points:90, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'الصنف المجرّد: تمارين 1', description:'اكتب صنف مجرّد حيوان ب دالة صوت() مجرّد، وصنف قط يرث حيوان ب دالة صوت() ترجع "мяو". أنشئ قطاً واطبع صوته.', starterCode:'', expectedOutput:'мяو', requirements:'[{"type":"must_use_keyword","keyword":"مجرّد"},{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"عام"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:14, xpReward:80, points:90, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'الصنف المجرّد: تمارين 2', description:'اكتب صنف مجرّد آلة ب دالة حرك() مجرّد، وصنف طائرة يرث آلة ب دالة حرك() ترجع "طائرة تحلق". أنشئ طائرة واطبع حركتها.', starterCode:'', expectedOutput:'طائرة تحلق', requirements:'[{"type":"must_use_keyword","keyword":"مجرّد"},{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"عام"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:15, xpReward:80, points:90, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 6: الواجهة ──
  { title:'الواجهة: المثال', description:'(درس) الواجهة هي عقد يحدد مجموعة من الدوال التي يجب على أي صنف يرثها تنفيذها جميعاً. الواجهة لا تحتوي على تنفيذ للدوال، بل تُعرّف فقط التوقيع الخارجي للصنف. هذا يسمح بالتعامل مع أصناف مختلفة بشكل موحد إذا كانت تُطبق نفس الواجهة، مما يُعزز المرونة وسهولة الصيانة في البرمجة.\nالكود:\nواجهة قابل_للهجاء {\n    دالة هجاء()\n}\nصنف كتاب يرث قابل_للهجاء {\n    دالة جديد(العنوان) {\n        هذا.العنوان = العنوان\n    }\n    دالة هجاء() {\n        ارجع "كتاب: " + هذا.العنوان\n    }\n}\nصحيح ك = جديد("العلم")\nطباعة(ك.هجاء())\nالنتيجة المتوقعة: كتاب: العلم', starterCode:'واجهة قابل_للهجاء {\n    دالة هجاء()\n}\nصنف كتاب يرث قابل_للهجاء {\n    دالة جديد(العنوان) {\n        هذا.العنوان = العنوان\n    }\n    دالة هجاء() {\n        ارجع "كتاب: " + هذا.العنوان\n    }\n}\nصحيح ك = جديد("العلم")\nطباعة(ك.هجاء())', expectedOutput:'كتاب: العلم', requirements:'[{"type":"must_use_keyword","keyword":"واجهة"},{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:16, xpReward:80, points:90, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'الواجهة: تمارين 1', description:'اكتب واجهة قابل_للطباعة ب دالة طباعة_صفحة(). وصنف مقال يرثها ب دالة طباعة_صفحة() ترجع "طباعة مقال". أنشئ مقالاً واطبع صفحته.', starterCode:'', expectedOutput:'طباعة مقال', requirements:'[{"type":"must_use_keyword","keyword":"واجهة"},{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:17, xpReward:80, points:90, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'الواجهة: تمارين 2', description:'اكتب واجهة قابل_للحذف ب دالة حذف(). وصنف ملف يرثها ب دالة حذف() ترجع "تم الحذف". أنشئ ملفاً واحذفه.', starterCode:'', expectedOutput:'تم الحذف', requirements:'[{"type":"must_use_keyword","keyword":"واجهة"},{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"يرث"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:18, xpReward:80, points:90, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 7: النطاق ──
  { title:'النطاق: المثال', description:'(درس) النطاق هو بناء تستخدم لتجميع دوال ومتغيرات متعلقة ببعضها في وحدة منطقية واحدة. يُشبه النطاق الفئات لكنه يركّز على تجميع الوظائف بدلاً من تعريف كائنات. استخدام النطاقات يُنظّم الكود ويمنع تعارض أسماء المتغيرات والدوال في مساحات عمل مختلفة.\nالكود:\nنطاق رياضيات {\n    دالة اجمع(أ، ب) {\n        ارجع أ + ب\n    }\n    دالة اطرح(أ، ب) {\n        ارجع أ - ب\n    }\n}\nصحيح نتيجة = رياضيات.اجمع(10، 5)\nطباعة(النتيجة)\nالنتيجة المتوقعة: 15', starterCode:'نطاق رياضيات {\n    دالة اجمع(أ، ب) {\n        ارجع أ + ب\n    }\n    دالة اطرح(أ، ب) {\n        ارجع أ - ب\n    }\n}\nصحيح نتيجة = رياضيات.اجمع(10، 5)\nطباعة(النتيجة)', expectedOutput:'15', requirements:'[{"type":"must_use_keyword","keyword":"نطاق"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:19, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'النطاق: تمارين 1', description:'اكتب نطاق حسابات ب دالة ضرب() ودالة قسمة(). احسب ضرب 6 في 7 واطبع النتيجة.', starterCode:'', expectedOutput:'42', requirements:'[{"type":"must_use_keyword","keyword":"نطاق"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:20, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'النطاق: تمارين 2', description:'اكتب نطاق نصوص ب دالة طول_النص() ودالة عكس(). اطبع طول النص "مرحباً".', starterCode:'', expectedOutput:'6', requirements:'[{"type":"must_use_keyword","keyword":"نطاق"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:21, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 8: التعداد ──
  { title:'التعداد: المثال', description:'(درس) التعداد هو نوع بيانات يُعرّف مجموعة من القيم الثابتة والمحدودة، بحيث يمكن أن يتغير المتغير الذي يحمل التعداد بقيم محددة فقط مسبقاً. التعداد يُحسّن قراءة الكود ويقلل من الأخطاء لأن القيم معروفة مسبقاً وليست نصوصاً عشوائية. مثلاً، بدل من استخدام نص "الأحد"، يمكنك استخدام تعداد يمثل اليوم بشكل واضح وآمن.\nالكود:\nتعداد يوم {\n    السبت\n    الأحد\n    الاثنين\n    الثلاثاء\n}\nصحيح يوم = يوم.الاثنين\nإذا (يوم == يوم.الاثنين) {\n    طباعة("اليوم الاثنين")\n}\nالنتيجة المتوقعة: اليوم الاثنين', starterCode:'تعداد يوم {\n    السبت\n    الأحد\n    الاثنين\n    الثلاثاء\n}\nصحيح يوم = يوم.الاثنين\nإذا (يوم == يوم.الاثنين) {\n    طباعة("اليوم الاثنين")\n}', expectedOutput:'اليوم الاثنين', requirements:'[{"type":"must_use_keyword","keyword":"تعداد"},{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:22, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'التعداد: تمارين 1', description:'اكتب تعداد لون { أحمر، أزرق، أخضر }. عرّف لوناً بقيمة الأزرق واطبع "اللون أزرق" إذا كان أزرق.', starterCode:'', expectedOutput:'اللون أزرق', requirements:'[{"type":"must_use_keyword","keyword":"تعداد"},{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:23, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'التعداد: تمارين 2', description:'اكتب تعداد حجم { صغير، متوسط، كبير }. عرّف حجماً بقيمة كبير واطبع "الحجم كبير" إذا كان كبير.', starterCode:'', expectedOutput:'الحجم كبير', requirements:'[{"type":"must_use_keyword","keyword":"تعداد"},{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:24, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 9: المعالجة من الأخطاء ──
  { title:'معالجة الأخطاء: المثال', description:'(درس) معالجة الأخطاء هي تقنية تسمح بالتعامل مع المواقف الاستثنائية التي قد تحدث أثناء تنفيذ البرنامج دون توقفه. يتم استخدام كلمة "حاول" لاحتواء الكود الذي قد يُسبب خطأ، و"امسك" لالتقاط الخطأ ومعالجته بشكل مناسب. هذه الآلية تجعل البرامج أكثر متانة وقدرة على التعامل مع المواقف غير المتوقعة.\nالكود:\nحاول {\n    صحيح نتيجة = 10 / 0\n    طباعة(النتيجة)\n} أمسك (الخطأ) {\n    طباعة("خطأ في القسمة")\n}\nالنتيجة المتوقعة: خطأ في القسمة', starterCode:'حاول {\n    صحيح نتيجة = 10 / 0\n    طباعة(النتيجة)\n} أمسك (الخطأ) {\n    طباعة("خطأ في القسمة")\n}', expectedOutput:'خطأ في القسمة', requirements:'[{"type":"must_use_keyword","keyword":"حاول"},{"type":"must_use_keyword","keyword":"امسك"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:25, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'معالجة الأخطاء: تمارين 1', description:'اكتب برنامجاً يحاول طباعة متغير غير معرّف، وأمسك الخطأ واطبع "متغير غير موجود".', starterCode:'', expectedOutput:'متغير غير موجود', requirements:'[{"type":"must_use_keyword","keyword":"حاول"},{"type":"must_use_keyword","keyword":"امسك"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:26, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'معالجة الأخطاء: تمارين 2', description:'اكتب برنامجاً يحاول طباعة طول متغير غير نصي، وأمسك الخطأ واطبع "خطأ في النوع".', starterCode:'', expectedOutput:'خطأ في النوع', requirements:'[{"type":"must_use_keyword","keyword":"حاول"},{"type":"must_use_keyword","keyword":"امسك"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:27, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },

  // ── الدرس 10: هيكل ──
  { title:'هيكل: المثال', description:'(درس) الهيكل هو نوع بيانات بسيط يُستخدم لتجميع مجموعة من الخصائص في كيان واحد، بدون الحاجة لتعريف دوال معقدة مثل الفئات. الهياكل مفيدة لتمثيل البيانات البسيطة مثل النقاط أو السجلات، وتوفر وسيلة سريعة لإنشاء كائنات بخصائص مشتركة. الهياكل عادة ما تكون أخف وزناً من الفئات وتُستخدم لتخزين البيانات فقط.\nالكود:\nهيكل نقطة {\n    صحيح س\n    صحيح ص\n}\nصحيح نقطة1 = جديد(5، 10)\nطباعة(نقطة1.س + نقطة1.ص)\nالنتيجة المتوقعة: 15', starterCode:'هيكل نقطة {\n    صحيح س\n    صحيح ص\n}\nصحيح نقطة1 = جديد(5، 10)\nطباعة(نقطة1.س + نقطة1.ص)', expectedOutput:'15', requirements:'[{"type":"must_use_keyword","keyword":"هيكل"},{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:28, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'هيكل: تمارين 1', description:'اكتب هيكل طالب بالاسم والدرجة، وأنشئ طالباً باسم "أحمد" ودرجة 90 واطبع درجته.', starterCode:'', expectedOutput:'90', requirements:'[{"type":"must_use_keyword","keyword":"هيكل"},{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:29, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
  { title:'هيكل: تمارين 2', description:'اكتب هيكل مستطيل بالطول والعرض، وأنشئ مستطيل بطول 6 وعرض 4 واطبع مساحته.', starterCode:'', expectedOutput:'24', requirements:'[{"type":"must_use_keyword","keyword":"هيكل"},{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:30, xpReward:80, points:85, difficulty:'EXPERT', dynamicOutput:'' },
];
