module.exports = [
  // ═══════════════════════════════════════════════════════════════
  // TIER 2: المنطق والتحكم (30 challenges = 10 lessons × 3 exercises)
  // ═══════════════════════════════════════════════════════════════

  // ── الدرس 1: شرط إذا ──
  { title:'شرط إذا: المثال', description:'(درس) الجملة الشرطية إذا تسمح لك بتنفيذ كود فقط عند تحقق شرط معين!\nفي ض، نستخدم إذا متبوعة بشرط بين قوسين، والكود المنفذ بين قوسين معقوفين.\nإذا كان الشرط صواباً (صحيح)، يُنفذ الكود داخل القوسين. وإلا يتم تجاهله.\nالكود:\nصحيح عمر = 20\nإذا (عمر >= 18) {\n    طباعة("بالغ")\n}\ntprint: بالغ', starterCode:'صحيح عمر = 20\nإذا (عمر >= 18) {\n    طباعة("بالغ")\n}', expectedOutput:'بالغ', requirements:'[{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:1, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'شرط إذا: تمارين 1', description:'عرّف متغيراً صحيحاً اسمه الدرجة بقيمة 85. إذا كانت الدرجة أكبر من 80 اطبع "ناجح".', starterCode:'', expectedOutput:'ناجح', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:2, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'شرط إذا: تمارين 2', description:'عرّف متغيراً صحيحاً اسمه العمر بقيمة 12. إذا كان العمر أصغر من 13 اطبع "طفل".', starterCode:'', expectedOutput:'طفل', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:3, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 2: إذا وإلا ──
  { title:'إذا وإلا: المثال', description:'(درس) أضف كلمة وإلا بعد جملة إذا للتعامل مع الحالة العكسية!\nإذا لم يتحقق الشرط، يُنفذ الكود الموجود بعد وإلا.\nهذا يضمن أن أحد الخيارين سيُنفذ دائماً.\nالكود:\nصحيح عمر = 15\nإذا (عمر >= 18) {\n    طباعة("بالغ")\n} وإلا {\n    طباعة("قاصر")\n}\ntprint: قاصر', starterCode:'صحيح عمر = 15\nإذا (عمر >= 18) {\n    طباعة("بالغ")\n} وإلا {\n    طباعة("قاصر")\n}', expectedOutput:'قاصر', requirements:'[{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:4, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'إذا وإلا: تمارين 1', description:'عرّف متغيراً صحيحاً اسمه الدرجة بقيمة 60. إذا كانت الدرجة أكبر من أو تساوي 70 اطبع "ناجح"، وإلا اطبع "راسب".', starterCode:'', expectedOutput:'راسب', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:5, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'إذا وإلا: تمارين 2', description:'عرّف متغيراً صحيحاً اسمه الرقم بقيمة 7. إذا كان الزوجي اطبع "زوجي"، وإلا اطبع "فردي".', starterCode:'', expectedOutput:'فردي', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:6, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 3: شروط متعددة ──
  { title:'شروط متعددة: المثال', description:'(درس) يمكنك إ.chain عدة شروط باستخدام وإلا إذا!\nهذا يسمح لك بالتحقق من عدة حالات بترتيب معين.\nإذا لم يتحقق أي شرط، يُنفذ الكود الأخير بعد وإلا.\nالكود:\nصحيح الدرجة = 85\nإذا (الدرجة >= 90) {\n    طباعة("ممتاز")\n} وإلا إذا (الدرجة >= 80) {\n    طباعة("جيد جداً")\n} وإلا {\n    طباعة("مقبول")\n}\ntprint: جيد جداً', starterCode:'صحيح الدرجة = 85\nإذا (الدرجة >= 90) {\n    طباعة("ممتاز")\n} وإلا إذا (الدرجة >= 80) {\n    طباعة("جيد جداً")\n} وإلا {\n    طباعة("مقبول")\n}', expectedOutput:'جيد جداً', requirements:'[{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:7, xpReward:15, points:20, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'شروط متعددة: تمارين 1', description:'عرّف متغيراً صحيحاً اسمه العمر بقيمة 30. إذا كان العمر أكبر من 60 اطبع "كبير"، وإلا إذا كان أكبر من 30 اطبع "بالغ"، وإلا اطبع "شاب".', starterCode:'', expectedOutput:'شاب', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:8, xpReward:15, points:20, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'شروط متعددة: تمارين 2', description:'عرّف متغيراً صحيحاً اسمه الدرجة بقيمة 95. إذا كانت الدرجة 100 اطبع "كمال"، وإلا إذا كانت >= 90 اطبع "ممتاز"، وإلا إذا كانت >= 80 اطبع "جيد جداً".', starterCode:'', expectedOutput:'ممتاز', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:9, xpReward:15, points:20, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 4: حلقة طالما ──
  { title:'حلقة طالما: المثال', description:'(درس) حلقة طالما تكرر تنفيذ كود طالما الشرط بين القوسين صواب!\nالشرط يُفحص في كل مرة قبل التنفيذ. إذا أصبح خطأ، تتوقف الحلقة.\nتذكّر: عليك زيادة العداد داخل الحلقة لتجنب الحلقة اللانهائية!\nالكود:\nصحيح عداد = 1\nطالما (عداد <= 5) {\n    طباعة(عداد)\n    عداد = عداد + 1\n}\ntprint: 1\\n2\\n3\\n4\\n5', starterCode:'صحيح عداد = 1\nطالما (عداد <= 5) {\n    طباعة(عداد)\n    عداد = عداد + 1\n}', expectedOutput:'1\n2\n3\n4\n5', requirements:'[{"type":"must_use_keyword","keyword":"طالما"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:10, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'حلقة طالما: تمارين 1', description:'اكتب حلقة طالما تطبع الأرقام من 1 إلى 3.', starterCode:'', expectedOutput:'1\n2\n3', requirements:'[{"type":"must_use_keyword","keyword":"طالما"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:11, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'حلقة طالما: تمارين 2', description:'اكتب حلقة طالما تطبع الأرقام من 5 إلى 1 (تصاعدي عكسي).', starterCode:'', expectedOutput:'5\n4\n3\n2\n1', requirements:'[{"type":"must_use_keyword","keyword":"طالما"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:12, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 5: حلقة لكل ──
  { title:'حلقة لكل: المثال', description:'(درس) حلقة لكل تكرر تنفيذ كود لعدد محدد من المرات!\nالبنية: لكل (نوع المتغير = البداية؛ الشرط؛ التكرار) { الكود }\nالعدّاد يبدأ من القيمة الأولية ويُزاد في كل مرة حتى يتحقق الشرط.\nالكود:\nلكل (صحيح ع = 0؛ ع < 4؛ ع = ع + 1) {\n    طباعة(ع)\n}\ntprint: 0\\n1\\n2\\n3', starterCode:'لكل (صحيح ع = 0؛ ع < 4؛ ع = ع + 1) {\n    طباعة(ع)\n}', expectedOutput:'0\n1\n2\n3', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:13, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'حلقة لكل: تمارين 1', description:'اكتب حلقة لكل تطبع الأرقام من 0 إلى 4.', starterCode:'', expectedOutput:'0\n1\n2\n3\n4', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:14, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'حلقة لكل: تمارين 2', description:'اكتب حلقة لكل تطبع الأرقام من 1 إلى 5.', starterCode:'', expectedOutput:'1\n2\n3\n4\n5', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:15, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 6: حلقة كل على مصفوفة ──
  { title:'كل على مصفوفة: المثال', description:'(درس) يمكنك استخدام لكل مع كلمة في ل Iterate على كل عنصر في المصفوفة!\nالصيغة: لكل (نوع المتغير في المصفوفة) { الكود }\nفي كل دورة، يتغير المتغير ليأخذ قيمة العنصر التالي في المصفوفة.\nالكود:\nنص[] الفواكه = ["تفاح"، "موز"، "برتقال"]\nلكل (نص فاكهة في الفواكه) {\n    طباعة(فاكهة)\n}\ntprint: تفاح\\nموز\\nبرتقال', starterCode:'نص[] الفواكه = ["تفاح"، "موز"، "برتقال"]\nلكل (نص فاكهة في الفواكه) {\n    طباعة(فاكهة)\n}', expectedOutput:'تفاح\nموز\nبرتقال', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"في"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:16, xpReward:15, points:20, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'كل على مصفوفة: تمارين 1', description:'لديك مصفوفة نصوص ["أحمد"، "علي"، "محمد"]. اطبع كل اسم في سطر.', starterCode:'', expectedOutput:'أحمد\nعلي\nمحمد', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"في"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:17, xpReward:15, points:20, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'كل على مصفوفة: تمارين 2', description:'لديك مصفوفة أرقام [10، 20، 30]. اطبع كل رقم في سطر.', starterCode:'', expectedOutput:'10\n20\n30', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"في"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:18, xpReward:15, points:20, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 7: مقارنات منطقية ──
  { title:'مقارنات منطقية: المثال', description:'(درس) عوامل المقارنة تُرجع قيمة منطقية (صواب أو خطأ) بناءً على المقارنة!\nالعوامerial: > (أكبر من)، < (أصغر من)، >= (أكبر أو يساوي)، <= (أصغر أو يساوي)، == (يساوي)، != (لا يساوي).\nالنتيجة ستكون دائماً true أو false.\nالكود:\nصحيح نتيجة = 10 > 5\nطباعة(النتيجة)\ntprint: true', starterCode:'صحيح نتيجة = 10 > 5\nطباعة(النتيجة)', expectedOutput:'true', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:19, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'مقارنات منطقية: تمارين 1', description:'تحقق هل 20 يساوي 20 واطبع النتيجة.', starterCode:'', expectedOutput:'true', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:20, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'مقارنات منطقية: تمارين 2', description:'تحقق هل 15 أصغر من 10 واطبع النتيجة.', starterCode:'', expectedOutput:'false', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:21, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 8: المنطق && و || ──
  { title:'المنطق: المثال', description:'(درس) يمكنك دمج شروط متعددة باستخدام عوامل المنطق && (و) و || (أو)!\n&& (و): تُرجع صواب فقط إذا كان الشرطان صحيحين.\n|| (أو): تُرجع صواب إذا كان أحد الشرطين على الأقل صحيحاً.\nالكود:\nصحيح نتيجة = (5 > 3) && (10 > 7)\nطباعة(النتيجة)\ntprint: true', starterCode:'صحيح نتيجة = (5 > 3) && (10 > 7)\nطباعة(النتيجة)', expectedOutput:'true', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:22, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'المنطق: تمارين 1', description:'تحقق هل (10 > 5) أو (3 > 8) واطبع النتيجة.', starterCode:'', expectedOutput:'true', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:23, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'المنطق: تمارين 2', description:'تحقق هل (10 < 5) و (3 > 8) واطبع النتيجة.', starterCode:'', expectedOutput:'false', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:24, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 9: النفي ! ──
  { title:'النفي: المثال', description:'(درس) عامل النفي ! يعكس القيمة المنطقية تماماً!\nإذا كانت القيمة صواب، تصبح خطأ. وإذا كانت خطأ، تصبح صواب.\nمفيد عندما تريد التحقق من عكس شرط معين.\nالكود:\nصحيح قيمة = !(5 > 3)\nطباعة(قيمة)\ntprint: false', starterCode:'صحيح قيمة = !(5 > 3)\nطباعة(قيمة)', expectedOutput:'false', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:25, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'النفي: تمارين 1', description:'تحقق من نفي (10 > 20) واطبع النتيجة.', starterCode:'', expectedOutput:'true', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:26, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'النفي: تمارين 2', description:'تحقق من نفي (5 == 5) واطبع النتيجة.', starterCode:'', expectedOutput:'false', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:27, xpReward:15, points:15, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 10: حلقة افعل ──
  { title:'حلقة افعل: المثال', description:'(درس) حلقة افعلطالما تضمن تنفيذ الكود مرة واحدة على الأقل قبل فحص الشرط!\nالفرق عن طالما: هنا يُنفذ الكود أولاً ثم يُفحص الشرط.\nإذا كان الشرط صواباً، تكرر الحلقة. وإلا تتوقف.\nالكود:\nصحيح عداد = 1\nافعل {\n    طباعة(عداد)\n    عداد = عداد + 1\n}طالما (عداد <= 3)\ntprint: 1\\n2\\n3', starterCode:'صحيح عداد = 1\nافعل {\n    طباعة(عداد)\n    عداد = عداد + 1\n}طالما (عداد <= 3)', expectedOutput:'1\n2\n3', requirements:'[{"type":"must_use_keyword","keyword":"افعل"},{"type":"must_use_keyword","keyword":"طالما"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:28, xpReward:15, points:20, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'حلقة افعل: تمارين 1', description:'اكتب حلقة افعلطالما تطبع الأرقام من 1 إلى 2.', starterCode:'', expectedOutput:'1\n2', requirements:'[{"type":"must_use_keyword","keyword":"افعل"},{"type":"must_use_keyword","keyword":"طالما"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:29, xpReward:15, points:20, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'حلقة افعل: تمارين 2', description:'اكتب حلقة افعلطالما تطبع الأرقام من 0 إلى 3.', starterCode:'', expectedOutput:'0\n1\n2\n3', requirements:'[{"type":"must_use_keyword","keyword":"افعل"},{"type":"must_use_keyword","keyword":"طالما"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:30, xpReward:15, points:20, difficulty:'INTERMEDIATE', dynamicOutput:'' },
];
