module.exports = [
  // ═══════════════════════════════════════════════════════════════
  // TIER 3: هيكل البيانات (30 challenges = 10 lessons × 3 exercises)
  // ═══════════════════════════════════════════════════════════════

  // ── الدرس 1: تعريف دالة بسيطة ──
  { title:'دالة بسيطة: المثال', description:'(درس) الدالة هي كود منظّم يمكنك استخدامه مرة ومرة أخرى!\nلتعريف دالة في ض، استخدم كلمة دالة متبوعة باسم الدالة وأقواس فارغة ()، ثم الكود داخل قوسين معقوفين {}.\nلاستدعاء الدالة، اكتب اسمها متبوعاً بأقواس فارغة.\nالكود:\nدالة احيِ() {\n    طباعة("أهلاً")\n}\nاحيِ()\ntprint: أهلاً', starterCode:'دالة احيِ() {\n    طباعة("أهلاً")\n}\nاحيِ()', expectedOutput:'أهلاً', requirements:'[{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:1, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'دالة بسيطة: تمارين 1', description:'اكتب دالة اسمها رحّب تطبع "يا عالم" ثم استدعِها.', starterCode:'', expectedOutput:'يا عالم', requirements:'[{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:2, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'دالة بسيطة: تمارين 2', description:'اكتب دالة اسمها وداع تطبع "مع السلامة" ثم استدعِها.', starterCode:'', expectedOutput:'مع السلامة', requirements:'[{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:3, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 2: دالة مع معاملات ──
  { title:'دالة مع معاملات: المثال', description:'(درس) يمكنك جعل الدالة تقبل بيانات داخلية (معاملات) لتخصيص سلوكها!\nاكتب المعاملات بين الأقواس بعد اسم الدالة. يمكنك استخدام المعامل داخل الكود.\nهذا يجعل الدالة مرنة وقابلة لإعادة الاستخدام بمختلف القيم.\nالكود:\nدالة احيِ(الاسم) {\n    طباعة("أهلاً " + الاسم)\n}\nاحيِ("محمد")\ntprint: أهلاً محمد', starterCode:'دالة احيِ(الاسم) {\n    طباعة("أهلاً " + الاسم)\n}\nاحيِ("محمد")', expectedOutput:'أهلاً محمد', requirements:'[{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:4, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'دالة مع معاملات: تمارين 1', description:'اكتب دالة تطبع تحية شخص بالاسم. استدعِها بـ "أحمد".', starterCode:'', expectedOutput:'أهلاً أحمد', requirements:'[{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:5, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'دالة مع معاملات: تمارين 2', description:'اكتب دالة تطبع اسم المدينة. استدعِها بـ "جدة".', starterCode:'', expectedOutput:'جدة', requirements:'[{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:6, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 3: دالة بقيمة إرجاع ──
  { title:'دالة إرجاع: المثال', description:'(درس) يمكنك جعل الدالة تُرجع قيمة نهائية باستخدام كلمة ارجع!\nالقيمة المُعادة يمكن حفظها في متغير واستخدامها لاحقاً.\nهذا مفيد عند تريد نتيجة حسابية من الدالة مثل الجمع أو الطرح.\nالكود:\nدالة اجمع(أ، ب) {\n    ارجع أ + ب\n}\nصحيح نتيجة = اجمع(5، 3)\nطباعة(النتيجة)\ntprint: 8', starterCode:'دالة اجمع(أ، ب) {\n    ارجع أ + ب\n}\nصحيح نتيجة = اجمع(5، 3)\nطباعة(النتيجة)', expectedOutput:'8', requirements:'[{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:7, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'دالة إرجاع: تمارين 1', description:'اكتب دالة تطرح عددين وترجع النتيجة. استدعِها بـ 20 و 8 واطبع النتيجة.', starterCode:'', expectedOutput:'12', requirements:'[{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:8, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'دالة إرجاع: تمارين 2', description:'اكتب دالة تضرب عددين وترجع النتيجة. استدعِها بـ 6 و 7 واطبع النتيجة.', starterCode:'', expectedOutput:'42', requirements:'[{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:9, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 4: المصفوفات ──
  { title:'المصفوفات: المثال', description:'(درس) المصفوفة هي قائمة منظمة من العناصر في ترتيب معين!\nلإنشاء مصفوفة في ض، استخدم الأقواس المربعة [] مع العناصر مفصولة بفاصلة.\nللوصول لعنصر معين، استخدم رقم الفهرس (يبدأ من 0) بين أقواس مربعة.\nالكود:\nصحيح[] الأعداد = [10، 20، 30]\nطباعة(الأعداد[0])\ntprint: 10', starterCode:'صحيح[] الأعداد = [10، 20، 30]\nطباعة(الأعداد[0])', expectedOutput:'10', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:10, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'المصفوفات: تمارين 1', description:'أنشئ مصفوفة [5، 10، 15] واطبع العنصر الثاني (الفهرس 1).', starterCode:'', expectedOutput:'10', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:11, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'المصفوفات: تمارين 2', description:'أنشئ مصفوفة ["تفاح"، "موز"، "عنب"] واطبع العنصر الأول.', starterCode:'', expectedOutput:'تفاح', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:12, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 5: طول المصفوفة ──
  { title:'طول المصفوفة: المثال', description:'(درس) لمعرفة عدد العناصر في المصفوفة، استخدم دالة طول()!\nالطول يُرجع رقماً صحيحاً يمثل عدد العناصر الحالية.\nمفيد جداً عند استخدام الحلقات للمرور على جميع العناصر.\nالكود:\nصحيح[] الفواكه = ["تفاح"، "موز"، "برتقال"]\nطباعة(طول(الفواكه))\ntprint: 3', starterCode:'صحيح[] الفواكه = ["تفاح"، "موز"، "برتقال"]\nطباعة(طول(الفواكه))', expectedOutput:'3', requirements:'[{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:13, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'طول المصفوفة: تمارين 1', description:'أنشئ مصفوفة [1، 2، 3، 4، 5] واطبع طولها.', starterCode:'', expectedOutput:'5', requirements:'[{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:14, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'طول المصفوفة: تمارين 2', description:'أنشئ مصفوفة ["أ"، "ب"] واطبع طولها.', starterCode:'', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:15, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 6: تعديل المصفوفة ──
  { title:'تعديل المصفوفة: المثال', description:'(درس) يمكنك تغيير أي عنصر في المصفوفة عن طريق الفهرس!\nاكتب اسم المصفوفة متبوعاً رقم الفهرس بين أقواس مربعة، ثم علامة = ثم القيمة الجديدة.\nهذا يُغيّر قيمة العنصر فقط دون تأثير على باقي العناصر.\nالكود:\nصحيح[] الدرجات = [85، 90، 78]\nالدرجات[1] = 95\nطباعة(الدرجات[1])\ntprint: 95', starterCode:'صحيح[] الدرجات = [85، 90، 78]\nالدرجات[1] = 95\nطباعة(الدرجات[1])', expectedOutput:'95', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:16, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'تعديل المصفوفة: تمارين 1', description:'أنشئ مصفوفة [10، 20، 30] ثم غيّر العنصر الأول إلى 15 واطبعه.', starterCode:'', expectedOutput:'15', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:17, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'تعديل المصفوفة: تمارين 2', description:'أنشئ مصفوفة ["أ"، "ب"، "ج"] ثم غيّر العنصر الأخير إلى "ز" واطبعه.', starterCode:'', expectedOutput:'ز', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:18, xpReward:25, points:25, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 7: حساب المجموع ──
  { title:'حساب المجموع: المثال', description:'(درس) يمكنك حساب مجموع جميع عناصر المصفوفة باستخدام حلقة وكل!\nابدأ بمتغير المجموع = 0، ثم مر على كل عنصر وأضفه للمجموع.\nفي كل دورة، نأخذ العنصر الحالي ونضيفه للمجموع.\nالكود:\nصحيح[] الأعداد = [4، 8، 12]\nصحيح المجموع = 0\nلكل (صحيح ع = 0؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    المجموع = المجموع + الأعداد[ع]\n}\nطباعة(المجموع)\ntprint: 24', starterCode:'صحيح[] الأعداد = [4، 8، 12]\nصحيح المجموع = 0\nلكل (صحيح ع = 0؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    المجموع = المجموع + الأعداد[ع]\n}\nطباعة(المجموع)', expectedOutput:'24', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:19, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'حساب المجموع: تمارين 1', description:'احسب مجموع مصفوفة [5، 10، 15] واطبع النتيجة.', starterCode:'', expectedOutput:'30', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:20, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'حساب المجموع: تمارين 2', description:'احسب مجموع مصفوفة [1، 2، 3، 4] واطبع النتيجة.', starterCode:'', expectedOutput:'10', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:21, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 8: أكبر وأصغر قيمة ──
  { title:'أكبر وأصغر: المثال', description:'(درس) لإيجاد أكبر قيمة في المصفوفة، ابدأ بأول عنصر ثم قارن مع الباقي!\nنفترض أن العنصر الأول هو الأكبر، ثم نمر على باقي العناصر ونقارن.\nإذا وجدنا عنصراً أكبر، نحدّث المتغير. في النهاية، سيكون لدينا الأكبر.\nالكود:\nصحيح[] الأعداد = [3، 7، 2، 9، 5]\nصحيح أكبر = الأعداد[0]\nلكل (صحيح ع = 1؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    إذا (الأعداد[ع] > أكبر) {\n        أكبر = الأعداد[ع]\n    }\n}\nطباعة(أكبر)\ntprint: 9', starterCode:'صحيح[] الأعداد = [3، 7، 2، 9، 5]\nصحيح أكبر = الأعداد[0]\nلكل (صحيح ع = 1؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    إذا (الأعداد[ع] > أكبر) {\n        أكبر = الأعداد[ع]\n    }\n}\nطباعة(أكبر)', expectedOutput:'9', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:22, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'أكبر وأصغر: تمارين 1', description:'أوجد أكبر قيمة في مصفوفة [10، 3، 15، 7] واطبعها.', starterCode:'', expectedOutput:'15', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:23, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'أكبر وأصغر: تمارين 2', description:'أوجد أصغر قيمة في مصفوفة [8، 2، 12، 4] واطبعها.', starterCode:'', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:24, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 9: البحث في المصفوفة ──
  { title:'البحث في المصفوفة: المثال', description:'(درس) للبحث عن عنصر معين في المصفوفة، نمر على كل عنصر ونقارنه بالقيمة المطلوبة!\nنبدأ بفرض أن العنصر غير موجود (الفهرس = -1)، ثم نبحث.\nإذا وجدنا العنصر، نحفظ فهرسه. لو لم نجده، يبقى الفهرس = -1.\nالكود:\nصحيح[] الأعداد = [5، 10، 15، 20]\nصحيح الهدف = 15\nصحيح فهرس = -1\nلكل (صحيح ع = 0؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    إذا (الأعداد[ع] == الهدف) {\n        فهرس = ع\n    }\n}\nطباعة(فهرس)\ntprint: 2', starterCode:'صحيح[] الأعداد = [5، 10، 15، 20]\nصحيح الهدف = 15\nصحيح فهرس = -1\nلكل (صحيح ع = 0؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    إذا (الأعداد[ع] == الهدف) {\n        فهرس = ع\n    }\n}\nطباعة(فهرس)', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:25, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'البحث في المصفوفة: تمارين 1', description:'ابحث عن الرقم 7 في مصفوفة [1، 3، 5، 7، 9] واطبع فهرسه.', starterCode:'', expectedOutput:'3', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:26, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'البحث في المصفوفة: تمارين 2', description:'ابحث عن النص "موز" في مصفوفة ["تفاح"، "موز"، "عنب"] واطبع فهرسه.', starterCode:'', expectedOutput:'1', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:27, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },

  // ── الدرس 10: عد التكرارات ──
  { title:'عد التكرارات: المثال', description:'(درس) يمكنك عد عدد مرات تكرار عنصر معين في المصفوفة!\nنبدأ بعدّاد = 0، ثم نمر على كل عنصر ونقارنه بالقيمة المطلوبة.\nكل مرة نجد فيها العنصر، نزيد العداد بمقدار واحد.\nالكود:\nصحيح[] الأعداد = [1، 2، 2، 3، 2]\nصحيح العدد = 0\nلكل (صحيح ع = 0؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    إذا (الأعداد[ع] == 2) {\n        العدد = العدد + 1\n    }\n}\nطباعة(العدد)\ntprint: 3', starterCode:'صحيح[] الأعداد = [1، 2، 2، 3، 2]\nصحيح العدد = 0\nلكل (صحيح ع = 0؛ ع < طول(الأعداد)؛ ع = ع + 1) {\n    إذا (الأعداد[ع] == 2) {\n        العدد = العدد + 1\n    }\n}\nطباعة(العدد)', expectedOutput:'3', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:28, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'عد التكرارات: تمارين 1', description:'عد تكرار الرقم 5 في مصفوفة [5، 1، 5، 3، 5] واطبع العدد.', starterCode:'', expectedOutput:'3', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:29, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },
  { title:'عد التكرارات: تمارين 2', description:'عد تكرار النص "أحمد" في مصفوفة ["أحمد"، "علي"، "أحمد"، "محمد"] واطبع العدد.', starterCode:'', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:30, xpReward:25, points:30, difficulty:'ADVANCED', dynamicOutput:'' },
];
