module.exports = [
  // ═══════════════════════════════════════════════════════════════
  // TIER 4: البرمجة الكائنية (30 challenges = 10 lessons × 3 exercises)
  // ═══════════════════════════════════════════════════════════════

  // ── الدرس 1: تعريف صنف بسيط ──
  { title:'صنف بسيط: المثال', description:'(درس) الصنف هو قالب لإنشاء كيانات (أشياء) في البرمجة، مثل وصف لسيارة!\nفي ض، استخدم كلمة صنف متبوعة باسم الصنف، ثم الكود داخل قوسين معقوفين.\nالصانع جديد() هو دالة خاصة تُنادي عند إنشاء كيان جديد (باستخدام جديد()).\nالكلمة هذا تشير للكيان الحالي وتخزن القيم في خصائصه.\nالكود:\nصنف دائرة {\n    دالة جديد(نصف_القطر) {\n        هذا.نصف_القطر = نصف_القطر\n    }\n    دالة محيط() {\n        ارجع 2 * 3.14 * هذا.نصف_القطر\n    }\n}\nصحيح د = جديد(7)\nطباعة(د.محيط())\ntprint: 43.96', starterCode:'صنف دائرة {\n    دالة جديد(نصف_القطر) {\n        هذا.نصف_القطر = نصف_القطر\n    }\n    دالة محيط() {\n        ارجع 2 * 3.14 * هذا.نصف_القطر\n    }\n}\nصحيح د = جديد(7)\nطباعة(د.محيط())', expectedOutput:'43.96', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:1, xpReward:40, points:40, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف بسيط: تمارين 1', description:'اكتب صنف مستطيل بطول وعرض، ودالة مساحة(). أنشئ مستطيل بطول 6 وعرض 4 واطبع مساحته.', starterCode:'', expectedOutput:'24', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:2, xpReward:40, points:40, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف بسيط: تمارين 2', description:'اكتب صنف مربع بطول ضلع، ودالة مساحة(). أنشئ مربع بطول 5 واطبع مساحته.', starterCode:'', expectedOutput:'25', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:3, xpReward:40, points:40, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 2: صانع مع قيم افتراضية ──
  { title:'قيم افتراضية: المثال', description:'(درس) يمكنك إعطاء قيم افتراضية لمعاملات الصانع حتى لو لم يُحدد المستخدمها!\nفي دالة جديد()، اكتب المعامل متبوعاً بعلامة = ثم القيمة الافتراضية.\nإذا لم يُرسل المستخدم قيمة، تُستخدم القيمة الافتراضية تلقائياً.\nالكود:\nصنف طالب {\n    دالة جديد(الاسم = "زائر"، العمر = 18) {\n        هذا.الاسم = الاسم\n        هذا.العمر = العمر\n    }\n    دالة عرض() {\n        طباعة(هذا.الاسم)\n        طباعة(هذا.العمر)\n    }\n}\nصحيح ط = جديد()\nط.عرض()\ntprint: زائر\\n18', starterCode:'صنف طالب {\n    دالة جديد(الاسم = "زائر"، العمر = 18) {\n        هذا.الاسم = الاسم\n        هذا.العمر = العمر\n    }\n    دالة عرض() {\n        طباعة(هذا.الاسم)\n        طباعة(هذا.العمر)\n    }\n}\nصحيح ط = جديد()\nط.عرض()', expectedOutput:'زائر\n18', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:4, xpReward:40, points:40, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'قيم افتراضية: تمارين 1', description:'اكتب صنف كتاب بعنوان افتراضي "بدون عنوان"، ودالة عرض() تطبع العنوان. أنشئ كتاباً بعنوان "العلم" واطبعه.', starterCode:'', expectedOutput:'العلم', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:5, xpReward:40, points:40, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'قيم افتراضية: تمارين 2', description:'اكتب صنف حيوان ب nome افتراضي "مجهول"، ودالة صوت(). أنشئ حيواناً ب nome "قط" واطبع صوته " мяو".', starterCode:'', expectedOutput:' мяو', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:6, xpReward:40, points:40, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 3: الخاصية والطريقة ──
  { title:'الخاصةية والطريقة: المثال', description:'(درس) في الصنف، يمكنك دمج البيانات (الخصائص) والدوال (الطريقات) معاً!\nالخاصةية هي متغير يخزن بيانات الكيان (مثل المبلغ)، والطريقة هي دالة تنفيذ عملاً معيناً (مثل حساب الضريبة).\nيمكن للطريقة استخدام خصائص الكيان باستخدام هذا.\nالكود:\nصنف حساب {\n    دالة جديد(المبلغ) {\n        هذا.المبلغ = المبلغ\n    }\n    دالة ضريبة() {\n        ارجع هذا.المبلغ * 0.15\n    }\n    دالة إجمالي() {\n        ارجع هذا.المبلغ + هذا.المبلغ * 0.15\n    }\n}\nصحيح ح = جديد(100)\nطباعة(ح.إجمالي())\ntprint: 115', starterCode:'صنف حساب {\n    دالة جديد(المبلغ) {\n        هذا.المبلغ = المبلغ\n    }\n    دالة ضريبة() {\n        ارجع هذا.المبلغ * 0.15\n    }\n    دالة إجمالي() {\n        ارجع هذا.المبلغ + هذا.المبلغ * 0.15\n    }\n}\nصحيح ح = جديد(100)\nطباعة(ح.إجمالي())', expectedOutput:'115', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:7, xpReward:40, points:45, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'الخاصةية والطريقة: تمارين 1', description:'اكتب صنف خصم بمبلغ، ودالة نسبة_الخصم() ترجع 10% من المبلغ، ودالة بعد_الخصم() ترجع المبلغ بعد الخصم. أنشئ خصم بمبلغ 200 واطبع بعد الخصم.', starterCode:'', expectedOutput:'180', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:8, xpReward:40, points:45, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'الخاصةية والطريقة: تمارين 2', description:'اكتب صنف محيط دائرة بنصف قطر، ودالة محيط() ترجع 2 * 3.14 * نصف القطر، ودالة مساحة() ترجع 3.14 * نصف القطر * نصف القطر. أنشئ دائرة بنصف قطر 5 واطبع مساحتها.', starterCode:'', expectedOutput:'78.5', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:9, xpReward:40, points:45, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 4: صنف مع عداد ──
  { title:'صنف مع عداد: المثال', description:'(درس) يمكنك استخدام متغير داخل الصنف لتتبع حالة تغير مع مرور الوقت!\nفي هذا المثال، العداد يبدأ من 0 ويمكنك زيادته باستخدام دالة زِد().\nهذا يُظهر كيف يمكن للصنف الحفاظ على حالته عبر استدعاءات متعددة.\nالكود:\nصنف عداد {\n    دالة جديد() {\n        هذا.القيمة = 0\n    }\n    دالة زِد() {\n        هذا.القيمة = هذا.القيمة + 1\n    }\n    دالة اعرض() {\n        طباعة(هذا.القيمة)\n    }\n}\nصحيح ع = جديد()\nع.زِد()\nع.زِد()\nع.زِد()\nع.اعرض()\ntprint: 3', starterCode:'صنف عداد {\n    دالة جديد() {\n        هذا.القيمة = 0\n    }\n    دالة زِد() {\n        هذا.القيمة = هذا.القيمة + 1\n    }\n    دالة اعرض() {\n        طباعة(هذا.القيمة)\n    }\n}\nصحيح ع = جديد()\nع.زِد()\nع.زِد()\nع.زِد()\nع.اعرض()', expectedOutput:'3', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:10, xpReward:40, points:40, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف مع عداد: تمارين 1', description:'اكتب صنف عداد يبدأ من 0، ودالة زِد() تزيد 1، ودالة اعرض() تطبع القيمة. أنشئ عداداً وزِده 5 مرات ثم اطبع القيمة.', starterCode:'', expectedOutput:'5', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:11, xpReward:40, points:40, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف مع عداد: تمارين 2', description:'اكتب صنف عداد يبدأ من 10، ودالة انقص() تنقص 1، ودالة اعرض() تطبع القيمة. أنشئ عداداً وانقصه 3 مرات ثم اطبع القيمة.', starterCode:'', expectedOutput:'7', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:12, xpReward:40, points:40, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 5: صنف حساب ──
  { title:'صنف حساب: المثال', description:'(درس) يمكنك إنشاء صنف يمثل حساباً بنكياً مع عمليات إيداع وسحب!\nهذا يُظهر كيف يمكن للصنف إدارة حالة معقدة (الرصيد) باستخدام طريقات متعددة.\nكل طريقة تُغيّر حالة الكيان بطرق مختلفة.\nالكود:\nصنف حساب_بنكي {\n    دالة جديد(الرصيد) {\n        هذا.الرصيد = الرصيد\n    }\n    دالة إيداع(المبلغ) {\n        هذا.الرصيد = هذا.الرصيد + المبلغ\n    }\n    دالة سحب(المبلغ) {\n        هذا.الرصيد = هذا.الرصيد - المبلغ\n    }\n    دالة اعرض() {\n        طباعة(هذا.الرصيد)\n    }\n}\nصحيح ح = جديد(1000)\nح.إيداع(500)\nح.سحب(200)\nح.اعرض()\ntprint: 1300', starterCode:'صنف حساب_بنكي {\n    دالة جديد(الرصيد) {\n        هذا.الرصيد = الرصيد\n    }\n    دالة إيداع(المبلغ) {\n        هذا.الرصيد = هذا.الرصيد + المبلغ\n    }\n    دالة سحب(المبلغ) {\n        هذا.الرصيد = هذا.الرصيد - المبلغ\n    }\n    دالة اعرض() {\n        طباعة(هذا.الرصيد)\n    }\n}\nصحيح ح = جديد(1000)\nح.إيداع(500)\nح.سحب(200)\nح.اعرض()', expectedOutput:'1300', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:13, xpReward:40, points:45, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف حساب: تمارين 1', description:'اكتب صنف حساب بنكي يبدأ برصيد 500، ودالة إيداع() وسحب() وعرض(). أنشئ حساباً وأودع 300 واسحب 100 ثم اطبع الرصيد.', starterCode:'', expectedOutput:'700', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:14, xpReward:40, points:45, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف حساب: تمارين 2', description:'اكتب صنف محفظة ب_balance افتراضي 0، ودالة أضف() واطبع الرصيد. أنشئ محفظة وأضف 250 ثم اطبع الرصيد.', starterCode:'', expectedOutput:'250', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:15, xpReward:40, points:45, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 6: صنف طالب ──
  { title:'صنف طالب: المثال', description:'(درس) يمكنك تمثيل الكيانات الحقيقية بالصنف، مثل طالب له اسم ودرجة!\nهذا يُظهر كيف يمكن للصنف الجمع بين البيانات (الاسم، الدرجة) والمنطق (حالة النجاح).\nالدالة حالة() تستخدم شرطاً لإرجاع قيمة مختلفة بناءً على الدرجة.\nالكود:\nصنف طالب {\n    دالة جديد(الاسم، الدرجة) {\n        هذا.الاسم = الاسم\n        هذا.الدرجة = الدرجة\n    }\n    دالة حالة() {\n        إذا (هذا.الدرجة >= 60) {\n            ارجع "ناجح"\n        } وإلا {\n            ارجع "راسب"\n        }\n    }\n    دالة اعرض() {\n        طباعة(هذا.الاسم)\n        طباعة(هذا.حالة())\n    }\n}\nصحيح ط = جديد("سعود"، 85)\nط.اعرض()\ntprint: سعود\\nناجح', starterCode:'صنف طالب {\n    دالة جديد(الاسم، الدرجة) {\n        هذا.الاسم = الاسم\n        هذا.الدرجة = الدرجة\n    }\n    دالة حالة() {\n        إذا (هذا.الدرجة >= 60) {\n            ارجع "ناجح"\n        } وإلا {\n            ارجع "راسب"\n        }\n    }\n    دالة اعرض() {\n        طباعة(هذا.الاسم)\n        طباعة(هذا.حالة())\n    }\n}\nصحيح ط = جديد("سعود"، 85)\nط.اعرض()', expectedOutput:'سعود\nناجح', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:16, xpReward:40, points:50, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف طالب: تمارين 1', description:'اكتب صنف طالب بالاسم والدرجة، ودالة حالة() ترجع "ناجح" إذا الدرجة >= 50 وإلا "راسب". أنشئ طالباً اسمه "فهد" بدرجة 45 واطبع حالته.', starterCode:'', expectedOutput:'فهد\nراسب', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:17, xpReward:40, points:50, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف طالب: تمارين 2', description:'اكتب صنف طالب بالاسم والدرجة، ودالة لقب() ترجع "ممتاز" إذا >= 90، "جيد جداً" إذا >= 80، "جيد" إذا >= 70، وإلا "مقبول". أنشئ طالباً بدرجة 75 واطبع لقبه.', starterCode:'', expectedOutput:'جيد', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا إذا"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:18, xpReward:40, points:50, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 7: صنف محفظة ──
  { title:'صنف محفظة: المثال', description:'(درس) يمكنك إنشاء صنف يمثل محفظة تحتوي على مجموعة عملات!\nفي الصانع، نُنشئ مصفوفة فارغة لتخزين العملات.\nدالة أضف() تضيف عنصراً جديداً في نهاية المصفوفة.\nدالة عرض() تمر على جميع العناصر وتطبعها.\nالكود:\nصنف محفظة {\n    دالة جديد() {\n        هذا.العملات = []\n    }\n    دالة أضف(العملة) {\n        هذا.العملات[طول(هذا.العملات)] = العملة\n    }\n    دالة عرض() {\n        لكل (صحيح ع = 0؛ ع < طول(هذا.العملات)؛ ع = ع + 1) {\n            طباعة(هذا.العملات[ع])\n        }\n    }\n}\nصحيح م = جديد()\nم.أضف("ذهب")\nم.أضف("فضة")\nم.عرض()\ntprint: ذهب\\nفضة', starterCode:'صنف محفظة {\n    دالة جديد() {\n        هذا.العملات = []\n    }\n    دالة أضف(العملة) {\n        هذا.العملات[طول(هذا.العملات)] = العملة\n    }\n    دالة عرض() {\n        لكل (صحيح ع = 0؛ ع < طول(هذا.العملات)؛ ع = ع + 1) {\n            طباعة(هذا.العملات[ع])\n        }\n    }\n}\nصحيح م = جديد()\nم.أضف("ذهب")\nم.أضف("فضة")\nم.عرض()', expectedOutput:'ذهب\nفضة', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:19, xpReward:40, points:50, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف محفظة: تمارين 1', description:'اكتب صنف قائمة_مشتريات بعناصر فارغة، ودالة أضف() وعرض(). أنشئ قائمة وأضف "حليب" و "خبز" ثم اطبعها.', starterCode:'', expectedOutput:'حليب\nخبز', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:20, xpReward:40, points:50, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف محفظة: تمارين 2', description:'اكتب صنف مجموعة ألوان، ودالة أضف() وعدد(). أنشئ مجموعة وأضف "أحمر" و "أزرق" ثم اطبع العدد.', starterCode:'', expectedOutput:'2', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:21, xpReward:40, points:50, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 8: صنف مع تحقق ──
  { title:'صنف مع تحقق: المثال', description:'(درس) يمكنك إضافة منطق تحقق داخل الصانع لضمان صحة البيانات المُدخلة!\nفي هذا المثال، نتحقق من طول كلمة المرور قبل حفظها.\nإذا كانت غير صالحة، نُعيّن كلمة فارغة ونُعلم أن غير صالحة.\nالكود:\nصنف كلمة_مرور {\n    دالة جديد(كلمة) {\n        إذا (طول(كلمة) >= 8) {\n            هذا.الكلمة = كلمة\n            هذا.صالحة = صواب\n        } وإلا {\n            هذا.الكلمة = ""\n            هذا.صالحة = خطأ\n        }\n    }\n    دالة اعرض() {\n        إذا (هذا.صالحة) {\n            طباعة("صالحة")\n        } وإلا {\n            طباعة("غير صالحة")\n        }\n    }\n}\nصحيح ك = جديد("12345678")\nك.اعرض()\ntprint: صالحة', starterCode:'صنف كلمة_مرور {\n    دالة جديد(كلمة) {\n        إذا (طول(كلمة) >= 8) {\n            هذا.الكلمة = كلمة\n            هذا.صالحة = صواب\n        } وإلا {\n            هذا.الكلمة = ""\n            هذا.صالحة = خطأ\n        }\n    }\n    دالة اعرض() {\n        إذا (هذا.صالحة) {\n            طباعة("صالحة")\n        } وإلا {\n            طباعة("غير صالحة")\n        }\n    }\n}\nصحيح ك = جديد("12345678")\nك.اعرض()', expectedOutput:'صالحة', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:22, xpReward:40, points:50, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف مع تحقق: تمارين 1', description:'اكتب صنف بريد_الكتروني يتحقق من أن البريد يحتوي على @، ودالة اعرض() تطبع "صالح" أو "غير صالح". أنشئ بريداً "test@test.com" واطبع حالته.', starterCode:'', expectedOutput:'صالح', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:23, xpReward:40, points:50, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف مع تحقق: تمارين 2', description:'اكتب صنف عمر يتحقق من أن العمر >= 0، ودالة اعرض() تطبع "سنه" أو "خطأ". أنشئ عمر 25 واطبعه.', starterCode:'', expectedOutput:'سنه', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:24, xpReward:40, points:50, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 9: صنف مع مصفوفة ──
  { title:'صنف مع مصفوفة: المثال', description:'(درس) يمكنك استخدام مصفوفة داخل الصنف لإدارة مجموعة من العناصر!\nفي هذا المثال، الصنف فصل يحتوي على قائمة طلاب.\nيمكنك إضافة عناصر للمصفوفة وعرضها وعددها باستخدام دوال مخصصة.\nالكود:\nصنف فصل {\n    دالة جديد() {\n        هذا.الطلاب = []\n    }\n    دالة أضف_طالب(الاسم) {\n        هذا.الطلاب[طول(هذا.الطلاب)] = الاسم\n    }\n    دالة عرض() {\n        لكل (صحيح ع = 0؛ ع < طول(هذا.الطلاب)؛ ع = ع + 1) {\n            طباعة(هذا.الطلاب[ع])\n        }\n    }\n    دالة عدد() {\n        ارجع طول(هذا.الطلاب)\n    }\n}\nصحيح ف = جديد()\nف.أضف_طالب("أحمد")\nف.أضف_طالب("سعود")\nف.عرض()\nطباعة(ف.عدد())\ntprint: أحمد\\nسعود\\n2', starterCode:'صنف فصل {\n    دالة جديد() {\n        هذا.الطلاب = []\n    }\n    دالة أضف_طالب(الاسم) {\n        هذا.الطلاب[طول(هذا.الطلاب)] = الاسم\n    }\n    دالة عرض() {\n        لكل (صحيح ع = 0؛ ع < طول(هذا.الطلاب)؛ ع = ع + 1) {\n            طباعة(هذا.الطلاب[ع])\n        }\n    }\n    دالة عدد() {\n        ارجع طول(هذا.الطلاب)\n    }\n}\nصحيح ف = جديد()\nف.أضف_طالب("أحمد")\nف.أضف_طالب("سعود")\nف.عرض()\nطباعة(ف.عدد())', expectedOutput:'أحمد\nسعود\n2', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"لكل"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:25, xpReward:40, points:55, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف مع مصفوفة: تمارين 1', description:'اكتب صنف قائمة ألوان، ودالة أضف() وعدد() وعرض(). أنشئ قائمة وأضف "أحمر" و "أخضر" و "أزرق" ثم اطبع العدد.', starterCode:'', expectedOutput:'3', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"طول"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:26, xpReward:40, points:55, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف مع مصفوفة: تمارين 2', description:'اكتب صنف رصيد حساب، ودالة أضف() واطبع الرصيد. أنشئ حساباً وأضف 100 و 200 ثم اطبع الرصيد الإجمالي.', starterCode:'', expectedOutput:'300', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"دالة"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:27, xpReward:40, points:55, difficulty:'INTERMEDIATE', dynamicOutput:'' },

  // ── الدرس 10: صنف متقدم ──
  { title:'صنف متقدم: المثال', description:'(درس) هذا درس تلخيصي يجمع كل ما تعلمته عن الأصناف!\nيحتوي على خصائص (الاسم، الأهداف)، طريقات (تقييم، اعرض)، وشروط متعددة (إذا وإلا إذا).\nالكود:\nصنف كرة_قدم {\n    دالة جديد(الاسم، الأهداف) {\n        هذا.الاسم = الاسم\n        هذا.الأهداف = الأهداف\n    }\n    دالة تقييم() {\n        إذا (هذا.الأهداف >= 10) {\n            ارجع "نجم"\n        } وإلا إذا (هذا.الأهداف >= 5) {\n            ارجع "مهاجم"\n        } وإلا {\n            ارجع "لاعب"\n        }\n    }\n    دالة اعرض() {\n        طباعة(هذا.الاسم)\n        طباعة(هذا.تقييم())\n    }\n}\nصحيح ك = جديد("سالم"، 12)\nك.اعرض()\ntprint: سالم\\nنجم', starterCode:'صنف كرة_قدم {\n    دالة جديد(الاسم، الأهداف) {\n        هذا.الاسم = الاسم\n        هذا.الأهداف = الأهداف\n    }\n    دالة تقييم() {\n        إذا (هذا.الأهداف >= 10) {\n            ارجع "نجم"\n        } وإلا إذا (هذا.الأهداف >= 5) {\n            ارجع "مهاجم"\n        } وإلا {\n            ارجع "لاعب"\n        }\n    }\n    دالة اعرض() {\n        طباعة(هذا.الاسم)\n        طباعة(هذا.تقييم())\n    }\n}\nصحيح ك = جديد("سالم"، 12)\nك.اعرض()', expectedOutput:'سالم\nنجم', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا إذا"},{"type":"must_use_keyword","keyword":"وإلا"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:28, xpReward:40, points:55, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف متقدم: تمارين 1', description:'اكتب صنف سيارة بالتصنيع والموديل وسنة الصنع، ودالة عمر() ترجع سنة الحالية - سنة الصنع، ودالة اعرض(). أنشئ سيارة "toyota" "camry" 2020 واطبع عمرها.', starterCode:'', expectedOutput:'6', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:29, xpReward:40, points:55, difficulty:'INTERMEDIATE', dynamicOutput:'' },
  { title:'صنف متقدم: تمارين 2', description:'اكتب صنف طعام بالاسم والسعر والسعرات، ودالة صحي() ترجع "صحي" إذا السعرات < 200 وإلا "غير صحي". أنشئ طعاماً "تفاح" بسعر 5 وسعرات 95 واطبع حالته.', starterCode:'', expectedOutput:'صحي', requirements:'[{"type":"must_use_keyword","keyword":"صنف"},{"type":"must_use_keyword","keyword":"جديد"},{"type":"must_use_keyword","keyword":"هذا"},{"type":"must_use_keyword","keyword":"إذا"},{"type":"must_use_keyword","keyword":"وإلا"},{"type":"must_use_keyword","keyword":"ارجع"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:30, xpReward:40, points:55, difficulty:'INTERMEDIATE', dynamicOutput:'' },
];
