// ═══════════════════════════════════════════════════════════════
// دورة التشفير (Cryptography) - 10 دروس × 3 تمارين = 30 تحدي
// كلمات مفتاحية: شفر، فكّ، مفتاح، تشفير، هاش، HMAC
// ═══════════════════════════════════════════════════════════════

module.exports = [
  // ── الدرس 1: مفهوم التشفير ──
  { title:'ما هو التشفير: المثال', description:'الشفرة هي عملية تحويل النص إلى شكل غير مقروء. استخدم دالة شفر() لتشفير نص:\nشفر("مرحباً")\nثم اطبع النتيجة.', starterCode:'نص مشفى = شفر("مرحباً")\nطباعة("تم التشفير")', expectedOutput:'تم التشفير', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:1, xpReward:20, points:20, difficulty:'BEGINNER', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'ما هو التشفير: تمارين 1', description:'شفر كلمة "سلام" باستخدام دالة شفر() واطبع "تم التشفير".', starterCode:'', expectedOutput:'تم التشفير', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:2, xpReward:20, points:20, difficulty:'BEGINNER', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'ما هو التشفير: تمارين 2', description:'شفر كلمة "علوم" باستخدام دالة شفر() واطبع "تم التشفير".', starterCode:'', expectedOutput:'تم التشفير', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:1, order:3, xpReward:20, points:20, difficulty:'BEGINNER', dynamicOutput:'', courseId:'CRYPTO' },

  // ── الدرس 2: فك التشفير ──
  { title:'فك التشفير: المثال', description:'فك التشفير هو عكس عملية التشفير. استخدم دالة فكّ() لاستعادة النص الأصلي:\nفكّ("شفرة")\nثم اطبع النتيجة.', starterCode:'نص مفكوك = فكّ("شفرة")\nطباعة("تم فك التشفير")', expectedOutput:'تم فك التشفير', requirements:'[{"type":"must_use_keyword","keyword":"فكّ"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:4, xpReward:20, points:20, difficulty:'BEGINNER', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'فك التشفير: تمارين 1', description:'فكّ تشفير النص "abc" باستخدام دالة فكّ() واطبع "تم فك التشفير".', starterCode:'', expectedOutput:'تم فك التشفير', requirements:'[{"type":"must_use_keyword","keyword":"فكّ"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:5, xpReward:20, points:20, difficulty:'BEGINNER', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'فك التشفير: تمارين 2', description:'فكّ تشفير النص "xyz" باستخدام دالة فكّ() واطبع "تم فك التشفير".', starterCode:'', expectedOutput:'تم فك التشفير', requirements:'[{"type":"must_use_keyword","keyword":"فكّ"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:2, order:6, xpReward:20, points:20, difficulty:'BEGINNER', dynamicOutput:'', courseId:'CRYPTO' },

  // ── الدرس 3: المفتاح ──
  { title:'المفتاح: المثال', description:'المفتاح يُستخدم لتشفير وفك تشفير البيانات. عرّف مفتاحاً واطبعه:\nنص مفتاح = "سري123"\nطباعة(المفتاح)', starterCode:'نص مفتاح = "سري123"\nطباعة(المفتاح)', expectedOutput:'سري123', requirements:'[{"type":"must_use_keyword","keyword":"مفتاح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:7, xpReward:20, points:20, difficulty:'BEGINNER', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'المفتاح: تمارين 1', description:'عرّف مفتاحاً بقيمة "abc456" واطبعه.', starterCode:'', expectedOutput:'abc456', requirements:'[{"type":"must_use_keyword","keyword":"مفتاح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:8, xpReward:20, points:20, difficulty:'BEGINNER', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'المفتاح: تمارين 2', description:'عرّف مفتاحاً بقيمة "def789" واطبعه.', starterCode:'', expectedOutput:'def789', requirements:'[{"type":"must_use_keyword","keyword":"مفتاح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:3, order:9, xpReward:20, points:20, difficulty:'BEGINNER', dynamicOutput:'', courseId:'CRYPTO' },

  // ── الدرس 4: التشفير المتماثل ──
  { title:'التشفير المتماثل: المثال', description:'في التشفير المتماثل نفس المفتاح للتشفير ولفك التشفير. استخدم شفر() مع مفتاح:\nشفر("رسالة"، "مفتاح1")', starterCode:'نص رسالة = شفر("رسالة"، "مفتاح1")\nطباعة(رسالة)', expectedOutput:'رسالة', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:10, xpReward:25, points:25, difficulty:'EASY', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'التشفير المتماثل: تمارين 1', description:'شفر كلمة "سري" باستخدام مفتاح "m1" ثم اطبع النتيجة.', starterCode:'', expectedOutput:'سري', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:11, xpReward:25, points:25, difficulty:'EASY', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'التشفير المتماثل: تمارين 2', description:'شفر كلمة "مخفٍ" باستخدام مفتاح "k2" ثم اطبع النتيجة.', starterCode:'', expectedOutput:'مخفٍ', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:4, order:12, xpReward:25, points:25, difficulty:'EASY', dynamicOutput:'', courseId:'CRYPTO' },

  // ── الدرس 5: التشفير غير المتماثل ──
  { title:'التشفير غير المتماثل: المثال', description:'في التشفير غير المتماثل مفتاح عام للتشفير ومفتاح خاص لفك التشفير:\nشفر("رسالة"، "عام123")', starterCode:'نص مفتاح_عام = "عام123"\nشفر("رسالة")\nطباعة("تم التشفير بالمفتاح العام")', expectedOutput:'تم التشفير بالمفتاح العام', requirements:'[{"type":"must_use_keyword","keyword":"مفتاح"},{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:13, xpReward:25, points:25, difficulty:'EASY', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'التشفير غير المتماثل: تمارين 1', description:'عرّف مفتاحاً عاماً بقيمة "public" وشفر كلمة "سري" واطبع "تم التشفير".', starterCode:'', expectedOutput:'تم التشفير', requirements:'[{"type":"must_use_keyword","keyword":"مفتاح"},{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:14, xpReward:25, points:25, difficulty:'EASY', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'التشفير غير المتماثل: تمارين 2', description:'عرّف مفتاحاً خاصاً بقيمة "private" وشفر كلمة "مخفية" واطبع "تم التشفير".', starterCode:'', expectedOutput:'تم التشفير', requirements:'[{"type":"must_use_keyword","keyword":"مفتاح"},{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:5, order:15, xpReward:25, points:25, difficulty:'EASY', dynamicOutput:'', courseId:'CRYPTO' },

  // ── الدرس 6: تشفير الهاش ──
  { title:'تشفير الهاش: المثال', description:'الهاش يُحوّل النص إلى قيمة ثابتة لا يمكن عكسها. استخدم دالة هاش():\nهاش("كلمة_مرور")', starterCode:'هاش("كلمة_مرور")\nطباعة("تم إنشاء الهاش")', expectedOutput:'تم إنشاء الهاش', requirements:'[{"type":"must_use_keyword","keyword":"هاش"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:16, xpReward:25, points:25, difficulty:'MEDIUM', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'تشفير الهاش: تمارين 1', description:'أنشئ هاش لكلمة "مرور123" باستخدام دالة هاش() واطبع "تم إنشاء الهاش".', starterCode:'', expectedOutput:'تم إنشاء الهاش', requirements:'[{"type":"must_use_keyword","keyword":"هاش"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:17, xpReward:25, points:25, difficulty:'MEDIUM', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'تشفير الهاش: تمارين 2', description:'أنشئ هاش لكلمة "أمين" باستخدام دالة هاش() واطبع "تم إنشاء الهاش".', starterCode:'', expectedOutput:'تم إنشاء الهاش', requirements:'[{"type":"must_use_keyword","keyword":"هاش"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:6, order:18, xpReward:25, points:25, difficulty:'MEDIUM', dynamicOutput:'', courseId:'CRYPTO' },

  // ── الدرس 7: شفرة القيصر ──
  { title:'شفرة القيصر: المثال', description:'شفرة القيصر تحرك كل حرف بعدداً ثابت. مثلاً hello مع إزاحة +3 تصبح khoor:\nشفر_قيصر("hello"، 3)', starterCode:'نص مدخل = "hello"\nطباعة("khoor")', expectedOutput:'khoor', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:19, xpReward:25, points:25, difficulty:'MEDIUM', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'شفرة القيصر: تمارين 1', description:'شفر كلمة "abc" بشفرة قيصر بإزاحة +1 واطبع النتيجة.', starterCode:'', expectedOutput:'bcd', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:20, xpReward:25, points:25, difficulty:'MEDIUM', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'شفرة القيصر: تمارين 2', description:'شفر كلمة "xyz" بشفرة قيصر بإزاحة +2 واطبع النتيجة.', starterCode:'', expectedOutput:'zab', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:7, order:21, xpReward:25, points:25, difficulty:'MEDIUM', dynamicOutput:'', courseId:'CRYPTO' },

  // ── الدرس 8: تشفير XOR ──
  { title:'تشفير XOR: المثال', description:'XOR عملية منطقية تُستخدم في التشفير. 5 XOR 3 = 6:\nصحيح نتيجة = 5 XOR 3\nطباعة(النتيجة)', starterCode:'صحيح نتيجة = 5 XOR 3\nطباعة(النتيجة)', expectedOutput:'6', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:8, order:22, xpReward:30, points:30, difficulty:'MEDIUM', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'تشفير XOR: تمارين 1', description:'احسب 10 XOR 5 واطبع النتيجة.', starterCode:'', expectedOutput:'15', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:8, order:23, xpReward:30, points:30, difficulty:'MEDIUM', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'تشفير XOR: تمارين 2', description:'احسب 7 XOR 7 واطبع النتيجة.', starterCode:'', expectedOutput:'0', requirements:'[{"type":"must_use_keyword","keyword":"صحيح"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:8, order:24, xpReward:30, points:30, difficulty:'MEDIUM', dynamicOutput:'', courseId:'CRYPTO' },

  // ── الدرس 9: HMAC ──
  { title:'HMAC: المثال', description:'HMAC يجمع بين الهاش والمفتاح للتحقق من سلامة البيانات:\nHMAC("رسالة"، "مفتاح")', starterCode:'HMAC("رسالة"، "مفتاح")\nطباعة("تم التحقق")', expectedOutput:'تم التحقق', requirements:'[{"type":"must_use_keyword","keyword":"HMAC"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:9, order:25, xpReward:30, points:30, difficulty:'HARD', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'HMAC: تمارين 1', description:'تحقق من رسالة "أهلاً" بمفتاح "سري" باستخدام HMAC واطبع "تم التحقق".', starterCode:'', expectedOutput:'تم التحقق', requirements:'[{"type":"must_use_keyword","keyword":"HMAC"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:9, order:26, xpReward:30, points:30, difficulty:'HARD', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'HMAC: تمارين 2', description:'تحقق من رسالة "سلام" بمفتاح "عام" باستخدام HMAC واطبع "تم التحقق".', starterCode:'', expectedOutput:'تم التحقق', requirements:'[{"type":"must_use_keyword","keyword":"HMAC"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:9, order:27, xpReward:30, points:30, difficulty:'HARD', dynamicOutput:'', courseId:'CRYPTO' },

  // ── الدرس 10: ملخص التشفير ──
  { title:'ملخص: المثال', description:'ملخص ما تعلمته: التشفير (شفر)، الهاش (هاش)، فك التشفير (فكّ):\nشفر("data")\nهاش("data")\nطباعة("أكملت دورة التشفير")', starterCode:'شفر("data")\nهاش("data")\nطباعة("أكملت دورة التشفير")', expectedOutput:'أكملت دورة التشفير', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"هاش"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:10, order:28, xpReward:35, points:35, difficulty:'HARD', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'ملخص: تمارين 1', description:'شفر كلمة "أحمد" وأنشئ لها هاش واطبع "تم التشفير والهاش".', starterCode:'', expectedOutput:'تم التشفير والهاش', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"هاش"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:10, order:29, xpReward:35, points:35, difficulty:'HARD', dynamicOutput:'', courseId:'CRYPTO' },
  { title:'ملخص: تمارين 2', description:'شفر كلمة "سري" وفكّها ثم اطبع "تم الانتهاء".', starterCode:'', expectedOutput:'تم الانتهاء', requirements:'[{"type":"must_use_keyword","keyword":"شفر"},{"type":"must_use_keyword","keyword":"فكّ"},{"type":"must_use_keyword","keyword":"طباعة"}]', tier:10, order:30, xpReward:35, points:35, difficulty:'HARD', dynamicOutput:'', courseId:'CRYPTO' },
];
