const challenges = [
  // Branch 1: اختبار الاختراق (Penetration Testing) - Tiers 1-10
  // Lesson 1: مقدمة في الاختراق
  {
    title: 'مقدمة في الاختراق: المثال',
    description: 'أنشئ دالة تطبع رسالة ترحيب بالدخول إلى عالم اختبار الاختراق',
    starterCode: 'دالة تحية() {\n  طباعة("مرحباً بك في اختبار الاختراق")\n}',
    expectedOutput: 'مرحباً بك في اختبار الاختراق',
    requirements: ['must_use_keyword:طباعة'],
    tier: 1,
    order: 1,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'مقدمة في الاختراق: تمارين 1',
    description: 'أنشئ دالة تطبع رسالة عن أهمية أمن المعلومات',
    starterCode: '',
    expectedOutput: 'أمن المعلومات مفتاح النجاح في العصر الرقمي',
    requirements: ['must_use_keyword:طباعة'],
    tier: 1,
    order: 2,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'مقدمة في الاختراق: تمارين 2',
    description: 'أنشئ دالة تطبع رسالة عن قواعد الأخلاقيات في اختبار الاختراق',
    starterCode: '',
    expectedOutput: 'الاخلاقيات أساس مهنة اختبار الاختراق',
    requirements: ['must_use_keyword:طباعة'],
    tier: 1,
    order: 3,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 2: جمع المعلومات
  {
    title: 'جمع المعلومات: المثال',
    description: 'أنشئ دالة تطبع رسالة عن طرق جمع المعلومات',
    starterCode: 'دالة جمع_المعلومات() {\n  طباعة("جمع المعلومات هو الخطوة الأولى في الاختراق")\n}',
    expectedOutput: 'جمع المعلومات هو الخطوة الأولى في الاختراق',
    requirements: ['must_use_keyword:طباعة'],
    tier: 2,
    order: 1,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'جمع المعلومات: تمارين 1',
    description: 'أنشئ دالة تطبع رسالة عن مصادر المعلومات المتاحة',
    starterCode: '',
    expectedOutput: 'المصادر العامة هي أفضل نقطة بداية لجمع المعلومات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 2,
    order: 2,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'جمع المعلومات: تمارين 2',
    description: 'أنشئ دالة تطبع رسالة عن أهمية التوثيق أثناء جمع المعلومات',
    starterCode: '',
    expectedOutput: 'التوثيق الدقيق يضمن نجاح عملية الاختراق',
    requirements: ['must_use_keyword:طباعة'],
    tier: 2,
    order: 3,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 3: مسح الشبكات
  {
    title: 'مسح الشبكات: المثال',
    description: 'أنشئ دالة تطبع رسالة عن تقنيات مسح الشبكات',
    starterCode: 'دالة مسح_الشبكة() {\n  طباعة("مسح الشبكة يكشف عن الأجهزة المتصلة")\n}',
    expectedOutput: 'مسح الشبكة يكشف عن الأجهزة المتصلة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 3,
    order: 1,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'مسح الشبكات: تمارين 1',
    description: 'أنشئ دالة تطبع رسالة عن أنواع مسح الشبكات',
    starterCode: '',
    expectedOutput: 'هناك مسح سطحي ومسح عميق للشبكات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 3,
    order: 2,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'مسح الشبكات: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن أهمية مسح المنافذ',
    starterCode: '',
    expectedOutput: 'مسح المنافذ يكشف الخدمات المتاحة على الأجهزة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 3,
    order: 3,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 4: استغلال الثغرات
  {
    title: 'استغلال الثغرات: المثال',
    description: 'أنشئ دالة تطبع رسالة عن استغلال الثغرات الأمنية',
    starterCode: 'دالة استغلال() {\n  طباعة("استغلال الثغرات يتطلب معرفة تقنية عميقة")\n}',
    expectedOutput: 'استغلال الثغرات يتطلب معرفة تقنية عميقة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 4,
    order: 1,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'استغلال الثغرات: تمارين 1',
    description: 'أنشئ دالة تطبع رسالة عن أنواع الثغرات الشائعة',
    starterCode: '',
    expectedOutput: 'ثغرات حقن SQL وXSS من أكثر الثغرات شيوعاً',
    requirements: ['must_use_keyword:طباعة'],
    tier: 4,
    order: 2,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'استغلال الثغرات: تمارين 2',
    description: 'أنشئ دالة تطبع رسالة عن أدوات استغلال الثغرات',
    starterCode: '',
    expectedOutput: 'Metasploit من أقوى أدوات استغلال الثغرات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 4,
    order: 3,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 5: Получение الوصول
  {
    title: 'الوصول إلى النظام: المثال',
    description: 'أنشئ دالة تطبع رسالة عن طرق الحصول على وصول غير مصرح به',
    starterCode: 'دالة وصول() {\n  طباعة("الحصول على وصول غير مصرح به هو هدف المختبر")\n}',
    expectedOutput: 'الحصول على وصول غير مصرح به هو هدف المختبر',
    requirements: ['must_use_keyword:طباعة'],
    tier: 5,
    order: 1,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'الوصول إلى النظام: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن طرق اختراق كلمات المرور',
    starterCode: '',
    expectedOutput: 'هجمات القاموس وهجمات القوة الغاشمة شائعة في اختراق كلمات المرور',
    requirements: ['must_use_keyword:طباعة'],
    tier: 5,
    order: 2,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'الوصول إلى النظام: تمارين 2',
    description: 'أنشئ دالة تطبع رسالة عن هجمات الأطراف الثانية',
    starterCode: '',
    expectedOutput: 'هجمات الأطراف الثانية تستغل ثقة المستخدم في الخدمات الموثوقة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 5,
    order: 3,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 6: حفظ الوصول
  {
    title: 'حفظ الوصول: المثال',
    description: 'أنشئ دالة ت.print رسالة عن طرق الحفاظ على الوصول بعد الاختراق',
    starterCode: 'دالة حفظ_الوصول() {\n  طباعة("حفظ الوصول يضمن الاستمرارية في الاختراق")\n}',
    expectedOutput: 'حفظ الوصول يضمن الاستمرارية في الاختراق',
    requirements: ['must_use_keyword:طباعة'],
    tier: 6,
    order: 1,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'حفظ الوصول: تمارين 1',
    description: 'أنشئ دالة تطبع رسالة عن Backdoors',
    starterCode: '',
    expectedOutput: 'ال thuخانيات الخلفية تسمح بالوصول المستدام للنظام',
    requirements: ['must_use_keyword:طباعة'],
    tier: 6,
    order: 2,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'حفظ الوصول: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن Rootkits',
    starterCode: '',
    expectedOutput: 'Rootkits تختفي في النظام وتحافظ على الوصول لفترة طويلة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 6,
    order: 3,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 7: تجنب الكشف
  {
    title: 'تجنب الكشف: المثال',
    description: 'أنشئ دالة تطبع رسالة عن تقنيات تجنب أنظمة الكشف',
    starterCode: 'دالة تجنب_الكشف() {\n  طباعة("تجنب الكشف هو فن الاختراق")\n}',
    expectedOutput: 'تجنب الكشف هو فن الاختراق',
    requirements: ['must_use_keyword:طباعة'],
    tier: 7,
    order: 1,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تجنب الكشف: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن تقنيات التمويه',
    starterCode: '',
    expectedOutput: 'التمويه يخفي نشاط المختبر عن أنظمة المراقبة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 7,
    order: 2,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تجنب الكشف: تمارين 2',
    description: 'أنشئ دالة تطبع رسالة عن تشفير الاتصالات',
    starterCode: '',
    expectedOutput: 'تشفير الاتصالات يمنع اعتراض البيانات أثناء النقل',
    requirements: ['must_use_keyword:طباعة'],
    tier: 7,
    order: 3,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 8: تقرير الاختراق
  {
    title: 'تقرير الاختراق: المثال',
    description: 'أنشئ دالة تطبع رسالة عن أهمية كتابة تقارير الاختراق',
    starterCode: 'دالة تقرير() {\n  طباعة("تقرير الاختراق هو النتيجة النهائية للعمل")\n}',
    expectedOutput: 'تقرير الاختراق هو النتيجة النهائية للعمل',
    requirements: ['must_use_keyword:طباعة'],
    tier: 8,
    order: 1,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تقرير الاختراق: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن مكونات تقرير الاختراق',
    starterCode: '',
    expectedOutput: 'التقرير يجب أن يشمل الملخص التنفيذي والتقنيات المستخدمة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 8,
    order: 2,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تقرير الاختراق: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن توصيات التقرير',
    starterCode: '',
    expectedOutput: 'التوصيات يجب أن تكون عملية وقابلة للتطبيق',
    requirements: ['must_use_keyword:طباعة'],
    tier: 8,
    order: 3,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 9: أدوات اختبار الاختراق
  {
    title: 'أدوات اختبار الاختراق: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية استخدام الأدوات في الاختراق',
    starterCode: 'دالة أدوات() {\n  طباعة("الأدوات تسهل عملية اختبار الاختراق")\n}',
    expectedOutput: 'الأدوات تسهل عملية اختبار الاختراق',
    requirements: ['must_use_keyword:طباعة'],
    tier: 9,
    order: 1,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'أدوات اختبار الاختراق: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن أدوات مسح الشبكات',
    starterCode: '',
    expectedOutput: 'Nmap من أقوى أدوات مسح الشبكات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 9,
    order: 2,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'أدوات اختبار الاختراق: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن أدوات تحليل حزم البيانات',
    starterCode: '',
    expectedOutput: 'Wireshark يسمح بتحليل حزم البيانات بالتفصيل',
    requirements: ['must_use_keyword:طباعة'],
    tier: 9,
    order: 3,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 10: تمرين عملي
  {
    title: 'تمرين عملي: المثال',
    description: 'أنشئ دالة تطبع رسالة عن أهمية التدريب العملي',
    starterCode: 'دالة تمرين() {\n  طباعة("التدريب العملي يثبيت المعرفة النظرية")\n}',
    expectedOutput: 'التدريب العملي يثبيت المعرفة النظرية',
    requirements: ['must_use_keyword:طباعة'],
    tier: 10,
    order: 1,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تمرين عملي: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن بيئة التدريب الآمنة',
    starterCode: '',
    expectedOutput: 'بيئة التدريب الآمنة تجرب المهارات بدون مخاطرة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 10,
    order: 2,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تمرين عملي: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن تقييم التقدم في التدريب',
    starterCode: '',
    expectedOutput: 'تقييم التقدم يساعد على تحسين الأداء باستمرار',
    requirements: ['must_use_keyword:طباعة'],
    tier: 10,
    order: 3,
    xpReward: 20,
    points: 10,
    difficulty: 'BEGINNER',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Branch 2: حماية الشبكات (Network Security) - Tiers 11-20
  // Lesson 11: مقدمة أمن الشبكات
  {
    title: 'مقدمة أمن الشبكات: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية أمن الشبكات',
    starterCode: 'دالة أمن_الشبكة() {\n  طباعة("أمن الشبكات حماية البيانات من التهديدات")\n}',
    expectedOutput: 'أمن الشبكات حماية البيانات من التهديدات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 11,
    order: 1,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'مقدمة أمن الشبكات: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن التهديدات الشائعة على الشبكات',
    starterCode: '',
    expectedOutput: 'هجمات DDoS والديدان من أكثر التهديدات شيوعاً',
    requirements: ['must_use_keyword:طباعة'],
    tier: 11,
    order: 2,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'مقدمة أمن الشبكات: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن نماذج أمن الشبكات',
    starterCode: '',
    expectedOutput: 'نموذج OSI يوفر إطاراً شاملاً لفهم أمن الشبكات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 11,
    order: 3,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 12: جدران الحماية
  {
    title: 'جدران الحماية: المثال',
    description: 'أنشئ دالة ت.print رسالة عن دور جدران الحماية',
    starterCode: 'دالة جدار_الحماية() {\n  طباعة("جدار الحماية هو الخط الأول للدفاع")\n}',
    expectedOutput: 'جدار الحماية هو الخط الأول للدفاع',
    requirements: ['must_use_keyword:طباعة'],
    tier: 12,
    order: 1,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'جدران الحماية: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن أنواع جدران الحماية',
    starterCode: '',
    expectedOutput: 'هناك جدران حماية مادية وبرمجية ومدمجة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 12,
    order: 2,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'جدران الحماية: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن قواعد جدران الحماية',
    starterCode: '',
    expectedOutput: 'قواعد جدران الحماية تحكم حركة المرور الواردة والصادرة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 12,
    order: 3,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 13: أنظمة كشف الاختراق
  {
    title: 'أنظمة كشف الاختراق: المثال',
    description: 'أنشئ دالة ت.print رسالة عن دور أنظمة كشف الاختراق',
    starterCode: 'دالة كشف_الاختراق() {\n  طباعة("أنظمة كشف الاختراق تراقب نشاط الشبكة")\n}',
    expectedOutput: 'أنظمة كشف الاختراق تراقب نشاط الشبكة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 13,
    order: 1,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'أنظمة كشف الاختراق: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن أنواع أنظمة كشف الاختراق',
    starterCode: '',
    expectedOutput: 'هناك أنظمة كشف مبنية على القواعد وأخرى مبنية على الشذوذ',
    requirements: ['must_use_keyword:طباعة'],
    tier: 13,
    order: 2,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'أنظمة كشف الاختراق: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن تحذيرات كشف الاختراق',
    starterCode: '',
    expectedOutput: 'التحذيرات الإيجابية الكاذبة تقلل من فعالية أنظمة الكشف',
    requirements: ['must_use_keyword:طباعة'],
    tier: 13,
    order: 3,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 14: VPN
  {
    title: 'VPN: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية VPN في أمن الشبكات',
    starterCode: 'دالة VPN() {\n  طباعة("VPN يوفر اتصالاً آمناً عبر الإنترنت")\n}',
    expectedOutput: 'VPN يوفر اتصالاً آمناً عبر الإنترنت',
    requirements: ['must_use_keyword:طباعة'],
    tier: 14,
    order: 1,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'VPN: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن بروتوكولات VPN',
    starterCode: '',
    expectedOutput: 'IPSec وOpenVPN من أكثر بروتوكولات VPN استخداماً',
    requirements: ['must_use_keyword:طباعة'],
    tier: 14,
    order: 2,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'VPN: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن فوائد استخدام VPN',
    starterCode: '',
    expectedOutput: 'VPN يحافظ على الخصوصية ويمنع تتبع النشاط عبر الإنترنت',
    requirements: ['must_use_keyword:طباعة'],
    tier: 14,
    order: 3,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 15: تشفير الشبكات
  {
    title: 'تشفير الشبكات: المثال',
    description: 'أنشئ دالة ت.print رسالة عن دور التشفير في حماية الشبكات',
    starterCode: 'دالة تشفير() {\n  طباعة("التشفير يحمي البيانات من الوصول غير المصرح به")\n}',
    expectedOutput: 'التشفير يحمي البيانات من الوصول غير المصرح به',
    requirements: ['must_use_keyword:طباعة'],
    tier: 15,
    order: 1,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تشفير الشبكات: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن خوارزميات التشفير',
    starterCode: '',
    expectedOutput: 'AES وRSA من أكثر خوارزميات التشفير استخداماً',
    requirements: ['must_use_keyword:طباعة'],
    tier: 15,
    order: 2,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تشفير الشبكات: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن تشفير البيانات في حالة السكون',
    starterCode: '',
    expectedOutput: 'تشفير البيانات في حالة السكون يحمي المعلومات المخزنة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 15,
    order: 3,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 16: أمان WiFi
  {
    title: 'أمان WiFi: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية تأمين شبكات WiFi',
    starterCode: 'دالة أمان_WIFI() {\n  طباعة("شبكات WiFi غير المؤمنة معرضة للهجمات")\n}',
    expectedOutput: 'شبكات WiFi غير المؤمنة معرضة للهجمات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 16,
    order: 1,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'أمان WiFi: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن بروتوكولات الأمان في WiFi',
    starterCode: '',
    expectedOutput: 'WPA2 وWPA3 هما أفضل بروتوكولات أمان WiFi',
    requirements: ['must_use_keyword:طباعة'],
    tier: 16,
    order: 2,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'أمان WiFi: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن هجمات WiFi الشائعة',
    starterCode: '',
    expectedOutput: 'هجمات القوة الغاشمة وهجمات القناة الجانبية شائعة في WiFi',
    requirements: ['must_use_keyword:طباعة'],
    tier: 16,
    order: 3,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 17: مراقبة الشبكة
  {
    title: 'مراقبة الشبكة: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية مراقبة الشبكة',
    starterCode: 'دالة مراقبة() {\n  طباعة("المراقبة المستمرة تكشف عن الأنشطة المشبوهة")\n}',
    expectedOutput: 'المراقبة المستمرة تكشف عن الأنشطة المشبوهة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 17,
    order: 1,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'مراقبة الشبكة: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن أدوات مراقبة الشبكة',
    starterCode: '',
    expectedOutput: 'SNMP وNetFlow من أدوات مراقبة الشبكة الشائعة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 17,
    order: 2,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'مراقبة الشبكة: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن تحليل حركة المرور',
    starterCode: '',
    expectedOutput: 'تحليل حركة المرور يكشف عن الأنماط غير الطبيعية',
    requirements: ['must_use_keyword:طباعة'],
    tier: 17,
    order: 3,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 18: استجابة الحوادث
  {
    title: 'استجابة الحوادث: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية الاستجابة السريعة للحوادث',
    starterCode: 'دالة استجابة() {\n  طباعة("الاستجابة السريعة تقلل من تأثير الحوادث الأمنية")\n}',
    expectedOutput: 'الاستجابة السريعة تقلل من تأثير الحوادث الأمنية',
    requirements: ['must_use_keyword:طباعة'],
    tier: 18,
    order: 1,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'استجابة الحوادث: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن مراحل الاستجابة للحوادث',
    starterCode: '',
    expectedOutput: 'الكشف والاحتواء والإزالة والاسترداد مراحل الاستجابة للحوادث',
    requirements: ['must_use_keyword:طباعة'],
    tier: 18,
    order: 2,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'استجابة الحوادث: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن فريق الاستجابة للحوادث',
    starterCode: '',
    expectedOutput: 'فريق الاستجابة للحوادث يجب أن يكون مدرباً ومجهزاً',
    requirements: ['must_use_keyword:طباعة'],
    tier: 18,
    order: 3,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 19: سياسات الأمان
  {
    title: 'سياسات الأمان: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية سياسات الأمان',
    starterCode: 'دالة سياسات() {\n  طباعة("سياسات الأمان تحدد الإجراءات الأمنية")\n}',
    expectedOutput: 'سياسات الأمان تحدد الإجراءات الأمنية',
    requirements: ['must_use_keyword:طباعة'],
    tier: 19,
    order: 1,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'سياسات الأمان: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن مكونات سياسات الأمان',
    starterCode: '',
    expectedOutput: 'السياسات يجب أن تشمل الوصول والتحكم والحماية',
    requirements: ['must_use_keyword:طباعة'],
    tier: 19,
    order: 2,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'سياسات الأمان: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن تطبيق سياسات الأمان',
    starterCode: '',
    expectedOutput: 'تطبيق السياسات يتطلب التدريب والawareness للموظفين',
    requirements: ['must_use_keyword:طباعة'],
    tier: 19,
    order: 3,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 20: حماية التطبيقات
  {
    title: 'حماية التطبيقات: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية حماية التطبيقات',
    starterCode: 'دالة حماية_التطبيقات() {\n  طباعة("حماية التطبيقات تبدأ من مرحلة التطوير")\n}',
    expectedOutput: 'حماية التطبيقات تبدأ من مرحلة التطوير',
    requirements: ['must_use_keyword:طباعة'],
    tier: 20,
    order: 1,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'حماية التطبيقات: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن ثغرات OWASP Top 10',
    starterCode: '',
    expectedOutput: 'OWASP Top 10 يسرد أكثر الثغرات أماناً خطورة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 20,
    order: 2,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'حماية التطبيقات: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن اختبار أمان التطبيقات',
    starterCode: '',
    expectedOutput: 'اختبار الأمان يجب أن يكون جزءاً من دورة تطوير البرمجيات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 20,
    order: 3,
    xpReward: 25,
    points: 12,
    difficulty: 'INTERMEDIATE',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Branch 3: التحليل الجنائي (Digital Forensics) - Tiers 21-30
  // Lesson 21: مقدمة التحليل الجنائي
  {
    title: 'مقدمة التحليل الجنائي: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية التحليل الجنائي الرقمي',
    starterCode: 'دالة تحليل_جنائي() {\n  طباعة("التحليل الجنائي الرقمي يكشف الأدلة الإلكترونية")\n}',
    expectedOutput: 'التحليل الجنائي الرقمي يكشف الأدلة الإلكترونية',
    requirements: ['must_use_keyword:طباعة'],
    tier: 21,
    order: 1,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'مقدمة التحليل الجنائي: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن مراحل التحليل الجنائي',
    starterCode: '',
    expectedOutput: 'الجمع والتحليل والتقرير مراحل التحليل الجنائي',
    requirements: ['must_use_keyword:طباعة'],
    tier: 21,
    order: 2,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'مقدمة التحليل الجنائي: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن سلسلة الحفظ',
    starterCode: '',
    expectedOutput: 'سلسلة الحفظ تضمن مصداقية الأدلة الرقمية',
    requirements: ['must_use_keyword:طباعة'],
    tier: 21,
    order: 3,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 22: اقراص الأقراص
  {
    title: 'استخراج الأقراص: المثال',
    description: 'أنشئ دالة ت.print رسالة عن تقنيات استخراج البيانات من الأقراص',
    starterCode: 'دالة استخراج() {\n  طباعة("استخراج البيانات يتطلب أدوات متخصصة")\n}',
    expectedOutput: 'استخراج البيانات يتطلب أدوات متخصصة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 22,
    order: 1,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'استخراج الأقراص: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن أنواع الأقراص الصلبة',
    starterCode: '',
    expectedOutput: 'HDD وSSD لها خصائص مختلفة في التحليل الجنائي',
    requirements: ['must_use_keyword:طباعة'],
    tier: 22,
    order: 2,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'استخراج الأقراص: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن استخراج الأقراص المحذوفة',
    starterCode: '',
    expectedOutput: 'استعادة الملفات المحذوفة ممكنة باستخدام الأدوات المناسبة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 22,
    order: 3,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 23: تحليل الذاكرة
  {
    title: 'تحليل الذاكرة: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية تحليل الذاكرة في التحليل الجنائي',
    starterCode: 'دالة تحليل_الذاكرة() {\n  طباعة("تحليل الذاكرة يكشف عن العمليات النشطة")\n}',
    expectedOutput: 'تحليل الذاكرة يكشف عن العمليات النشطة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 23,
    order: 1,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تحليل الذاكرة: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن أدوات تحليل الذاكرة',
    starterCode: '',
    expectedOutput: 'Volatility من أقوى أدوات تحليل الذاكرة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 23,
    order: 2,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تحليل الذاكرة: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن صور الذاكرة',
    starterCode: '',
    expectedOutput: 'صور الذاكرة تحتوي على معلومات حية عن حالة النظام',
    requirements: ['must_use_keyword:طباعة'],
    tier: 23,
    order: 3,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 24: تحليل الشبكات
  {
    title: 'تحليل الشبكات: المثال',
    description: 'أنشئ دالة ت.print رسالة عن تحليل حركة المرور الشبكية',
    starterCode: 'دالة تحليل_الشبكة() {\n  طباعة("تحليل الشبكة يكشف عن الاتصالات المشبوهة")\n}',
    expectedOutput: 'تحليل الشبكة يكشف عن الاتصالات المشبوهة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 24,
    order: 1,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تحليل الشبكات: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن تحليل حزم البيانات',
    starterCode: '',
    expectedOutput: 'تحليل حزم البيانات يكشف عن محتويات الاتصالات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 24,
    order: 2,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تحليل الشبكات: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن بروتوكولات التحليل',
    starterCode: '',
    expectedOutput: 'بروتوكولات TCP/IP وUDP تحتاج إلى فهم عميق للتحليل',
    requirements: ['must_use_keyword:طباعة'],
    tier: 24,
    order: 3,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 25: البريد الإلكتروني
  {
    title: 'تحليل البريد الإلكتروني: المثال',
    description: 'أنشئ دالة ت.print رسالة عن تحليل البريد الإلكتروني في التحليل الجنائي',
    starterCode: 'دالة تحليل_البريد() {\n  طباعة("البريد الإلكتروني يحتوي على معلومات قيّمة")\n}',
    expectedOutput: 'البريد الإلكتروني يحتوي على معلومات قيّمة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 25,
    order: 1,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تحليل البريد الإلكتروني: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن التوقيعات الرقمية في البريد',
    starterCode: '',
    expectedOutput: 'التوقيعات الرقمية تتحقق من صحة مصدر البريد الإلكتروني',
    requirements: ['must_use_keyword:طباعة'],
    tier: 25,
    order: 2,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'تحليل البريد الإلكتروني: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن هجمات التصيد عبر البريد',
    starterCode: '',
    expectedOutput: 'هجمات التصيد عبر البريد من أكثر التهديدات شيوعاً',
    requirements: ['must_use_keyword:طباعة'],
    tier: 25,
    order: 3,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 26: الأدلة الرقمية
  {
    title: 'الأدلة الرقمية: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أنواع الأدلة الرقمية',
    starterCode: 'دالة الأدلة() {\n  طباعة("الأدلة الرقمية تشمل الملفات والسجلات والصور")\n}',
    expectedOutput: 'الأدلة الرقمية تشمل الملفات والسجلات والصور',
    requirements: ['must_use_keyword:طباعة'],
    tier: 26,
    order: 1,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'الأدلة الرقمية: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن جمع الأدلة الرقمية',
    starterCode: '',
    expectedOutput: 'جمع الأدلة يجب أن يتم وفقاً لإجراءات صارمة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 26,
    order: 2,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'الأدلة الرقمية: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن تحليل الأدلة الرقمية',
    starterCode: '',
    expectedOutput: 'تحليل الأدلة يتطلب خبرة في الأدوات والتقنيات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 26,
    order: 3,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 27: سلسلة الحفظ
  {
    title: 'سلسلة الحفظ: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية سلسلة الحفظ في التحليل الجنائي',
    starterCode: 'دالة سلسلة_الحفظ() {\n  طباعة("سلسلة الحفظ تضمن نظافة الأدلة")\n}',
    expectedOutput: 'سلسلة الحفظ تضمن نظافة الأدلة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 27,
    order: 1,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'سلسلة الحفظ: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن توثيق سلسلة الحفظ',
    starterCode: '',
    expectedOutput: 'التوثيق الدقيق لسلسلة الحفظ ضروري لمصداقية الأدلة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 27,
    order: 2,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'سلسلة الحفظ: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن التوقيعات الرقمية في سلسلة الحفظ',
    starterCode: '',
    expectedOutput: 'التوقيعات الرقمية تثبت سلامة الأدلة من التلاعب',
    requirements: ['must_use_keyword:طباعة'],
    tier: 27,
    order: 3,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 28: التوقيعات الرقمية
  {
    title: 'التوقيعات الرقمية: المثال',
    description: 'أنشئ دالة ت.print رسالة عن دور التوقيعات الرقمية في أمن المعلومات',
    starterCode: 'دالة توقيع() {\n  طباعة("التوقيعات الرقمية تضمن الأصالة والسلامة")\n}',
    expectedOutput: 'التوقيعات الرقمية تضمن الأصالة والسلامة',
    requirements: ['must_use_keyword:طباعة'],
    tier: 28,
    order: 1,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'التوقيعات الرقمية: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن كيف تعمل التوقيعات الرقمية',
    starterCode: '',
    expectedOutput: 'التوقيعات الرقمية تستخدم التشفير المتماثل وغير المتماثل',
    requirements: ['must_use_keyword:طباعة'],
    tier: 28,
    order: 2,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'التوقيعات الرقمية: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن تطبيقات التوقيعات الرقمية',
    starterCode: '',
    expectedOutput: 'التوقيعات الرقمية تستخدم في البريد الإلكتروني والبرامج والمستندات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 28,
    order: 3,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 29: التقارير الجنائية
  {
    title: 'التقارير الجنائية: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية التقارير الجنائية',
    starterCode: 'دالة تقارير() {\n  طباعة("التقارير الجنائية هي النتيجة النهائية للتحليل")\n}',
    expectedOutput: 'التقارير الجنائية هي النتيجة النهائية للتحليل',
    requirements: ['must_use_keyword:طباعة'],
    tier: 29,
    order: 1,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'التقارير الجنائية: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن مكونات التقرير الجنائي',
    starterCode: '',
    expectedOutput: 'التقرير يجب أن يشمل المقدمة والمنهجية والنتائج والاستنتاجات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 29,
    order: 2,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'التقارير الجنائية: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن تقديم التقارير في المحكمة',
    starterCode: '',
    expectedOutput: 'التقارير يجب أن تكون واضحة ومفهومة للقاضي والهيئة القضائية',
    requirements: ['must_use_keyword:طباعة'],
    tier: 29,
    order: 3,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },

  // Lesson 30: دراسة حالة
  {
    title: 'دراسة حالة: المثال',
    description: 'أنشئ دالة ت.print رسالة عن أهمية دراسة الحالات في التحليل الجنائي',
    starterCode: 'دالة دراسة() {\n  طباعة("دراسة الحالات الحقيقية تثري المعرفة العملية")\n}',
    expectedOutput: 'دراسة الحالات الحقيقية تثري المعرفة العملية',
    requirements: ['must_use_keyword:طباعة'],
    tier: 30,
    order: 1,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'دراسة حالة: تمارين 1',
    description: 'أنشئ دالة ت.print رسالة عن تحليل دراسات الحالة السابقة',
    starterCode: '',
    expectedOutput: 'تحليل الحالات السابقة يكشف عن أنماط التهديدات',
    requirements: ['must_use_keyword:طباعة'],
    tier: 30,
    order: 2,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  },
  {
    title: 'دراسة حالة: تمارين 2',
    description: 'أنشئ دالة ت.print رسالة عن تطبيق الدروس المستفادة من دراسات الحالة',
    starterCode: '',
    expectedOutput: 'الدروس المستفادة من الحالات السابقة تحسن الاستجابة للمستقبل',
    requirements: ['must_use_keyword:طباعة'],
    tier: 30,
    order: 3,
    xpReward: 30,
    points: 15,
    difficulty: 'ADVANCED',
    dynamicOutput: '',
    courseId: 'CYBER'
  }
];

module.exports = challenges;
