# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $32, %rsp
.L_main_entry:
  leaq -8(%rbp), %rax
  movq $5, (%rax)
  leaq -16(%rbp), %rbx
  movq $3, (%rbx)
  leaq -24(%rbp), %rcx
  movq (%rax), %rdx
  movq (%rbx), %rsi
  movq %rdx, %rdi
  addq %rsi, %rdi
  movq %rdi, (%rcx)
  movq (%rcx), %r8
  movq %r8, %rax
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
