# Generated by DAAD Compiler
.text
.globl مجموع
مجموع:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_مجموع_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_مجموع_epilogue
.L_مجموع_epilogue:
  addq $224, %rsp
  leave
  ret

.globl طرح
طرح:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_طرح_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  subq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_طرح_epilogue
.L_طرح_epilogue:
  addq $224, %rsp
  leave
  ret

.globl ضرب
ضرب:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_ضرب_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  imulq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_ضرب_epilogue
.L_ضرب_epilogue:
  addq $224, %rsp
  leave
  ret

.globl قسمة
قسمة:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_قسمة_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  cqo
  idivq -48(%rbp)
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_قسمة_epilogue
.L_قسمة_epilogue:
  addq $224, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $384, %rsp
.L_main_entry:
  leaq -232(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $100, (%rax)
  leaq -240(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $25, (%rax)
  leaq -248(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rdx, -24(%rbp)
  movq %rcx, -32(%rbp)
  movq %r8, -40(%rbp)
  movq %r9, -48(%rbp)
  movq %rcx, -56(%rbp)
  movq %r8, -64(%rbp)
  movq %r9, -72(%rbp)
  movq %rax, -80(%rbp)
  movq %r8, -88(%rbp)
  movq %r9, -96(%rbp)
  movq %rax, -104(%rbp)
  movq %r10, -112(%rbp)
  movq %r9, -120(%rbp)
  movq %rax, -128(%rbp)
  movq %rdi, -136(%rbp)
  movq %rsi, -144(%rbp)
  movq %rdi, -152(%rbp)
  movq %rsi, -160(%rbp)
  movq %rdx, -168(%rbp)
  movq %rcx, -176(%rbp)
  movq %rsi, -184(%rbp)
  movq %rdx, -192(%rbp)
  movq %rsi, -200(%rbp)
  movq %rcx, -208(%rbp)
  movq %rsi, -216(%rbp)
  movq -32(%rbp), %rdi
  movq -40(%rbp), %rsi
  callq مجموع
  movq %rax, %r9
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rsi
  movq -24(%rbp), %rdx
  movq -32(%rbp), %rcx
  movq -40(%rbp), %r8
  movq -48(%rbp), %r9
  movq -56(%rbp), %rcx
  movq -64(%rbp), %r8
  movq -72(%rbp), %r9
  movq -80(%rbp), %rax
  movq -88(%rbp), %r8
  movq -96(%rbp), %r9
  movq -104(%rbp), %rax
  movq -112(%rbp), %r10
  movq -120(%rbp), %r9
  movq -128(%rbp), %rax
  movq -136(%rbp), %rdi
  movq -144(%rbp), %rsi
  movq -152(%rbp), %rdi
  movq -160(%rbp), %rsi
  movq -168(%rbp), %rdx
  movq -176(%rbp), %rcx
  movq -184(%rbp), %rsi
  movq -192(%rbp), %rdx
  movq -200(%rbp), %rsi
  movq -208(%rbp), %rcx
  movq -216(%rbp), %rsi
  movq %rdx, %rax
  movq %r9, %rcx
  movq %rcx, (%rax)
  leaq -256(%rbp), %rax
  movq %rax, %rcx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %r9
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rdx, -24(%rbp)
  movq %rcx, -32(%rbp)
  movq %r8, -40(%rbp)
  movq %r9, -48(%rbp)
  movq %rcx, -56(%rbp)
  movq %r8, -64(%rbp)
  movq %r9, -72(%rbp)
  movq %rax, -80(%rbp)
  movq %r8, -88(%rbp)
  movq %r9, -96(%rbp)
  movq %rax, -104(%rbp)
  movq %r10, -112(%rbp)
  movq %r9, -120(%rbp)
  movq %rax, -128(%rbp)
  movq %rdi, -136(%rbp)
  movq %rsi, -144(%rbp)
  movq %rdi, -152(%rbp)
  movq %rsi, -160(%rbp)
  movq %rdx, -168(%rbp)
  movq %rcx, -176(%rbp)
  movq %rsi, -184(%rbp)
  movq %rdx, -192(%rbp)
  movq %rsi, -200(%rbp)
  movq %rcx, -208(%rbp)
  movq %rsi, -216(%rbp)
  movq -64(%rbp), %rdi
  movq -72(%rbp), %rsi
  callq طرح
  movq %rax, %rax
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rsi
  movq -24(%rbp), %rdx
  movq -32(%rbp), %rcx
  movq -40(%rbp), %r8
  movq -48(%rbp), %r9
  movq -56(%rbp), %rcx
  movq -64(%rbp), %r8
  movq -72(%rbp), %r9
  movq -80(%rbp), %rax
  movq -88(%rbp), %r8
  movq -96(%rbp), %r9
  movq -104(%rbp), %rax
  movq -112(%rbp), %r10
  movq -120(%rbp), %r9
  movq -128(%rbp), %rax
  movq -136(%rbp), %rdi
  movq -144(%rbp), %rsi
  movq -152(%rbp), %rdi
  movq -160(%rbp), %rsi
  movq -168(%rbp), %rdx
  movq -176(%rbp), %rcx
  movq -184(%rbp), %rsi
  movq -192(%rbp), %rdx
  movq -200(%rbp), %rsi
  movq -208(%rbp), %rcx
  movq -216(%rbp), %rsi
  movq %rcx, %rax
  movq %rax, %rcx
  movq %rcx, (%rax)
  leaq -264(%rbp), %rax
  movq %rax, %r8
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r9
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rax
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rdx, -24(%rbp)
  movq %rcx, -32(%rbp)
  movq %r8, -40(%rbp)
  movq %r9, -48(%rbp)
  movq %rcx, -56(%rbp)
  movq %r8, -64(%rbp)
  movq %r9, -72(%rbp)
  movq %rax, -80(%rbp)
  movq %r8, -88(%rbp)
  movq %r9, -96(%rbp)
  movq %rax, -104(%rbp)
  movq %r10, -112(%rbp)
  movq %r9, -120(%rbp)
  movq %rax, -128(%rbp)
  movq %rdi, -136(%rbp)
  movq %rsi, -144(%rbp)
  movq %rdi, -152(%rbp)
  movq %rsi, -160(%rbp)
  movq %rdx, -168(%rbp)
  movq %rcx, -176(%rbp)
  movq %rsi, -184(%rbp)
  movq %rdx, -192(%rbp)
  movq %rsi, -200(%rbp)
  movq %rcx, -208(%rbp)
  movq %rsi, -216(%rbp)
  movq -96(%rbp), %rdi
  movq -104(%rbp), %rsi
  callq ضرب
  movq %rax, %r10
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rsi
  movq -24(%rbp), %rdx
  movq -32(%rbp), %rcx
  movq -40(%rbp), %r8
  movq -48(%rbp), %r9
  movq -56(%rbp), %rcx
  movq -64(%rbp), %r8
  movq -72(%rbp), %r9
  movq -80(%rbp), %rax
  movq -88(%rbp), %r8
  movq -96(%rbp), %r9
  movq -104(%rbp), %rax
  movq -112(%rbp), %r10
  movq -120(%rbp), %r9
  movq -128(%rbp), %rax
  movq -136(%rbp), %rdi
  movq -144(%rbp), %rsi
  movq -152(%rbp), %rdi
  movq -160(%rbp), %rsi
  movq -168(%rbp), %rdx
  movq -176(%rbp), %rcx
  movq -184(%rbp), %rsi
  movq -192(%rbp), %rdx
  movq -200(%rbp), %rsi
  movq -208(%rbp), %rcx
  movq -216(%rbp), %rsi
  movq %r8, %rax
  movq %r10, %rcx
  movq %rcx, (%rax)
  leaq -272(%rbp), %rax
  movq %rax, %r9
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rax
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rdx, -24(%rbp)
  movq %rcx, -32(%rbp)
  movq %r8, -40(%rbp)
  movq %r9, -48(%rbp)
  movq %rcx, -56(%rbp)
  movq %r8, -64(%rbp)
  movq %r9, -72(%rbp)
  movq %rax, -80(%rbp)
  movq %r8, -88(%rbp)
  movq %r9, -96(%rbp)
  movq %rax, -104(%rbp)
  movq %r10, -112(%rbp)
  movq %r9, -120(%rbp)
  movq %rax, -128(%rbp)
  movq %rdi, -136(%rbp)
  movq %rsi, -144(%rbp)
  movq %rdi, -152(%rbp)
  movq %rsi, -160(%rbp)
  movq %rdx, -168(%rbp)
  movq %rcx, -176(%rbp)
  movq %rsi, -184(%rbp)
  movq %rdx, -192(%rbp)
  movq %rsi, -200(%rbp)
  movq %rcx, -208(%rbp)
  movq %rsi, -216(%rbp)
  movq -128(%rbp), %rdi
  movq -136(%rbp), %rsi
  callq قسمة
  movq %rax, %rsi
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rsi
  movq -24(%rbp), %rdx
  movq -32(%rbp), %rcx
  movq -40(%rbp), %r8
  movq -48(%rbp), %r9
  movq -56(%rbp), %rcx
  movq -64(%rbp), %r8
  movq -72(%rbp), %r9
  movq -80(%rbp), %rax
  movq -88(%rbp), %r8
  movq -96(%rbp), %r9
  movq -104(%rbp), %rax
  movq -112(%rbp), %r10
  movq -120(%rbp), %r9
  movq -128(%rbp), %rax
  movq -136(%rbp), %rdi
  movq -144(%rbp), %rsi
  movq -152(%rbp), %rdi
  movq -160(%rbp), %rsi
  movq -168(%rbp), %rdx
  movq -176(%rbp), %rcx
  movq -184(%rbp), %rsi
  movq -192(%rbp), %rdx
  movq -200(%rbp), %rsi
  movq -208(%rbp), %rcx
  movq -216(%rbp), %rsi
  movq %r9, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  leaq -280(%rbp), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  addq -168(%rbp), %rax
  movq %rax, %rcx
  movq %r8, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rcx, %rax
  addq -184(%rbp), %rax
  movq %rax, %rdx
  movq %r9, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  addq -200(%rbp), %rax
  movq %rax, %rcx
  movq %rdi, %rax
  movq %rcx, %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $384, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
