# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $32, %rsp
entry:
  subq $8, %rsp
  movq %rsp, %rax
  movq $10, (%rax)
  subq $8, %rsp
  movq %rsp, %rbx
  movq $20, (%rbx)
  subq $8, %rsp
  movq %rsp, %rcx
  movq (%rax), %rdx
  movq (%rbx), %rsi
  movq %rdx, %rdi
  addq %rsi, %rdi
  movq %rdi, (%rcx)
  subq $8, %rsp
  movq %rsp, %r8
  movq (%rcx), %r9
  movq %r9, %rax
  imulq $2, %rax
  movq %rax, %r10
  movq %r10, (%r8)
  movq (%r8), %r11
  movq %r11, %rax
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
