# Generated by DAAD Compiler
.text
.globl مضروب
مضروب:
  pushq %rbp
  movq %rsp, %rbp
  subq $240, %rsp
  movq %rdi, -8(%rbp)
.L_مضروب_entry:
  leaq -88(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  cmpq $1, %rax
  setle %al
  movzbl %al, %eax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_مضروب_if_then
  jmp .L_مضروب_if_merge
.L_مضروب_if_then:
  movq $1, %rax
  jmp .L_مضروب_epilogue
.L_مضروب_if_merge:
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  subq $1, %rax
  movq %rax, %rdi
  movq %rdi, -16(%rbp)
  movq %rsi, -24(%rbp)
  movq %rdx, -32(%rbp)
  movq %rsi, -40(%rbp)
  movq %rdx, -48(%rbp)
  movq %rdi, -56(%rbp)
  movq %rdx, -64(%rbp)
  movq %rdi, -72(%rbp)
  movq -56(%rbp), %rdi
  callq مضروب
  movq %rax, %rdx
  movq -16(%rbp), %rdi
  movq -24(%rbp), %rsi
  movq -32(%rbp), %rdx
  movq -40(%rbp), %rsi
  movq -48(%rbp), %rdx
  movq -56(%rbp), %rdi
  movq -64(%rbp), %rdx
  movq -72(%rbp), %rdi
  movq %rsi, %rax
  imulq -64(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  jmp .L_مضروب_epilogue
.L_مضروب_epilogue:
  addq $240, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  movq %rdi, -8(%rbp)
  movq $10, %rdi
  callq مضروب
  movq %rax, %rdi
  movq -8(%rbp), %rdi
  movq %rdi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
