# Generated by DAAD Compiler
.text
.globl مجموع
مجموع:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_مجموع_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_مجموع_epilogue
.L_مجموع_epilogue:
  addq $224, %rsp
  leave
  ret

.globl معدل
معدل:
  pushq %rbp
  movq %rsp, %rbp
  subq $272, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rdx, -24(%rbp)
.L_معدل_entry:
  leaq -128(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -136(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -144(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq -24(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -152(%rbp), %rax
  movq %rax, %rcx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %r8, %rax
  addq -72(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -88(%rbp), %rax
  movq %rax, %rdx
  movq %rcx, %rax
  movq %rdx, %rcx
  movq %rcx, (%rax)
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  cqo
  movq $3, %rcx
  idivq %rcx
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_معدل_epilogue
.L_معدل_epilogue:
  addq $272, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $288, %rsp
.L_main_entry:
  leaq -144(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $1, (%rax)
  leaq -152(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $90, (%rax)
  leaq -160(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $85, (%rax)
  leaq -168(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $78, (%rax)
  leaq -176(%rbp), %rax
  movq %rax, %rcx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %r9
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rax
  movq %rdi, -8(%rbp)
  movq %rdi, -16(%rbp)
  movq %rsi, -24(%rbp)
  movq %rdx, -32(%rbp)
  movq %rcx, -40(%rbp)
  movq %r8, -48(%rbp)
  movq %r9, -56(%rbp)
  movq %rax, -64(%rbp)
  movq %r10, -72(%rbp)
  movq %r9, -80(%rbp)
  movq %rcx, -88(%rbp)
  movq %r8, -96(%rbp)
  movq %rdi, -104(%rbp)
  movq %rsi, -112(%rbp)
  movq %rdx, -120(%rbp)
  movq %rdi, -128(%rbp)
  movq -56(%rbp), %rdi
  movq -64(%rbp), %rsi
  callq مجموع
  movq %rax, %r10
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rdi
  movq -24(%rbp), %rsi
  movq -32(%rbp), %rdx
  movq -40(%rbp), %rcx
  movq -48(%rbp), %r8
  movq -56(%rbp), %r9
  movq -64(%rbp), %rax
  movq -72(%rbp), %r10
  movq -80(%rbp), %r9
  movq -88(%rbp), %rcx
  movq -96(%rbp), %r8
  movq -104(%rbp), %rdi
  movq -112(%rbp), %rsi
  movq -120(%rbp), %rdx
  movq -128(%rbp), %rdi
  movq %rdi, -8(%rbp)
  movq %rdi, -16(%rbp)
  movq %rsi, -24(%rbp)
  movq %rdx, -32(%rbp)
  movq %rcx, -40(%rbp)
  movq %r8, -48(%rbp)
  movq %r9, -56(%rbp)
  movq %rax, -64(%rbp)
  movq %r10, -72(%rbp)
  movq %r9, -80(%rbp)
  movq %rcx, -88(%rbp)
  movq %r8, -96(%rbp)
  movq %rdi, -104(%rbp)
  movq %rsi, -112(%rbp)
  movq %rdx, -120(%rbp)
  movq %rdi, -128(%rbp)
  movq -48(%rbp), %rdi
  movq -72(%rbp), %rsi
  callq مجموع
  movq %rax, %r9
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rdi
  movq -24(%rbp), %rsi
  movq -32(%rbp), %rdx
  movq -40(%rbp), %rcx
  movq -48(%rbp), %r8
  movq -56(%rbp), %r9
  movq -64(%rbp), %rax
  movq -72(%rbp), %r10
  movq -80(%rbp), %r9
  movq -88(%rbp), %rcx
  movq -96(%rbp), %r8
  movq -104(%rbp), %rdi
  movq -112(%rbp), %rsi
  movq -120(%rbp), %rdx
  movq -128(%rbp), %rdi
  movq %rcx, %rax
  movq %r9, %rcx
  movq %rcx, (%rax)
  leaq -184(%rbp), %rax
  movq %rax, %rcx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rdi, -8(%rbp)
  movq %rdi, -16(%rbp)
  movq %rsi, -24(%rbp)
  movq %rdx, -32(%rbp)
  movq %rcx, -40(%rbp)
  movq %r8, -48(%rbp)
  movq %r9, -56(%rbp)
  movq %rax, -64(%rbp)
  movq %r10, -72(%rbp)
  movq %r9, -80(%rbp)
  movq %rcx, -88(%rbp)
  movq %r8, -96(%rbp)
  movq %rdi, -104(%rbp)
  movq %rsi, -112(%rbp)
  movq %rdx, -120(%rbp)
  movq %rdi, -128(%rbp)
  movq -96(%rbp), %rdi
  movq -104(%rbp), %rsi
  movq -112(%rbp), %rdx
  callq معدل
  movq %rax, %rdx
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rdi
  movq -24(%rbp), %rsi
  movq -32(%rbp), %rdx
  movq -40(%rbp), %rcx
  movq -48(%rbp), %r8
  movq -56(%rbp), %r9
  movq -64(%rbp), %rax
  movq -72(%rbp), %r10
  movq -80(%rbp), %r9
  movq -88(%rbp), %rcx
  movq -96(%rbp), %r8
  movq -104(%rbp), %rdi
  movq -112(%rbp), %rsi
  movq -120(%rbp), %rdx
  movq -128(%rbp), %rdi
  movq %rcx, %rax
  movq %rdx, %rcx
  movq %rcx, (%rax)
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $288, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
