# Generated by DAAD Compiler
.text
.globl اجمع
اجمع:
  pushq %rbp
  movq %rsp, %rbp
  subq $16, %rsp
  movq %rdi, %rax
  movq %rsi, %rbx
.L_اجمع_entry:
  leaq -8(%rbp), %rcx
  movq %rax, (%rcx)
  leaq -16(%rbp), %rdx
  movq %rbx, (%rdx)
  movq (%rcx), %rsi
  movq (%rdx), %rdi
  movq %rsi, %r8
  addq %rdi, %r8
  movq %r8, %rax
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $16, %rsp
.L_main_entry:
  movq $3, %rdi
  movq $4, %rsi
  callq اجمع
  movq %rax, %rax
  movq %rax, %rax
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
