# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $416, %rsp
.L_main_entry:
  leaq -272(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  addq $8, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  addq $16, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  addq $24, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  addq $32, %rax
  movq %rax, %rdi
  leaq -280(%rbp), %rax
  movq %rax, %rdi
  leaq -288(%rbp), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  addq $8, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq -168(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq -184(%rbp), %rax
  movq %rax, %rdi
  leaq -296(%rbp), %rax
  movq %rax, %rdi
  leaq -304(%rbp), %rax
  movq %rax, %rsi
  leaq -312(%rbp), %rax
  movq %rax, %rdx
  nop
  movq %rdx, %rax
  addq $8, %rax
  movq %rax, %rcx
  nop
  movq %rsi, %rax
  addq $8, %rax
  movq %rax, %rdx
  movq %rsi, %rax
  addq $16, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $416, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
