# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
.L_main_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  addq $8, %rax
  movq %rax, %rdi
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $224, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
