# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $368, %rsp
.L_main_entry:
  leaq -216(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  addq $8, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  addq $16, %rax
  movq %rax, %rdi
  nop
  leaq -224(%rbp), %rax
  movq %rax, %rdi
  leaq -232(%rbp), %rax
  movq %rax, %rsi
  nop
  movq %rsi, %rax
  addq $8, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq -128(%rbp), %rax
  movq %rax, %rdi
  leaq -240(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $5, (%rax)
  leaq -248(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $10, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  movq %rdi, %rcx
  cmpq %rcx, %rax
  setl %al
  movzbl %al, %eax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  cmpq $0, %rax
  setg %al
  movzbl %al, %eax
  movq %rax, %rsi
  movq %rcx, %rax
  andq -192(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_merge
.L_main_if_then:
  jmp .L_main_if_merge
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $368, %rsp
  leave
  ret

.section .rodata
.str0: .asciz "أحمد"


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
