# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $336, %rsp
.L_main_entry:
  leaq -184(%rbp), %rax
  movq %rax, %rdi
  leaq -192(%rbp), %rax
  movq %rax, %rsi
  leaq -200(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movsd %rcx, %xmm0
  addsd -40(%rbp), %xmm0
  movsd %xmm0, %r9
  movq %rdx, %rax
  movq %r9, %rcx
  movq %rcx, (%rax)
  leaq -208(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movsd %rcx, %xmm0
  subsd -72(%rbp), %xmm0
  movsd %xmm0, %r9
  movq %rdx, %rax
  movq %r9, %rcx
  movq %rcx, (%rax)
  leaq -216(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movsd %rcx, %xmm0
  mulsd -104(%rbp), %xmm0
  movsd %xmm0, %r9
  movq %rdx, %rax
  movq %r9, %rcx
  movq %rcx, (%rax)
  leaq -224(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movsd %rcx, %xmm0
  divsd -136(%rbp), %xmm0
  movsd %xmm0, %r9
  movq %rdx, %rax
  movq %r9, %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movsd %rdx, %xmm0
  ucomisd -160(%rbp), %xmm0
  setg %al
  movzbl %al, %eax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_merge
.L_main_if_then:
  jmp .L_main_if_merge
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $336, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
