# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $208, %rsp
.L_main_entry:
  leaq -56(%rbp), %rax
  movq %rax, %rdi
  # malloc
  movq $100, %rdi
  callq malloc
  movq %rax, %rsi
  movq %rdi, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  leaq -64(%rbp), %rax
  movq %rax, %rsi
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  # realloc
  movq %rdx, %rdi
  movq $200, %rsi
  callq realloc
  movq %rax, %rdi
  movq %rsi, %rax
  movq %rdi, %rcx
  movq %rcx, (%rax)
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $208, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
