# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  leaq -32(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $10, (%rax)
  leaq -40(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $20, (%rax)
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
