# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $192, %rsp
.L_main_entry:
  leaq -48(%rbp), %rax
  movq %rax, %rdi
  # malloc
  movq $8, %rdi
  callq malloc
  movq %rax, %rsi
  movq %rdi, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  cmpq $0, %rax
  setne %al
  movzbl %al, %eax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_merge
.L_main_if_then:
  jmp .L_main_if_merge
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $192, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
