# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/m_hmoz/Documents/Dhad-Studio-Unified/Compiler;/home/m_hmoz/Documents/Dhad-Studio-Unified/Compiler/build-make")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "runtime;headers;stdlib;examples")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_EXAMPLES_DESCRIPTION "Sample .daad source files to get started")
set(CPACK_COMPONENT_EXAMPLES_DISPLAY_NAME "Example Programs")
set(CPACK_COMPONENT_EXAMPLES_INSTALL_TYPES "Full")
set(CPACK_COMPONENT_HEADERS_DESCRIPTION "C++ header files for the Daad engine (include/Daad/)")
set(CPACK_COMPONENT_HEADERS_DISPLAY_NAME "Development Headers")
set(CPACK_COMPONENT_HEADERS_INSTALL_TYPES "Full;Developer")
set(CPACK_COMPONENT_RUNTIME_DESCRIPTION "The daad-compiler CLI executable")
set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "Daad Compiler")
set(CPACK_COMPONENT_STDLIB_DESCRIPTION "Daad standard library headers (Math.hpp, String.hpp)")
set(CPACK_COMPONENT_STDLIB_DISPLAY_NAME "Standard Library")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "DaadStudio built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "NSIS")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/m_hmoz/Documents/Dhad-Studio-Unified/Compiler/build-make;DaadStudio;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_CONTACT "https://github.com/daad-studio")
set(CPACK_NSIS_CREATE_ICONS_EXTRA "CreateShortCut '$DESKTOP\\Daad Studio.lnk' '$INSTDIR\\bin\\daad-compiler.exe'")
set(CPACK_NSIS_DELETE_ICONS_EXTRA "Delete '$DESKTOP\\Daad Studio.lnk'")
set(CPACK_NSIS_DISPLAY_NAME "Daad Studio")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_HELP_LINK "https://github.com/daad-studio")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_MANUFACTURER "Daad Studio Team")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_PACKAGE_NAME "DaadStudio")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_NSIS_URL_INFO_ABOUT "https://github.com/daad-studio")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/m_hmoz/Documents/Dhad-Studio-Unified/Compiler/build-make/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "https://github.com/daad-studio")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "A complete development environment for the Daad Arabic programming language, ;featuring a compiler (daad-compiler), IDE with Andalusian Manuscript theme, ;and VS Code extension.")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Daad Studio - Arabic Programming Language Compiler and IDE")
set(CPACK_PACKAGE_FILE_NAME "DaadStudio-1.0.0-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "DaadStudio 1.0.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "DaadStudio 1.0.0")
set(CPACK_PACKAGE_NAME "DaadStudio")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Daad Studio Team")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/m_hmoz/Documents/Dhad-Studio-Unified/Compiler/LICENSE")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-4.2/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/m_hmoz/Documents/Dhad-Studio-Unified/Compiler/build-make/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/m_hmoz/Documents/Dhad-Studio-Unified/Compiler/build-make/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
