# Generated by DAAD Compiler
.text
.globl اجمع
اجمع:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_اجمع_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_اجمع_epilogue
.L_اجمع_epilogue:
  addq $224, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $208, %rsp
.L_main_entry:
  leaq -64(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  leaq -72(%rbp), %rax
  movq %rax, %rsi
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rsi, -24(%rbp)
  movq %rdx, -32(%rbp)
  movq %rsi, -40(%rbp)
  movq %rdi, -48(%rbp)
  movq $10, %rdi
  movq $20, %rsi
  callq اجمع
  movq %rax, %rdx
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rsi
  movq -24(%rbp), %rsi
  movq -32(%rbp), %rdx
  movq -40(%rbp), %rsi
  movq -48(%rbp), %rdi
  movq %rsi, %rax
  movq %rdx, %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  cmpq $10, %rax
  sete %al
  movzbl %al, %eax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_merge
.L_main_if_then:
  jmp .L_main_if_merge
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $208, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
