import os
import shutil

# Cleanup moc pre-processing files
build_dir = r"C:\daad-build\Projects\برمجه\build"
autogen_dir = os.path.join(build_dir, "frontend\DaadStudioIDE_autogen")
moc_def_file = os.path.join(autogen_dir, "moc_predefs.h")
moc_dir = os.path.join(autogen_dir, "SVODSI3R2M")

print("Cleaning up moc pre-processing files...")
print(f"Removing: {autogen_dir}")

# Remove the autogen directory if it exists
if os.path.exists(autogen_dir):
    shutil.rmtree(autogen_dir)
    print(f"✓ Removed: {autogen_dir}")

print(f"Removing: {moc_dir}")
if os.path.exists(moc_dir):
    shutil.rmtree(moc_dir)
    print(f"✓ Removed: {moc_dir}")

# Create the moc_predefs.h file first
os.makedirs(autogen_dir, exist_ok=True)

with open(moc_def_file, "w", encoding="utf-8") as f:
    f.write("""#ifndef MOC_PREDCRS_H
#define MOC_PREDCRS_H

#include <QtCore/qglobal.h>

#ifndef Q_MOC_OUTPUT_REVISION
#define Q_MOC_OUTPUT_REVISION 67
#endif

#if defined(QT_NAMESPACE) && defined(QT_NAMESPACE_OPEN)
#define QT_NAMESPACE_OPEN
#endif

#if defined(QT_NAMESPACE) && defined(QT_NAMESPACE_CLOSE)
#define QT_NAMESPACE_CLOSE
#endif

#else
#error "This file is autogenerated by moc. To edit, open the .hpp file instead."
#endif
""")

print(f"✓ Created moc_predefs.h for moc pre-processing")

# Change to build directory
os.chdir(build_dir)
print(f"Changed to directory: {os.getcwd()}")

# Continue with the build
print("Continuing build after cleaning moc pre-processing...")
import subprocess
import sys

result = subprocess.run(["cmake", "--build", ".", "--parallel", "4"], 
                       capture_output=True, text=True)

if result.returncode == 0:
    print("✓ Build completed successfully after cleaning moc files")

    # Verify QML deployment
    qml_dir = os.path.join(build_dir, "bin\qml")
    if os.path.exists(os.path.join(qml_dir, "Main.qml")):
        print("✓ QML files deployed successfully")
    else:
        print("Warning: QML not found, deploying manually...")
        src_qml = os.path.join(build_dir, "..\..\frontend\qml")
        if os.path.exists(src_qml):
            shutil.rmtree(qml_dir, ignore_errors=True)
            os.makedirs(qml_dir, exist_ok=True)
            shutil.copy2(os.path.join(src_qml, "Main.qml"), qml_dir)
            print("✓ QML files manually deployed")

    # Verify Qt5 DLLs are available
    qt5_target = os.path.join(build_dir, "bin")
    qt5_dlls = ["Qt5Core.dll", "Qt5Gui.dll", "Qt5Quick.dll", "Qt5Qml.dll", "Qt5Widgets.dll"]
    missing = []

    for dll in qt5_dlls:
        if not os.path.exists(os.path.join(qt5_target, dll)):
            missing.append(dll)

    if missing:
        print(f"Deploying Qt5 DLLs: {', '.join(missing)}")

        # Copy from MSYS64
        msys64 = r"C:\msys64\mingw64\bin"
        for dll in missing:
            src = os.path.join(msys64, dll)
            if os.path.exists(src):
                shutil.copy2(src, qt5_target)
                print(f"Copied {dll}")

    print(""")
    print("=========================================")
    print("Build completed successfully!")
    print("=========================================")
    print("")
    print("IDE executable:")
    print("  build\bin\DaadStudioIDE.exe")
    print("")
    print("Run from:")
    print("  cd build\bin")
    print("  .\DaadStudioIDE.exe")
    print("")

else:
    print("✗ Build failed!")
    print(result.stderr)
    sys.exit(result.returncode)
