#pragma once

#include <string>
#include <cstddef>

namespace daad {

enum class TokenType {
    // Literals
    TOKEN_NUMBER,
    TOKEN_STRING,
    TOKEN_IDENTIFIER,
    TOKEN_KEYWORD,

    // ═══ Distinct keyword token types (TOKEN_KW_*) ═══
    // 1. Data Types & Fundamentals (8)
    TOKEN_KW_INT,
    TOKEN_KW_DOUBLE,
    TOKEN_KW_BOOL,
    TOKEN_KW_CHAR,
    TOKEN_KW_STRING,
    TOKEN_KW_CONST,
    TOKEN_KW_VOID,
    TOKEN_KW_AUTO,

    // 2. Literals & Typedef (4)
    TOKEN_KW_TRUE,
    TOKEN_KW_FALSE,
    TOKEN_KW_NULLPTR,
    TOKEN_KW_TYPEDEF,

    // 3. Control Flow (13)
    TOKEN_KW_IF,
    TOKEN_KW_ELSE,
    TOKEN_KW_WHILE,
    TOKEN_KW_DO,
    TOKEN_KW_FOR,
    TOKEN_KW_IN,
    TOKEN_KW_SWITCH,
    TOKEN_KW_CASE,
    TOKEN_KW_DEFAULT,
    TOKEN_KW_BREAK,
    TOKEN_KW_CONTINUE,
    TOKEN_KW_GOTO,
    TOKEN_KW_RETURN,

    // 4. OOP & Scoping (5)
    TOKEN_KW_CLASS,
    TOKEN_KW_STRUCT,
    TOKEN_KW_ENUM,
    TOKEN_KW_INTERFACE,
    TOKEN_KW_NAMESPACE,

    // 5. Access & Inheritance (7)
    TOKEN_KW_PUBLIC,
    TOKEN_KW_PRIVATE,
    TOKEN_KW_PROTECTED,
    TOKEN_KW_INHERIT,
    TOKEN_KW_SELF,
    TOKEN_KW_BASE,
    TOKEN_KW_ABSTRACT,

    // 6. Functions & Memory (9)
    TOKEN_KW_FUNCTION,
    TOKEN_KW_NEW,
    TOKEN_KW_DELETE,
    TOKEN_KW_POINTER,
    TOKEN_KW_REFERENCE,
    TOKEN_KW_STATIC,
    TOKEN_KW_INLINE,
    TOKEN_KW_EXTERN,
    TOKEN_KW_TEMPLATE,

    // 7. Exception Handling (10)
    TOKEN_KW_TRY,
    TOKEN_KW_CATCH,
    TOKEN_KW_FINALLY,
    TOKEN_KW_THROW,
    TOKEN_KW_ASSERT,
    TOKEN_KW_EXCEPTION,
    TOKEN_KW_TYPEOF,
    TOKEN_KW_SIZEOF,
    TOKEN_KW_INCREMENT,
    TOKEN_KW_DECREMENT,

    // 8. Advanced Systems (10)
    TOKEN_KW_SYNC,
    TOKEN_KW_AWAIT,
    TOKEN_KW_THREAD,
    TOKEN_KW_LOCK,
    TOKEN_KW_SHARED,
    TOKEN_KW_UNIQUE,
    TOKEN_KW_IMPORT,
    TOKEN_KW_EXPORT,
    TOKEN_KW_MODULE,
    TOKEN_KW_ALTERNATIVE,

    // 9. GUI Keywords (14)
    TOKEN_KW_BUTTON,
    TOKEN_KW_TEXTFIELD,
    TOKEN_KW_COMBOBOX,
    TOKEN_KW_IMAGE,
    TOKEN_KW_CHECKBOX,
    TOKEN_KW_SLIDER,
    TOKEN_KW_DROPDOWN,
    TOKEN_KW_PANEL,
    TOKEN_KW_LABEL,
    TOKEN_KW_COLUMN,
    TOKEN_KW_ROW,
    TOKEN_KW_GRID,
    TOKEN_KW_PROGRESSBAR,
    TOKEN_KW_TABBAR,

    // 10. Print / Input (2)
    TOKEN_KW_PRINT,
    TOKEN_KW_INPUT,

    // 11. Arabic logic (2)
    TOKEN_KW_AND_ARABIC,
    TOKEN_KW_OR_ARABIC,

    // 12. Image Processing (20)
    TOKEN_KW_LOAD_IMAGE,
    TOKEN_KW_DRAW_IMAGE,
    TOKEN_KW_IMAGE_SIZE,
    TOKEN_KW_SAVE_IMAGE,
    TOKEN_KW_CROP_IMAGE,
    TOKEN_KW_RESIZE,
    TOKEN_KW_ROTATE_IMAGE,
    TOKEN_KW_FLIP_IMAGE,
    TOKEN_KW_OPACITY,
    TOKEN_KW_FILTER,
    TOKEN_KW_OVERLAY,
    TOKEN_KW_BACKGROUND,
    TOKEN_KW_PIXEL,
    TOKEN_KW_DRAW,
    TOKEN_KW_FILL,
    TOKEN_KW_RECTANGLE,
    TOKEN_KW_CIRCLE,
    TOKEN_KW_LINE,
    TOKEN_KW_TEXT_ON_CANVAS,
    TOKEN_KW_CLEAR,

    // 13. Coordinate axes (2)
    TOKEN_KW_X,
    TOKEN_KW_Y,

    // Operators
    TOKEN_PLUS,
    TOKEN_PLUS_PLUS,
    TOKEN_PLUS_EQUALS,
    TOKEN_MINUS,
    TOKEN_MINUS_MINUS,
    TOKEN_MINUS_EQUALS,
    TOKEN_STAR,
    TOKEN_STAR_EQUALS,
    TOKEN_SLASH,
    TOKEN_SLASH_EQUALS,
    TOKEN_PERCENT,
    TOKEN_PERCENT_EQUALS,
    TOKEN_POWER,
    TOKEN_POWER_ASSIGN,
    TOKEN_EQUALS,
    TOKEN_EQUAL_EQUAL,
    TOKEN_NOT,
    TOKEN_NOT_EQUALS,
    TOKEN_AND,
    TOKEN_OR,
    TOKEN_LESS,
    TOKEN_LESS_EQUALS,
    TOKEN_GREATER,
    TOKEN_GREATER_EQUALS,
    TOKEN_QUESTION,

    // Delimiters
    TOKEN_LEFT_BRACE,
    TOKEN_RIGHT_BRACE,
    TOKEN_LEFT_PAREN,
    TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACKET,
    TOKEN_RIGHT_BRACKET,
    TOKEN_COMMA,
    TOKEN_COLON,
    TOKEN_DOT,
    TOKEN_SEMICOLON,

    // Special
    TOKEN_EOF,
    TOKEN_UNKNOWN
};

struct Token {
    TokenType type = TokenType::TOKEN_UNKNOWN;
    std::string text;
    size_t line = 0;
    size_t column = 0;
};

} // namespace daad
