// مولّد آليًا من Docs/Specs/KEYWORDS_REGISTRY.json — لا تحرر يدويًا
// 116 كلمة مفتاحية للغة ض (المسار C++ عالي المستوى)

export interface DhadKeyword { word: string; kind: string; detail: string; doc: string; }
export const DHAD_KEYWORDS: DhadKeyword[] = [
  { word: "صحيح", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: int — الحالة: unified — نوع أساسي موحد." },
  { word: "عشري", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: double — الحالة: unified — نوع أساسي موحد." },
  { word: "منطقي", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: bool — الحالة: unified — نوع أساسي موحد." },
  { word: "حرف", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: char — الحالة: unified — نوع أساسي موحد." },
  { word: "نص", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: std::string — الحالة: unified — نوع أساسي موحد." },
  { word: "ثابت", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: const — الحالة: partial-parser-diff — فرق محلل: JS لها parseConstDecl مستقل، C++ تعالجها كنوع عادي." },
  { word: "فراغ", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: void — الحالة: unified — نوع الإرجاع الافتراضي للدوال في الطرفين." },
  { word: "تلقائي", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: auto — الحالة: unified — استنتاج النوع. JS تستخدمه كنوع افتراضي لـ for-each (dhad-parser.js:767)." },
  { word: "صواب", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: true — الحالة: unified — قيمة منطقية موحدة." },
  { word: "خطأ", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: false — الحالة: unified — قيمة منطقية موحدة." },
  { word: "عدم", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: nullptr — الحالة: unified — القيمة المعدومة. JS sandbox تطبعها عدم (dhad.js:157-160)." },
  { word: "عرّف", kind: "Type", detail: "ض — أنواع البيانات", doc: "المكافئ: typedef — الحالة: partial-parser-diff — فرق: JS تسجله لكن لا تحلله كتعريف نوع." },
  { word: "إذا", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: if — الحالة: partial-syntax-diff — فرق نحوي: JS تسمح بدون أقواس وبدون كتل (جملة مفردة)، C++ تتطلب كتل parseBlock." },
  { word: "اذا", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: if — الحالة: unified — بديل إملائي موحد في الطرفين." },
  { word: "وإلا", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: else — الحالة: partial-syntax-diff — فرق: else-if موجودة في JS فقط." },
  { word: "طالما", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: while — الحالة: unified — حلقة شرطية موحدة. C++ لها parseDoWhile منفصلة تستخدم طالما للذيل (Parser.cpp:835)." },
  { word: "بينما", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: while — الحالة: unified — بديل موحد. ملاحظة تلوين: highlight.js تفتقد بينما (تملك طالما فقط)." },
  { word: "افعل", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: do — الحالة: unified — حلقة لاحقة الشرط موحدة." },
  { word: "لكل", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: for — الحالة: unified — حلقة مزدوجة الشكل في الطرفين (عداد C-style ونطاق for-each عبر في)." },
  { word: "كرر", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: for — الحالة: unified — بديل موحد. ملاحظة تلوين: highlight.js تفتقد كرر." },
  { word: "في", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: for — الحالة: unified — حرف النطاق الموحد." },
  { word: "اختر", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: switch — الحالة: partial-codegen-diff — فرق مولد: C++ يولد if-else للسلاسل النصية، JS تولد switch دائمًا." },
  { word: "حالة", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: case — الحالة: unified — فرع switch موحد." },
  { word: "افتراضي", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: default — الحالة: unified — الفرع الافتراضي موحد." },
  { word: "توقف", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: break — الحالة: unified — كسر الحلقة موحد." },
  { word: "اكسر", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: break — الحالة: unified — بديل موحد." },
  { word: "استمر", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: continue — الحالة: unified — متابعة التكرار موحدة." },
  { word: "تابع", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: continue — الحالة: unified — بديل موحد." },
  { word: "انتقل", kind: "Control", detail: "ض — تحكم التدفق", doc: "المكافئ: goto — الحالة: rejected-by-design — مرفوضة بالتصميم في C++ (لا labels في اللغة). JS بلا قرار صريح — وحد الرفض." },
  { word: "س", kind: "Variable", detail: "ض — محاور", doc: "المكافئ: x — الحالة: partial-divergent — محور الإحداثيات. ملاحظة دقيقة: فرع C++ المسمى x ميت (parsePrimary:436-458 يسبقه ويعيد Variable(س)) — التسمية x تحدث فقط في JS. تلوين highlight.js يفتقد س/ص." },
  { word: "ص", kind: "Variable", detail: "ض — محاور", doc: "المكافئ: y — الحالة: partial-divergent — كملاحظة س أعلاه." },
  { word: "صنف", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: class — الحالة: unified-behavior-diff-shape — الفئة موحدة سلوكيًا، مختلفة البنية (C++ حقيقية، JS نماذج أولية)." },
  { word: "فئة", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: class — الحالة: unified — بديل موحد. ملاحظة تلوين: highlight.js تفتقد فئة." },
  { word: "هيكل", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: struct — الحالة: cpp-broken — فجوة C++ مثبتة: الأعضاء مفقودة في AST أصلًا — تحتاج توسيع StructDeclAST." },
  { word: "تعداد", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: enum — الحالة: unified — التعداد موحد سلوكيًا." },
  { word: "واجهة", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: class — الحالة: registered-no-impl — مسجلة في الطرفين بلا تنفيذ واجهات فعلي — قيد موثق." },
  { word: "نطاق", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: namespace — الحالة: unified — النطاق موحد." },
  { word: "عام", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: public — الحالة: unified — محدد الوصول موحد." },
  { word: "خاص", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: private — الحالة: unified — محدد الوصول موحد." },
  { word: "محمي", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: protected — الحالة: unified — محدد الوصول موحد." },
  { word: "يرث", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: public — الحالة: js-only-impl — الوراثة تعمل في JS، غير مثبتة في C++ المقروء — تحتاج اختبارًا متقاطعًا." },
  { word: "ذاتي", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: this — الحالة: unified — الإشارة الذاتية موحدة." },
  { word: "هذا", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: this — الحالة: unified — بديل موحد." },
  { word: "الأصل", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ:  — الحالة: registered-no-impl — مسجلة بلا تنفيذ super فعلي في الطرفين — قيد موثق." },
  { word: "مجرّد", kind: "Class", detail: "ض — الأصناف والكائنات", doc: "المكافئ: virtual — الحالة: registered-no-impl — مسجلة بلا تجريد فعلي. ملاحظة تلوين: highlight.js تكتبها مجرد بدون شدة (خطأ إملائي — لا تطابق)." },
  { word: "دالة", kind: "Function", detail: "ض — الدوال والذاكرة", doc: "المكافئ: (خاص — metadata فقط، Parser يعالجها) — الحالة: unified — تعريف الدوال موحد مع فروق شكلية (C++ أقواس اختيارية وأسماء مركبة بمسافات؛ JS قيم افتراضية وawait)." },
  { word: "ارجع", kind: "Function", detail: "ض — الدوال والذاكرة", doc: "المكافئ: return — الحالة: unified — الإرجاع موحد (بلا قيمة مسموح في الطرفين)." },
  { word: "جديد", kind: "Function", detail: "ض — الدوال والذاكرة", doc: "المكافئ: new — الحالة: unified — التخصيص موحد تعبيريًا. C++ يتتبع new/delete للتحذير (CodeGen.cpp:49-55)." },
  { word: "احذف", kind: "Function", detail: "ض — الدوال والذاكرة", doc: "المكافئ: delete — الحالة: unified — التحرير موحد." },
  { word: "مؤشر", kind: "Function", detail: "ض — الدوال والذاكرة", doc: "المكافئ: * — الحالة: partial-no-deref — نوع المؤشر مسجل في الطرفين؛ لا يوجد إلغاء مرجعية * أحادي في C++ (parseUnary:364-380 بلا *)." },
  { word: "مرجع", kind: "Function", detail: "ض — الدوال والذاكرة", doc: "المكافئ: & — الحالة: cpp-lexer-gap — فجوة lexer في C++: لا توكن & مفردة (Lexer.cpp:95-96 فقط &&) — النوع مسجل لكن لا يمكن كتابة &x." },
  { word: "ساكن", kind: "Function", detail: "ض — الدوال والذاكرة", doc: "المكافئ: static — الحالة: partial — مسجلة؛ السكون الصفي يعمل في JS داخل الصفوف فقط." },
  { word: "مضمن", kind: "Function", detail: "ض — الدوال والذاكرة", doc: "المكافئ: inline — الحالة: registered-no-impl — مسجلة بلا أثر تنفيذي مثبت — قيد." },
  { word: "خارجي", kind: "Function", detail: "ض — الدوال والذاكرة", doc: "المكافئ: extern — الحالة: registered-no-impl — مسجلة بلا تنفيذ — قيد." },
  { word: "قالب", kind: "Function", detail: "ض — الدوال والذاكرة", doc: "المكافئ: template — الحالة: partial-semantic-diff — فرق دلالي مشروع: compile-time في C++ مقابل محو في JS." },
  { word: "حاول", kind: "Control", detail: "ض — معالجة الأخطاء", doc: "المكافئ: try — الحالة: unified — المحاولة موحدة (try + امسك اختياري + أخيراً اختياري)." },
  { word: "امسك", kind: "Control", detail: "ض — معالجة الأخطاء", doc: "المكافئ: catch — الحالة: unified — الالتقاط موحد (C++ يقيد بـ std::exception)." },
  { word: "أخيراً", kind: "Control", detail: "ض — معالجة الأخطاء", doc: "المكافئ: finally — الحالة: partial-codegen-diff — فرق دلالي مثبت: C++ تنفذ الكتلة دائمًا كمجال عادي (ليست finally حقيقية)، JS صحيحة." },
  { word: "ارمِ", kind: "Control", detail: "ض — معالجة الأخطاء", doc: "المكافئ: throw — الحالة: unified — الرمي موحد." },
  { word: "تأكد", kind: "Control", detail: "ض — معالجة الأخطاء", doc: "المكافئ: assert — الحالة: registered-no-impl — مسجلة بلا عبارة تحقق فعلية في الطرفين — قيد." },
  { word: "استثناء", kind: "Control", detail: "ض — معالجة الأخطاء", doc: "المكافئ: std::exception — الحالة: registered-no-impl — مسجلة كنوع فقط — قيد." },
  { word: "نوع_الـ", kind: "Control", detail: "ض — معالجة الأخطاء", doc: "المكافئ: decltype — الحالة: partial-semantic-diff — فرق دلالي مشروع: compile-time مقابل runtime." },
  { word: "حجم_الـ", kind: "Control", detail: "ض — معالجة الأخطاء", doc: "المكافئ: sizeof — الحالة: partial-semantic-diff — فرق دلالي: حجم C++ مقابل طول JS — وثّق ولا توحد بسذاجة." },
  { word: "زد", kind: "Control", detail: "ض — معالجة الأخطاء", doc: "المكافئ: ++ — الحالة: unified — الزيادة موحدة (سكر +=1)." },
  { word: "انقص", kind: "Control", detail: "ض — معالجة الأخطاء", doc: "المكافئ: -- — الحالة: unified — النقصان موحد." },
  { word: "تزامن", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: std::mutex — الحالة: registered-no-impl — مسجلة بلا تنفيذ تزامن فعلي — قيد في الطرفين." },
  { word: "انتظر", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: co_await — الحالة: registered-no-impl — مسجلة بلا await فعلي — قيد." },
  { word: "بانتظار", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: co_await — الحالة: registered-no-impl — بديل موحد التسجيل، بلا تنفيذ." },
  { word: "خيط", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: std::thread — الحالة: registered-no-impl — مسجلة بلا خيوط فعلية — التنفيذ في stdlib/.ض فقط." },
  { word: "احجز", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: std::lock_guard — الحالة: registered-no-impl — مسجلة بلا أقفال فعلية — قيد." },
  { word: "مشترك", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: std::shared_ptr — الحالة: registered-no-impl — مسجلة بلا تنفيذ — قيد." },
  { word: "فريد", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: std::unique_ptr — الحالة: registered-no-impl — مسجلة بلا تنفيذ — قيد." },
  { word: "استورد", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: #include — الحالة: unified-noop — متطابق: تُحلل وتُتجاهل تنفيذيًا في الطرفين — خطر صمت موثق." },
  { word: "صدّر", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: export — الحالة: unified-noop — كاستورد أعلاه." },
  { word: "وحدة", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: module — الحالة: registered-no-impl — مسجلة بلا وحدات فعلية — قيد." },
  { word: "بديل", kind: "Module", detail: "ض — الأنظمة المتقدمة", doc: "المكافئ: else if — الحالة: js-only-impl — بديل الشرط يعمل في JS، غير مثبت في C++ المقروء." },
  { word: "طباعة", kind: "Builtin", detail: "ض — الإدخال والإخراج", doc: "المكافئ: daad::runtime::daad_print — الحالة: unified — الطباعة الأساسية موحدة (متعددة الوسائط). ملاحظة تلوين: highlight.js تملك طباعة فقط." },
  { word: "اطبع", kind: "Builtin", detail: "ض — الإدخال والإخراج", doc: "المكافئ: daad::runtime::daad_print — الحالة: unified-verify-parser — بديل موحد التسجيل. ملاحظة تلوين: highlight.js تفتقد اطبع." },
  { word: "ادخل", kind: "Builtin", detail: "ض — الإدخال والإخراج", doc: "المكافئ: (إدخال) — الحالة: partial-arity-diff — فجوة مثبتة: متعدد في JS مقابل مفرد في C++. ملاحظة تلوين: highlight.js تفتقد ادخل." },
  { word: "و", kind: "Operator", detail: "ض — المنطق العربي", doc: "المكافئ: && — الحالة: unified — العطف العربي موحد." },
  { word: "أو", kind: "Operator", detail: "ض — المنطق العربي", doc: "المكافئ: || — الحالة: unified — الفصل العربي موحد." },
  { word: "ليس", kind: "Operator", detail: "ض — المنطق العربي", doc: "المكافئ: ! — الحالة: js-only-registry-gap — أخطر فجوة قاموسية: النفي يعمل في JS ويفشل في C++. الإصلاح: سجل ليس في Keywords.cpp/hpp (انظر HIGH_LEVEL_GAPS.md GAP-K1)." },
  { word: "زر_أمر", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QPushButton — الحالة: registered-parser-gap — مسجلة في الطرفين؛ محللة كودجت في JS فقط؛ بلا توليد Qt فعلي — قيد." },
  { word: "حقل_نص", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QLineEdit — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "قائمة_خيارات", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QComboBox — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "صورة", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QLabel — الحالة: registered-parser-gap — كزر_أمر مع التباس اسمي موثق." },
  { word: "مربع_اختيار", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QCheckBox — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "شريط_تمرير", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QSlider — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "قائمة_منسدلة", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QComboBox — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "لوحة", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QWidget — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "تسمية", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QLabel — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "عمود", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QVBoxLayout — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "صف", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QHBoxLayout — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "شبكة", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QGridLayout — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "شريط_تلوين", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QProgressBar — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "علامة_تبويب", kind: "Widget", detail: "ض — عناصر الواجهات", doc: "المكافئ: QTabWidget — الحالة: registered-parser-gap — كزر_أمر." },
  { word: "حمّل_صورة", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::load — الحالة: js-codegen-broken — مسجلة ومحللة في الطرفين؛ مولد JS مكسور نحويًا (مسافة بدل نقطة) — أولوية إصلاح 1." },
  { word: "ارسم_صورة", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::draw — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "حجم_صورة", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::size — الحالة: js-codegen-broken — فجوة JS مزدوجة: نقطة مكسورة + غياب genExpr للتعبيرات (س = حجم_صورة(p) تفشل)." },
  { word: "احفظ_صورة", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::save — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "قص_صورة", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::crop — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "غيّر_حجم", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::resize — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "لف_صورة", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::rotate — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "قلب_صورة", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::flip — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "شفافية", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::opacity — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "فلتر", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::filter — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "تراكب", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::overlay — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "خلفية", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::background — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "بكسل", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::pixel — الحالة: js-codegen-broken — كحجم_صورة: نقطة مكسورة (:1019) + غياب genExpr." },
  { word: "ارسم", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::drawShape — الحالة: unified — الصحيحة: النقطة موجودة. تُستخدم أيضًا كاسم دالة عامة عند ( (Parser.cpp:125-130)." },
  { word: "ملء", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::fill — الحالة: unified — صحيحة كـ ارسم." },
  { word: "مستطيل", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::rectangle — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "دائرة", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::circle — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "خط", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::line — الحالة: js-codegen-broken — كحمّل_صورة." },
  { word: "نص_على_لوحة", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::text — الحالة: unified-verify-escape — صحيحة النقطة في JS؛ C++ يطبع النص بلا escapeString — قيد." },
  { word: "مسح", kind: "Library", detail: "ض — معالجة الصور", doc: "المكافئ: daad::image::clear — الحالة: js-codegen-broken — كحمّل_صورة. تُستخدم أيضًا كاسم دالة عامة عند ( (Parser.cpp:125-130)." },
];
export const DHAD_KEYWORD_COUNT = DHAD_KEYWORDS.length;
