# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $192, %rsp
.L_main_entry:
  leaq -40(%rbp), %rax
  movq %rax, -8(%rbp)
  movq -8(%rbp), %rax
  movq $20, (%rax)
  movq -8(%rbp), %rax
  movq (%rax), %rax
  movq %rax, -16(%rbp)
  movq -16(%rbp), %rax
  cmpq $18, %rax
  setge %al
  movzbl %al, %eax
  movq %rax, -24(%rbp)
  movq -24(%rbp), %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_merge
.L_main_if_then:
  movq $1, %rax
  jmp .L_main_epilogue
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $192, %rsp
  leave
  ret


# ── مساعد الطباعة: rdi = العدد ──
__daad_print_int:
  pushq %rbp
  movq %rsp, %rbp
  subq $48, %rsp
  movq %rdi, %rax
  leaq 31(%rsp), %r8
  movq %r8, %rsi
  movb $10, (%rsi)
  xorq %r9, %r9
  testq %rax, %rax
  jns .Ldpi_pos
  negq %rax
  movq $1, %r9
.Ldpi_pos:
  testq %rax, %rax
  jnz .Ldpi_loop
  decq %rsi
  movb $48, (%rsi)
  jmp .Ldpi_sign
.Ldpi_loop:
  testq %rax, %rax
  jz .Ldpi_sign
  xorq %rdx, %rdx
  movq $10, %rcx
  divq %rcx
  addq $48, %rdx
  decq %rsi
  movb %dl, (%rsi)
  jmp .Ldpi_loop
.Ldpi_sign:
  testq %r9, %r9
  jz .Ldpi_write
  decq %rsi
  movb $45, (%rsi)
.Ldpi_write:
  movq %r8, %rdx
  subq %rsi, %rdx
  incq %rdx
  movq $1, %rax
  movq $1, %rdi
  syscall
  leave
  ret

# ── مساعد الإدخال: يقرأ عددًا من stdin → rax ──
__daad_read_int:
  pushq %rbp
  movq %rsp, %rbp
  subq $256, %rsp
  leaq -256(%rbp), %rsi
  movq $0, %rax
  movq $0, %rdi
  movq $255, %rdx
  syscall
  leaq -256(%rbp), %rsi
  xorq %rax, %rax
  xorq %r9, %r9
  movb (%rsi), %cl
  cmpb $45, %cl
  jne .Ldri_digits
  movq $1, %r9
  incq %rsi
  movb (%rsi), %cl
.Ldri_digits:
  testb %cl, %cl
  jz .Ldri_sign
  cmpb $10, %cl
  je .Ldri_sign
  cmpb $32, %cl
  je .Ldri_sign
  subb $48, %cl
  movzbl %cl, %ecx
  imulq $10, %rax
  addq %rcx, %rax
  incq %rsi
  movb (%rsi), %cl
  jmp .Ldri_digits
.Ldri_sign:
  testq %r9, %r9
  jz .Ldri_done
  negq %rax
.Ldri_done:
  leave
  ret

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
