# Generated by DAAD Compiler
.text
.globl مضروب
مضروب:
  pushq %rbp
  movq %rsp, %rbp
  subq $240, %rsp
  movq %rdi, -8(%rbp)
.L_مضروب_entry:
  leaq -88(%rbp), %rax
  movq %rax, -16(%rbp)
  movq -16(%rbp), %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  movq -16(%rbp), %rax
  movq (%rax), %rax
  movq %rax, -24(%rbp)
  movq -24(%rbp), %rax
  cmpq $1, %rax
  setle %al
  movzbl %al, %eax
  movq %rax, -32(%rbp)
  movq -32(%rbp), %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_مضروب_if_then
  jmp .L_مضروب_if_merge
.L_مضروب_if_then:
  movq $1, %rax
  jmp .L_مضروب_epilogue
.L_مضروب_if_merge:
  movq -16(%rbp), %rax
  movq (%rax), %rax
  movq %rax, -40(%rbp)
  movq -16(%rbp), %rax
  movq (%rax), %rax
  movq %rax, -48(%rbp)
  movq -48(%rbp), %rax
  subq $1, %rax
  movq %rax, -56(%rbp)
  subq $64, %rsp
  movq %rdi, 0(%rsp)
  movq %rsi, 8(%rsp)
  movq %rdx, 16(%rsp)
  movq %rsi, 24(%rsp)
  movq %rdx, 32(%rsp)
  movq %rdi, 40(%rsp)
  movq %rdx, 48(%rsp)
  movq %rdi, 56(%rsp)
  movq -56(%rbp), %rdi
  callq مضروب
  movq %rax, -64(%rbp)
  movq 0(%rsp), %rdi
  movq 8(%rsp), %rsi
  movq 16(%rsp), %rdx
  movq 24(%rsp), %rsi
  movq 32(%rsp), %rdx
  movq 40(%rsp), %rdi
  movq 48(%rsp), %rdx
  movq 56(%rsp), %rdi
  addq $64, %rsp
  movq -40(%rbp), %rax
  movq -64(%rbp), %rcx
  imulq %rcx, %rax
  movq %rax, -72(%rbp)
  movq -72(%rbp), %rax
  jmp .L_مضروب_epilogue
.L_مضروب_epilogue:
  addq $240, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  subq $16, %rsp
  movq %rdi, 0(%rsp)
  movq $5, %rdi
  callq مضروب
  movq %rax, -8(%rbp)
  movq 0(%rsp), %rdi
  addq $16, %rsp
  movq -8(%rbp), %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret


# ── مساعد الطباعة: rdi = العدد ──
__daad_print_int:
  pushq %rbp
  movq %rsp, %rbp
  subq $48, %rsp
  movq %rdi, %rax
  leaq 31(%rsp), %r8
  movq %r8, %rsi
  movb $10, (%rsi)
  xorq %r9, %r9
  testq %rax, %rax
  jns .Ldpi_pos
  negq %rax
  movq $1, %r9
.Ldpi_pos:
  testq %rax, %rax
  jnz .Ldpi_loop
  decq %rsi
  movb $48, (%rsi)
  jmp .Ldpi_sign
.Ldpi_loop:
  testq %rax, %rax
  jz .Ldpi_sign
  xorq %rdx, %rdx
  movq $10, %rcx
  divq %rcx
  addq $48, %rdx
  decq %rsi
  movb %dl, (%rsi)
  jmp .Ldpi_loop
.Ldpi_sign:
  testq %r9, %r9
  jz .Ldpi_write
  decq %rsi
  movb $45, (%rsi)
.Ldpi_write:
  movq %r8, %rdx
  subq %rsi, %rdx
  incq %rdx
  movq $1, %rax
  movq $1, %rdi
  syscall
  leave
  ret

# ── مساعد الإدخال: يقرأ عددًا من stdin → rax ──
__daad_read_int:
  pushq %rbp
  movq %rsp, %rbp
  subq $256, %rsp
  leaq -256(%rbp), %rsi
  movq $0, %rax
  movq $0, %rdi
  movq $255, %rdx
  syscall
  leaq -256(%rbp), %rsi
  xorq %rax, %rax
  xorq %r9, %r9
  movb (%rsi), %cl
  cmpb $45, %cl
  jne .Ldri_digits
  movq $1, %r9
  incq %rsi
  movb (%rsi), %cl
.Ldri_digits:
  testb %cl, %cl
  jz .Ldri_sign
  cmpb $10, %cl
  je .Ldri_sign
  cmpb $32, %cl
  je .Ldri_sign
  subb $48, %cl
  movzbl %cl, %ecx
  imulq $10, %rax
  addq %rcx, %rax
  incq %rsi
  movb (%rsi), %cl
  jmp .Ldri_digits
.Ldri_sign:
  testq %r9, %r9
  jz .Ldri_done
  negq %rax
.Ldri_done:
  leave
  ret

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
