# Generated by DAAD Compiler
.text
.globl اجمع7
اجمع7:
  pushq %rbp
  movq %rsp, %rbp
  subq $384, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rdx, -24(%rbp)
  movq %rcx, -32(%rbp)
  movq %r8, -40(%rbp)
  movq %r9, -48(%rbp)
.L_اجمع7_entry:
  leaq -232(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -240(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -248(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq -24(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -256(%rbp), %rax
  movq %rax, %rcx
  movq %rcx, %rax
  movq -32(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -264(%rbp), %rax
  movq %rax, %r8
  movq %r8, %rax
  movq -40(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -272(%rbp), %rax
  movq %rax, %r9
  movq %r9, %rax
  movq -48(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -280(%rbp), %rax
  movq %rax, %rax
  movq %rax, %rax
  movq -56(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r10
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %r10, %rax
  addq -128(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -144(%rbp), %rax
  movq %rax, %rdx
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -160(%rbp), %rax
  movq %rax, %rsi
  movq %r8, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -176(%rbp), %rax
  movq %rax, %rdx
  movq %r9, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -192(%rbp), %rax
  movq %rax, %rsi
  movq %rax, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -208(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  jmp .L_اجمع7_epilogue
.L_اجمع7_epilogue:
  addq $384, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  leaq -32(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq $1, %rdi
  movq $2, %rsi
  movq $3, %rdx
  movq $4, %rcx
  movq $5, %r8
  movq $6, %r9
  callq اجمع7
  movq %rax, %rsi
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rsi
  movq %rdi, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
