# Generated by DAAD Compiler
.text
.globl اجمع
اجمع:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_اجمع_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_اجمع_epilogue
.L_اجمع_epilogue:
  addq $224, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
