# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $192, %rsp
.L_main_entry:
  leaq -40(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $10, (%rax)
  leaq -48(%rbp), %rax
  movq %rax, %rdi
  # malloc
  movq $8, %rdi
  callq malloc
  movq %rax, %rsi
  movq %rdi, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $192, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
