# Generated by DAAD Compiler
.text

# ── مساعد الطباعة: rdi = العدد ──
__daad_print_int:
  pushq %rbp
  movq %rsp, %rbp
  subq $48, %rsp
  movq %rdi, %rax
  leaq 31(%rsp), %r8
  movq %r8, %rsi
  movb $10, (%rsi)
  xorq %r9, %r9
  testq %rax, %rax
  jns .Ldpi_pos
  negq %rax
  movq $1, %r9
.Ldpi_pos:
  testq %rax, %rax
  jnz .Ldpi_loop
  decq %rsi
  movb $48, (%rsi)
  jmp .Ldpi_sign
.Ldpi_loop:
  testq %rax, %rax
  jz .Ldpi_sign
  xorq %rdx, %rdx
  movq $10, %rcx
  divq %rcx
  addq $48, %rdx
  decq %rsi
  movb %dl, (%rsi)
  jmp .Ldpi_loop
.Ldpi_sign:
  testq %r9, %r9
  jz .Ldpi_write
  decq %rsi
  movb $45, (%rsi)
.Ldpi_write:
  movq %r8, %rdx
  subq %rsi, %rdx
  incq %rdx
  movq $1, %rax
  movq $1, %rdi
  syscall
  leave
  ret

# ── مساعد الإدخال: يقرأ عددًا من stdin → rax ──
__daad_read_int:
  pushq %rbp
  movq %rsp, %rbp
  subq $256, %rsp
  # sys_read(0, buf, 255)
  leaq -256(%rbp), %rsi
  movq $0, %rax
  movq $0, %rdi
  movq $255, %rdx
  syscall
  # rax = عدد البايتات المقروءة — نحول المحتوى إلى صحيح
  leaq -256(%rbp), %rsi
  xorq %rax, %rax
  xorq %r9, %r9
  movb (%rsi), %cl
  cmpb $45, %cl
  jne .Ldri_digits
  movq $1, %r9
  incq %rsi
  movb (%rsi), %cl
.Ldri_digits:
  testb %cl, %cl
  jz .Ldri_sign
  cmpb $10, %cl
  je .Ldri_sign
  cmpb $32, %cl
  je .Ldri_sign
  subb $48, %cl
  movzbl %cl, %ecx
  imulq $10, %rax
  addq %rcx, %rax
  incq %rsi
  movb (%rsi), %cl
  jmp .Ldri_digits
.Ldri_sign:
  testq %r9, %r9
  jz .Ldri_done
  negq %rax
.Ldri_done:
  leave
  ret

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
