# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $208, %rsp
.L_main_entry:
  leaq -56(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $5, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  cmpq $10, %rax
  setg %al
  movzbl %al, %eax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_else
.L_main_if_then:
  movq $1, %rax
  jmp .L_main_epilogue
.L_main_if_else:
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  cmpq $3, %rax
  setg %al
  movzbl %al, %eax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_else
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_if_then:
  movq $2, %rax
  jmp .L_main_epilogue
.L_main_if_else:
  movq $3, %rax
  jmp .L_main_epilogue
.L_main_if_merge:
  jmp .L_main_if_merge
.L_main_epilogue:
  addq $208, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
