# Generated by DAAD Compiler
.text
.globl noop
noop:
  pushq %rbp
  movq %rsp, %rbp
  subq $192, %rsp
  movq %rdi, -8(%rbp)
.L_noop_entry:
  leaq -40(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_noop_epilogue
.L_noop_epilogue:
  addq $192, %rsp
  leave
  ret

.globl identity
identity:
  pushq %rbp
  movq %rsp, %rbp
  subq $192, %rsp
  movq %rdi, -8(%rbp)
.L_identity_entry:
  leaq -48(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rdi, -16(%rbp)
  movq %rsi, -24(%rbp)
  movq %rdi, -32(%rbp)
  movq -24(%rbp), %rdi
  callq noop
  movq %rax, %rdi
  movq -16(%rbp), %rdi
  movq -24(%rbp), %rsi
  movq -32(%rbp), %rdi
  movq %rdi, %rax
  jmp .L_identity_epilogue
.L_identity_epilogue:
  addq $192, %rsp
  leave
  ret

.globl double
double:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
.L_double_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rdi, -16(%rbp)
  movq %rsi, -24(%rbp)
  movq %rdx, -32(%rbp)
  movq %rsi, -40(%rbp)
  movq %rdi, -48(%rbp)
  movq %rsi, -56(%rbp)
  movq -24(%rbp), %rdi
  callq identity
  movq %rax, %rdx
  movq -16(%rbp), %rdi
  movq -24(%rbp), %rsi
  movq -32(%rbp), %rdx
  movq -40(%rbp), %rsi
  movq -48(%rbp), %rdi
  movq -56(%rbp), %rsi
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rdi, -16(%rbp)
  movq %rsi, -24(%rbp)
  movq %rdx, -32(%rbp)
  movq %rsi, -40(%rbp)
  movq %rdi, -48(%rbp)
  movq %rsi, -56(%rbp)
  movq -40(%rbp), %rdi
  callq identity
  movq %rax, %rdi
  movq -16(%rbp), %rdi
  movq -24(%rbp), %rsi
  movq -32(%rbp), %rdx
  movq -40(%rbp), %rsi
  movq -48(%rbp), %rdi
  movq -56(%rbp), %rsi
  movq %rdx, %rax
  addq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_double_epilogue
.L_double_epilogue:
  addq $224, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  movq %rdi, -8(%rbp)
  movq $5, %rdi
  callq double
  movq %rax, %rdi
  movq -8(%rbp), %rdi
  movq %rdi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
