# Generated by DAAD Compiler
.text
.globl add6
add6:
  pushq %rbp
  movq %rsp, %rbp
  subq $352, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rdx, -24(%rbp)
  movq %rcx, -32(%rbp)
  movq %r8, -40(%rbp)
  movq %r9, -48(%rbp)
.L_add6_entry:
  leaq -200(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -208(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -216(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq -24(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -224(%rbp), %rax
  movq %rax, %rcx
  movq %rcx, %rax
  movq -32(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -232(%rbp), %rax
  movq %rax, %r8
  movq %r8, %rax
  movq -40(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -240(%rbp), %rax
  movq %rax, %r9
  movq %r9, %rax
  movq -48(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rax
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rax, %rax
  addq -112(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -128(%rbp), %rax
  movq %rax, %rdx
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -144(%rbp), %rax
  movq %rax, %rsi
  movq %r8, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -160(%rbp), %rax
  movq %rax, %rdx
  movq %r9, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -176(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_add6_epilogue
.L_add6_epilogue:
  addq $352, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  movq %rdi, -8(%rbp)
  movq $1, %rdi
  movq $2, %rsi
  movq $3, %rdx
  movq $4, %rcx
  movq $5, %r8
  movq $6, %r9
  callq add6
  movq %rax, %rdi
  movq -8(%rbp), %rdi
  movq %rdi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
