# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $256, %rsp
.L_main_entry:
  leaq -104(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $10, (%rax)
  leaq -112(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $20, (%rax)
  leaq -120(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $30, (%rax)
  leaq -128(%rbp), %rax
  movq %rax, %rcx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %r8, %rax
  addq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -64(%rbp), %rax
  movq %rax, %rdx
  movq %rcx, %rax
  movq %rdx, %rcx
  movq %rcx, (%rax)
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  cmpq $60, %rax
  sete %al
  movzbl %al, %eax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_else
.L_main_if_then:
  movq $1, %rax
  jmp .L_main_epilogue
.L_main_if_else:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $256, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
