# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $272, %rsp
.L_main_entry:
  leaq -128(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $2, (%rax)
  leaq -136(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $3, (%rax)
  leaq -144(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $4, (%rax)
  leaq -152(%rbp), %rax
  movq %rax, %rcx
  movq %rcx, %rax
  movq $5, (%rax)
  leaq -160(%rbp), %rax
  movq %rax, %r8
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r9
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %r9, %rax
  imulq -56(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  imulq -80(%rbp), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  addq -88(%rbp), %rax
  movq %rax, %rdi
  movq %r8, %rax
  movq %rdi, %rcx
  movq %rcx, (%rax)
  movq %r8, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  cmpq $26, %rax
  sete %al
  movzbl %al, %eax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_else
.L_main_if_then:
  movq $1, %rax
  jmp .L_main_epilogue
.L_main_if_else:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $272, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
