# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $352, %rsp
.L_main_entry:
  leaq -200(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $1, (%rax)
  leaq -208(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $2, (%rax)
  leaq -216(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $3, (%rax)
  leaq -224(%rbp), %rax
  movq %rax, %rcx
  movq %rcx, %rax
  movq $4, (%rax)
  leaq -232(%rbp), %rax
  movq %rax, %r8
  movq %r8, %rax
  movq $5, (%rax)
  leaq -240(%rbp), %rax
  movq %rax, %r9
  movq %r9, %rax
  movq $6, (%rax)
  leaq -248(%rbp), %rax
  movq %rax, %rax
  movq %rax, %rax
  movq $7, (%rax)
  leaq -256(%rbp), %rax
  movq %rax, %r10
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r11
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %r11, %rax
  addq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -96(%rbp), %rax
  movq %rax, %rdx
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -112(%rbp), %rax
  movq %rax, %rsi
  movq %r8, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -128(%rbp), %rax
  movq %rax, %rdx
  movq %r9, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -144(%rbp), %rax
  movq %rax, %rsi
  movq %rax, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -160(%rbp), %rax
  movq %rax, %rdx
  movq %r10, %rax
  movq %rdx, %rcx
  movq %rcx, (%rax)
  movq %r10, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  cmpq $28, %rax
  sete %al
  movzbl %al, %eax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_else
.L_main_if_then:
  movq $1, %rax
  jmp .L_main_epilogue
.L_main_if_else:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $352, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
