# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $304, %rsp
.L_main_entry:
  leaq -152(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $10, (%rax)
  leaq -160(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $20, (%rax)
  leaq -168(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $30, (%rax)
  leaq -176(%rbp), %rax
  movq %rax, %rcx
  movq %rcx, %rax
  movq $40, (%rax)
  leaq -184(%rbp), %rax
  movq %rax, %r8
  movq %r8, %rax
  movq $50, (%rax)
  leaq -192(%rbp), %rax
  movq %rax, %r9
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rax
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rax, %rax
  addq -64(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -80(%rbp), %rax
  movq %rax, %rdx
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -96(%rbp), %rax
  movq %rax, %rsi
  movq %r8, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -112(%rbp), %rax
  movq %rax, %rdx
  movq %r9, %rax
  movq %rdx, %rcx
  movq %rcx, (%rax)
  movq %r9, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  cmpq $150, %rax
  sete %al
  movzbl %al, %eax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_else
.L_main_if_then:
  movq $1, %rax
  jmp .L_main_epilogue
.L_main_if_else:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $304, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
