# Generated by DAAD Compiler
.text
.globl add
add:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_add_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_add_epilogue
.L_add_epilogue:
  addq $224, %rsp
  leave
  ret

.globl mul
mul:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_mul_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  imulq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_mul_epilogue
.L_mul_epilogue:
  addq $224, %rsp
  leave
  ret

.globl compute
compute:
  pushq %rbp
  movq %rsp, %rbp
  subq $320, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rdx, -24(%rbp)
.L_compute_entry:
  leaq -176(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -184(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -192(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq -24(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -200(%rbp), %rax
  movq %rax, %rcx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %r8, %rax
  addq -72(%rbp), %rax
  movq %rax, %rsi
  movq %rcx, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  leaq -208(%rbp), %rax
  movq %rax, %rdi
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  imulq -104(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq %rdx, %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  cmpq $100, %rax
  setg %al
  movzbl %al, %eax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_compute_if_then
  jmp .L_compute_if_else
.L_compute_if_then:
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rdi, -32(%rbp)
  movq %rsi, -40(%rbp)
  movq %rdx, -48(%rbp)
  movq %rcx, -56(%rbp)
  movq %r8, -64(%rbp)
  movq %rdi, -72(%rbp)
  movq %rsi, -80(%rbp)
  movq %rdi, -88(%rbp)
  movq %rsi, -96(%rbp)
  movq %rcx, -104(%rbp)
  movq %rdx, -112(%rbp)
  movq %rsi, -120(%rbp)
  movq %rdx, -128(%rbp)
  movq %rsi, -136(%rbp)
  movq %rdx, -144(%rbp)
  movq %rsi, -152(%rbp)
  movq %rdi, -160(%rbp)
  movq -136(%rbp), %rdi
  movq $1, %rsi
  callq add
  movq %rax, %rdx
  movq -32(%rbp), %rdi
  movq -40(%rbp), %rsi
  movq -48(%rbp), %rdx
  movq -56(%rbp), %rcx
  movq -64(%rbp), %r8
  movq -72(%rbp), %rdi
  movq -80(%rbp), %rsi
  movq -88(%rbp), %rdi
  movq -96(%rbp), %rsi
  movq -104(%rbp), %rcx
  movq -112(%rbp), %rdx
  movq -120(%rbp), %rsi
  movq -128(%rbp), %rdx
  movq -136(%rbp), %rsi
  movq -144(%rbp), %rdx
  movq -152(%rbp), %rsi
  movq -160(%rbp), %rdi
  movq %rdx, %rax
  jmp .L_compute_epilogue
.L_compute_if_else:
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rdi, -32(%rbp)
  movq %rsi, -40(%rbp)
  movq %rdx, -48(%rbp)
  movq %rcx, -56(%rbp)
  movq %r8, -64(%rbp)
  movq %rdi, -72(%rbp)
  movq %rsi, -80(%rbp)
  movq %rdi, -88(%rbp)
  movq %rsi, -96(%rbp)
  movq %rcx, -104(%rbp)
  movq %rdx, -112(%rbp)
  movq %rsi, -120(%rbp)
  movq %rdx, -128(%rbp)
  movq %rsi, -136(%rbp)
  movq %rdx, -144(%rbp)
  movq %rsi, -152(%rbp)
  movq %rdi, -160(%rbp)
  movq -152(%rbp), %rdi
  movq $2, %rsi
  callq mul
  movq %rax, %rdi
  movq -32(%rbp), %rdi
  movq -40(%rbp), %rsi
  movq -48(%rbp), %rdx
  movq -56(%rbp), %rcx
  movq -64(%rbp), %r8
  movq -72(%rbp), %rdi
  movq -80(%rbp), %rsi
  movq -88(%rbp), %rdi
  movq -96(%rbp), %rsi
  movq -104(%rbp), %rcx
  movq -112(%rbp), %rdx
  movq -120(%rbp), %rsi
  movq -128(%rbp), %rdx
  movq -136(%rbp), %rsi
  movq -144(%rbp), %rdx
  movq -152(%rbp), %rsi
  movq -160(%rbp), %rdi
  movq %rdi, %rax
  jmp .L_compute_epilogue
.L_compute_if_merge:
  movq $0, %rax
  jmp .L_compute_epilogue
.L_compute_epilogue:
  addq $320, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  movq %rdi, -8(%rbp)
  movq $3, %rdi
  movq $4, %rsi
  movq $5, %rdx
  callq compute
  movq %rax, %rdi
  movq -8(%rbp), %rdi
  movq %rdi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
