# Generated by DAAD Compiler
.text
.globl add
add:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_add_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_add_epilogue
.L_add_epilogue:
  addq $224, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $240, %rsp
.L_main_entry:
  leaq -88(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $10, (%rax)
  leaq -96(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $20, (%rax)
  leaq -104(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rcx, %rax
  addq -40(%rbp), %rax
  movq %rax, %rsi
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rdx, -24(%rbp)
  movq %rcx, -32(%rbp)
  movq %rdi, -40(%rbp)
  movq %rsi, -48(%rbp)
  movq %rdi, -56(%rbp)
  movq %rdi, -64(%rbp)
  movq %rsi, -72(%rbp)
  movq -48(%rbp), %rdi
  movq $30, %rsi
  callq add
  movq %rax, %rdi
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rsi
  movq -24(%rbp), %rdx
  movq -32(%rbp), %rcx
  movq -40(%rbp), %rdi
  movq -48(%rbp), %rsi
  movq -56(%rbp), %rdi
  movq -64(%rbp), %rdi
  movq -72(%rbp), %rsi
  movq %rdx, %rax
  movq %rdi, %rcx
  movq %rcx, (%rax)
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  cmpq $60, %rax
  sete %al
  movzbl %al, %eax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_else
.L_main_if_then:
  movq $1, %rax
  jmp .L_main_epilogue
.L_main_if_else:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $240, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
