# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
.L_main_entry:
  leaq -80(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $7, (%rax)
  leaq -88(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $3, (%rax)
  leaq -96(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rcx, %rax
  addq -40(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  cmpq $10, %rax
  sete %al
  movzbl %al, %eax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_if_then
  jmp .L_main_if_else
.L_main_if_then:
  movq $1, %rax
  jmp .L_main_epilogue
.L_main_if_else:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_if_merge:
  movq $0, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $224, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
