# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $48, %rsp
.L_main_entry:
  leaq -8(%rbp), %rax
  movq $100, (%rax)
  leaq -16(%rbp), %rbx
  movq $200, (%rbx)
  leaq -24(%rbp), %rcx
  movq (%rax), %rdx
  movq (%rbx), %rsi
  movq %rdx, %rdi
  addq %rsi, %rdi
  movq %rdi, (%rcx)
  leaq -32(%rbp), %r8
  movq (%rcx), %r9
  movq %r9, %rax
  imulq $3, %rax
  movq %rax, %r10
  movq %r10, (%r8)
  leaq -40(%rbp), %r11
  movq (%r8), %r12
  movq %r12, %r13
  subq $50, %r13
  movq %r13, (%r11)
  movq (%r11), %r14
  movq %r14, %rax
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
