# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $272, %rsp
.L_main_entry:
  leaq -120(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $100, (%rax)
  leaq -128(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $200, (%rax)
  leaq -136(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rcx, %rax
  addq -40(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  leaq -144(%rbp), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  imulq $3, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq %rdx, %rcx
  movq %rcx, (%rax)
  leaq -152(%rbp), %rax
  movq %rax, %rsi
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  subq $50, %rax
  movq %rax, %rdi
  movq %rsi, %rax
  movq %rdi, %rcx
  movq %rcx, (%rax)
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $272, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
