# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $272, %rsp
.L_main_entry:
  leaq -120(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $1, (%rax)
  leaq -128(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $2, (%rax)
  leaq -136(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $3, (%rax)
  leaq -144(%rbp), %rax
  movq %rax, %rcx
  movq %rcx, %rax
  movq $4, (%rax)
  leaq -152(%rbp), %rax
  movq %rax, %r8
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r9
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %r9, %rax
  addq -56(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -72(%rbp), %rax
  movq %rax, %rdx
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -88(%rbp), %rax
  movq %rax, %rsi
  movq %r8, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  movq %r8, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $272, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
