# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $48, %rsp
.L_main_entry:
  leaq -8(%rbp), %rax
  movq $1, (%rax)
  leaq -16(%rbp), %rbx
  movq $2, (%rbx)
  leaq -24(%rbp), %rcx
  movq $3, (%rcx)
  leaq -32(%rbp), %rdx
  movq $4, (%rdx)
  leaq -40(%rbp), %rsi
  movq (%rax), %rdi
  movq (%rbx), %r8
  movq %rdi, %r9
  addq %r8, %r9
  movq (%rcx), %r10
  movq %r9, %r11
  addq %r10, %r11
  movq (%rdx), %r12
  movq %r11, %r13
  addq %r12, %r13
  movq %r13, (%rsi)
  movq (%rsi), %r14
  movq %r14, %rax
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
