# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  leaq -24(%rbp), %rax
  movq %rax, %rdi
  movq $3, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
