# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $208, %rsp
.L_main_entry:
  leaq -64(%rbp), %rax
  movq %rax, %rdi
  leaq -72(%rbp), %rax
  movq %rax, %rsi
  leaq -80(%rbp), %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rcx, %rax
  addq -40(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq %rsi, %rcx
  movq %rcx, (%rax)
  movq $3, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $208, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
