# Generated by DAAD Compiler
.text
.globl f1
f1:
  pushq %rbp
  movq %rsp, %rbp
  subq $192, %rsp
  movq %rdi, -8(%rbp)
.L_f1_entry:
  leaq -48(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  addq $1, %rax
  movq %rax, %rdi
  movq %rdi, %rax
  jmp .L_f1_epilogue
.L_f1_epilogue:
  addq $192, %rsp
  leave
  ret

.globl f2
f2:
  pushq %rbp
  movq %rsp, %rbp
  subq $208, %rsp
  movq %rdi, -8(%rbp)
.L_f2_entry:
  leaq -56(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rdi, -16(%rbp)
  movq %rsi, -24(%rbp)
  movq %rdi, -32(%rbp)
  movq %rsi, -40(%rbp)
  movq -24(%rbp), %rdi
  callq f1
  movq %rax, %rdi
  movq -16(%rbp), %rdi
  movq -24(%rbp), %rsi
  movq -32(%rbp), %rdi
  movq -40(%rbp), %rsi
  movq %rdi, %rax
  addq $10, %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_f2_epilogue
.L_f2_epilogue:
  addq $208, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq $5, %rdi
  callq f1
  movq %rax, %rdi
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rsi
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq -8(%rbp), %rdi
  callq f2
  movq %rax, %rsi
  movq -8(%rbp), %rdi
  movq -16(%rbp), %rsi
  movq %rsi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
