# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $32, %rsp
.L_main_entry:
  leaq -8(%rbp), %rax
  movq $2, (%rax)
  leaq -16(%rbp), %rbx
  movq (%rax), %rcx
  movq %rcx, %rdx
  addq $3, %rdx
  movq %rdx, (%rbx)
  leaq -24(%rbp), %rsi
  movq (%rbx), %rdi
  movq %rdi, %r8
  movq $2, %rcx
  shlq %cl, %r8
  movq %r8, (%rsi)
  movq (%rsi), %r9
  movq %r9, %rax
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
