# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $240, %rsp
.L_main_entry:
  leaq -96(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $10, (%rax)
  leaq -104(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq $20, (%rax)
  leaq -112(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $30, (%rax)
  leaq -120(%rbp), %rax
  movq %rax, %rcx
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %r8
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %r8, %rax
  addq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rsi, %rax
  addq -64(%rbp), %rax
  movq %rax, %rdx
  movq %rcx, %rax
  movq %rdx, %rcx
  movq %rcx, (%rax)
  movq %rcx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $240, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
