# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $32, %rsp
.L_main_entry:
  leaq -8(%rbp), %rax
  movq $10, (%rax)
  leaq -16(%rbp), %rbx
  movq $20, (%rbx)
  leaq -24(%rbp), %rcx
  movq $30, (%rcx)
  leaq -32(%rbp), %rdx
  movq (%rax), %rsi
  movq (%rbx), %rdi
  movq %rsi, %r8
  addq %rdi, %r8
  movq (%rcx), %r9
  movq %r8, %r10
  addq %r9, %r10
  movq %r10, (%rdx)
  movq (%rdx), %r11
  movq %r11, %rax
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
