# Generated by DAAD Compiler
.text
.globl is_even
is_even:
  pushq %rbp
  movq %rsp, %rbp
  subq $192, %rsp
  movq %rdi, -8(%rbp)
.L_is_even_entry:
  leaq -48(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  cmpq $0, %rax
  sete %al
  movzbl %al, %eax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_is_even_if_then
  jmp .L_is_even_if_else
.L_is_even_if_then:
  movq $1, %rax
  jmp .L_is_even_epilogue
.L_is_even_if_else:
  movq $0, %rax
  jmp .L_is_even_epilogue
.L_is_even_if_merge:
  movq $0, %rax
  jmp .L_is_even_epilogue
.L_is_even_epilogue:
  addq $192, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  movq %rdi, -8(%rbp)
  movq $4, %rdi
  callq is_even
  movq %rax, %rdi
  movq -8(%rbp), %rdi
  movq %rdi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
