# Generated by DAAD Compiler
.text
.globl add
add:
  pushq %rbp
  movq %rsp, %rbp
  subq $224, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
.L_add_entry:
  leaq -72(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -80(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rdx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdx, %rax
  addq -48(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_add_epilogue
.L_add_epilogue:
  addq $224, %rsp
  leave
  ret

.globl mul_add
mul_add:
  pushq %rbp
  movq %rsp, %rbp
  subq $256, %rsp
  movq %rdi, -8(%rbp)
  movq %rsi, -16(%rbp)
  movq %rdx, -24(%rbp)
.L_mul_add_entry:
  leaq -104(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq -8(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -112(%rbp), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  movq -16(%rbp), %rcx
  movq %rcx, (%rax)
  leaq -120(%rbp), %rax
  movq %rax, %rdx
  movq %rdx, %rax
  movq -24(%rbp), %rcx
  movq %rcx, (%rax)
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rcx
  movq %rsi, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rcx, %rax
  imulq -64(%rbp), %rax
  movq %rax, %rsi
  movq %rdx, %rax
  movq (%rax), %rax
  movq %rax, %rdi
  movq %rdi, -32(%rbp)
  movq %rsi, -40(%rbp)
  movq %rdx, -48(%rbp)
  movq %rcx, -56(%rbp)
  movq %rdi, -64(%rbp)
  movq %rsi, -72(%rbp)
  movq %rdi, -80(%rbp)
  movq %rdx, -88(%rbp)
  movq -72(%rbp), %rdi
  movq -80(%rbp), %rsi
  callq add
  movq %rax, %rdx
  movq -32(%rbp), %rdi
  movq -40(%rbp), %rsi
  movq -48(%rbp), %rdx
  movq -56(%rbp), %rcx
  movq -64(%rbp), %rdi
  movq -72(%rbp), %rsi
  movq -80(%rbp), %rdi
  movq -88(%rbp), %rdx
  movq %rdx, %rax
  jmp .L_mul_add_epilogue
.L_mul_add_epilogue:
  addq $256, %rsp
  leave
  ret

.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $176, %rsp
.L_main_entry:
  movq %rdi, -8(%rbp)
  movq $2, %rdi
  movq $3, %rsi
  movq $4, %rdx
  callq mul_add
  movq %rax, %rdi
  movq -8(%rbp), %rdi
  movq %rdi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $176, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
