# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $208, %rsp
.L_main_entry:
  leaq -64(%rbp), %rax
  movq %rax, %rdi
  movq %rdi, %rax
  movq $0, (%rax)
  jmp .L_main_while_cond
.L_main_while_cond:
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  cmpq $5, %rax
  setl %al
  movzbl %al, %eax
  movq %rax, %rdx
  movq %rdx, %rax
  movq $0, %rcx
  cmpq %rcx, %rax
  jne .L_main_while_body
  jmp .L_main_while_exit
.L_main_while_body:
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  addq $1, %rax
  movq %rax, %rdx
  movq %rdi, %rax
  movq %rdx, %rcx
  movq %rcx, (%rax)
  jmp .L_main_while_cond
.L_main_while_exit:
  movq %rdi, %rax
  movq (%rax), %rax
  movq %rax, %rsi
  movq %rsi, %rax
  jmp .L_main_epilogue
.L_main_epilogue:
  addq $208, %rsp
  leave
  ret


.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
