# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $16, %rsp
.L_main_entry:
  leaq -8(%rbp), %rax
  movq $3, (%rax)
  jmp .L_main_while_cond
.L_main_while_cond:
  movq (%rax), %rbx
  cmpq $0, %rbx
  cmpq $0, %rcx
  jne .L_main_while_body
  jmp .L_main_while_exit
.L_main_while_body:
  movq (%rax), %rdx
  movq %rdx, %rsi
  subq $1, %rsi
  movq %rsi, (%rax)
  jmp .L_main_while_cond
.L_main_while_exit:
  movq (%rax), %rdi
  movq %rdi, %rax
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
