# Generated by DAAD Compiler
.text
.globl main
main:
  pushq %rbp
  movq %rsp, %rbp
  subq $16, %rsp
.L_main_entry:
  leaq -8(%rbp), %rax
  movq $0, (%rax)
  leaq -16(%rbp), %rbx
  movq $0, (%rbx)
  jmp .L_main_while_cond
.L_main_while_cond:
  movq (%rax), %rcx
  cmpq $5, %rcx
  cmpq $0, %rdx
  jne .L_main_while_body
  jmp .L_main_while_exit
.L_main_while_body:
  movq (%rbx), %rsi
  movq %rsi, %rdi
  addq $2, %rdi
  movq %rdi, (%rbx)
  movq (%rax), %r8
  movq %r8, %r9
  addq $1, %r9
  movq %r9, (%rax)
  jmp .L_main_while_cond
.L_main_while_exit:
  movq (%rbx), %r10
  movq %r10, %rax
  leave
  ret

.section .rodata
  .align 8

.global _start
_start:
  callq main
  movq %rax, %rdi
  movq $60, %rax
  syscall
